module.exports.BUILT_IN_EXAMPLES = {
  'zh-HK': {
    '@sys.date-time': '上午十二',
    '@sys.date': '明天',
    '@sys.date-period': '四月',
    '@sys.time': '下午4:30',
    '@sys.time-period': '下午',
    '@sys.number': '1',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5美元',
    '@sys.percentage': '50％',
    '@sys.duration': '10分鐘',
    '@sys.age': '二十五歲',
    '@sys.currency-name': '美元',
    '@sys.zip-code': '266000',
    '@sys.geo-capital': '巴黎',
    '@sys.geo-country': '美國',
    '@sys.geo-city': '紐約',
    '@sys.location': '香港灣仔軒尼詩道265-267號',
    '@sys.email': 'user@example.com ',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': '斌蔚',
    '@sys.last-name': '王',
    '@sys.music-artist': '周杰倫',
    '@sys.color': '綠色',
    '@sys.language': '英語',
    '@sys.any': '花',
    '@sys.url': 'www.dialogflow.com',
  },
  'zh-CN': {
    '@sys.date-time': '上午十二点',
    '@sys.date': '明天',
    '@sys.date-period': '四月',
    '@sys.time': '下午4:30',
    '@sys.time-period': '下午',
    '@sys.number': '1',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5美元',
    '@sys.percentage': '50%',
    '@sys.duration': '10分钟',
    '@sys.age': '五岁',
    '@sys.currency-name': '美元',
    '@sys.address': '中国上海市静安区巨鹿路882号',
    '@sys.zip-code': '266000',
    '@sys.geo-capital': '巴黎',
    '@sys.geo-country': '美国',
    '@sys.geo-city': '纽约',
    '@sys.location': '台湾台中市西区林森路26-6号',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': '斌蔚',
    '@sys.last-name': '王',
    '@sys.music-artist': '周杰伦',
    '@sys.color': '绿色',
    '@sys.language': '英语',
    '@sys.any': '花',
    '@sys.url': 'www.dialogflow.com',
  },
  'zh-TW': {
    '@sys.date-time': '上午十二',
    '@sys.date': '明天',
    '@sys.date-period': '四月',
    '@sys.time': '下午4:30',
    '@sys.time-period': '下午',
    '@sys.number': '1',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5美元',
    '@sys.percentage': '50％',
    '@sys.duration': '10分鐘',
    '@sys.age': '二十五歲',
    '@sys.currency-name': '美元',
    '@sys.zip-code': '266000',
    '@sys.geo-capital': '巴黎',
    '@sys.geo-country': '美國',
    '@sys.geo-city': '紐約',
    '@sys.location': '10603台北市大安區金山南路2段55號',
    '@sys.email': 'user@example.com ',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': '斌蔚',
    '@sys.last-name': '王',
    '@sys.music-artist': '周杰倫',
    '@sys.color': '綠色',
    '@sys.language': '英語',
    '@sys.any': '花',
    '@sys.url': 'www.dialogflow.com',
  },
  da: {
    '@sys.date-time': '14:30',
    '@sys.date': 'i morgen',
    '@sys.date-period': 'april',
    '@sys.time': '16.3',
    '@sys.time-period': 'eftermiddag',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'tiende',
    '@sys.number-integer': '12',
    '@sys.unit-area': '10 kvadratmeter',
    '@sys.unit-currency': '5 Danske kroner',
    '@sys.unit-length': '10 meter',
    '@sys.unit-speed': '5 km/t',
    '@sys.unit-volume': '2 liter',
    '@sys.unit-weight': '5 kg',
    '@sys.unit-information': '250 megabytes',
    '@sys.temperature': '25 C',
    '@sys.currency-name': 'Danske kroner',
    '@sys.unit-area-name': 'kvadratmeter',
    '@sys.unit-length-name': 'meter',
    '@sys.unit-speed-name': 'kilometer i timen',
    '@sys.unit-volume-name': 'kubikmeter',
    '@sys.unit-weight-name': 'kilo',
    '@sys.unit-information-name': 'megabytes',
    '@sys.zip-code': '2750',
    '@sys.geo-capital': 'København',
    '@sys.geo-country': 'Danmark',
    '@sys.geo-city': 'Odense',
    '@sys.geo-state': '"Region Sjælland"',
    '@sys.given-name': 'Victor',
    '@sys.last-name': 'Nielsen',
    '@sys.music-artist': 'Lukas Graham',
    '@sys.music-genre': 'jazz',
    '@sys.color': 'grøn',
    '@sys.language': 'japansk',
    '@sys.any': 'blomst',
  },
  nl: {
    '@sys.date-time': '2.30 in de avond',
    '@sys.date': 'morgen',
    '@sys.date-period': 'april',
    '@sys.time': '4:30 in de middag',
    '@sys.time-period': 'middag',
    '@sys.number': 'een',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'tiende',
    '@sys.number-integer': '12',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-area': 'tien vierkante meter',
    '@sys.unit-currency': '3 euro',
    '@sys.unit-length': 'tien meter',
    '@sys.unit-speed': '5 km/u',
    '@sys.unit-volume': '2 liter',
    '@sys.unit-weight': '5 kilogram',
    '@sys.unit-information': '250 megabyte',
    '@sys.temperature': '25 F',
    '@sys.currency-name': 'euro',
    '@sys.unit-area-name': 'vierkante meter',
    '@sys.unit-length-name': 'meter',
    '@sys.unit-speed-name': 'kilometer per uur',
    '@sys.unit-volume-name': 'kubieke meter',
    '@sys.unit-weight-name': 'kilogram',
    '@sys.unit-information-name': 'megabyte',
    '@sys.zip-code': '1071 AA',
    '@sys.geo-capital': 'Amsterdam',
    '@sys.geo-country': 'Nederland',
    '@sys.geo-city': 'Delft',
    '@sys.geo-state': 'Groningen',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Lars',
    '@sys.last-name': 'Jansen',
    '@sys.music-artist': 'Doe Maar',
    '@sys.music-genre': 'pop',
    '@sys.color': 'groen',
    '@sys.language': 'Nederlands',
    '@sys.any': 'bloem',
    '@sys.url': 'www.dialogflow.com',
  },
  en: {
    '@sys.date-time': '2:30 PM',
    '@sys.date': 'tomorrow',
    '@sys.date-period': 'April',
    '@sys.time': '4:30 PM',
    '@sys.time-period': 'afternoon',
    '@sys.number': 'one',
    '@sys.cardinal': 'ten',
    '@sys.ordinal': 'tenth',
    '@sys.number-integer': '12',
    '@sys.number-sequence': '1 2 3',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-area': 'ten square feet',
    '@sys.unit-currency': '5 dollars',
    '@sys.unit-length': 'ten meters',
    '@sys.unit-speed': '5 km/h',
    '@sys.unit-volume': '2 liters',
    '@sys.unit-weight': '5 kilos',
    '@sys.unit-information': '250 megabytes',
    '@sys.percentage': '50%',
    '@sys.temperature': '',
    '@sys.duration': '10 minutes',
    '@sys.age': '5 y.o.',
    '@sys.currency-name': 'dollars',
    '@sys.unit-area-name': 'square meters',
    '@sys.unit-length-name': 'meters',
    '@sys.unit-speed-name': 'kilometer per hour',
    '@sys.unit-volume-name': 'cubic meters',
    '@sys.unit-weight-name': 'kilograms',
    '@sys.unit-information-name': 'megabytes',
    '@sys.address': '1600 Amphitheatre Pkwy, Mountain View, CA 94043',
    '@sys.zip-code': '94122',
    '@sys.geo-capital': 'Paris',
    '@sys.geo-country': 'United States',
    '@sys.geo-country-code': 'United Sates',
    '@sys.geo-city': 'New York',
    '@sys.geo-state': 'CA',
    '@sys.place-attraction': 'Golden Gate Bridge',
    '@sys.airport': 'Heathrow Airport',
    '@sys.location': '1600 Amphitheatre Pkwy, Mountain View, CA 94043',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'John',
    '@sys.last-name': 'Smith',
    '@sys.music-artist': 'Beatles',
    '@sys.music-genre': 'Blues',
    '@sys.color': 'green',
    '@sys.language': 'English',
    '@sys.any': 'flower',
    '@sys.url': 'www.dialogflow.com',
  },
  fr: {
    '@sys.date-time': '14h30',
    '@sys.date': 'demain',
    '@sys.date-period': 'avril',
    '@sys.time': '16h30',
    '@sys.time-period': 'après-midi',
    '@sys.number': 'un',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5 dollars',
    '@sys.unit-length': 'dix mètres',
    '@sys.percentage': '50%',
    '@sys.duration': '10 minutes',
    '@sys.age': '5 ans',
    '@sys.currency-name': 'dollars',
    '@sys.address': '8 Rue de Londres-15-15 Bis Rue de Clichy 75009 Paris France',
    '@sys.zip-code': '75009',
    '@sys.geo-country': 'États-Unis',
    '@sys.geo-city': 'New York',
    '@sys.geo-state': 'Île-de-France',
    '@sys.place-attraction': 'Tour Eiffel',
    '@sys.location': '8 Rue de Londres-15-15 Bis Rue de Clichy 75009 Paris France',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Sébastien',
    '@sys.last-name': 'Millet',
    '@sys.music-artist': 'Beatles',
    '@sys.color': 'vert',
    '@sys.language': 'Anglais',
    '@sys.any': 'fleur',
    '@sys.url': 'www.dialogflow.com',
  },
  de: {
    '@sys.date-time': '14:30 Uhr',
    '@sys.date': 'Morgen',
    '@sys.date-period': 'April',
    '@sys.time': '16:30 Uhr',
    '@sys.time-period': 'Nachmittag',
    '@sys.number': 'eins',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5 Dollar',
    '@sys.duration': '10 minuten',
    '@sys.unit-volume': '5 Kubikmeter',
    '@sys.unit-weight': '10 Kilogramm',
    '@sys.percentage': '50%',
    '@sys.currency-name': 'Dollar',
    '@sys.address': 'Unter den Linden 14 10117 Berlin Germany',
    '@sys.zip-code': '10178',
    '@sys.geo-country': 'Vereinigte Staaten',
    '@sys.geo-city': 'New York',
    '@sys.location': 'Unter den Linden 14 10117 Berlin Germany',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Tobias',
    '@sys.last-name': 'Müller',
    '@sys.music-artist': 'Beatles',
    '@sys.color': 'grün',
    '@sys.language': 'Englisch',
    '@sys.any': 'blume',
    '@sys.url': 'www.dialogflow.com',
  },
  hi: {
    '@sys.date-time': '2:30 शाम',
    '@sys.date': 'कल',
    '@sys.date-period': 'अप्रैल',
    '@sys.time': '4:30 शाम',
    '@sys.time-period': 'दोपहर',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'दसवाँ',
    '@sys.number-integer': '12',
    '@sys.unit-area': 'दस वर्ग फुट',
    '@sys.unit-currency': '3 यूरो',
    '@sys.unit-length': 'दस मीटर',
    '@sys.unit-speed': '5 किलोमीटर प्रति घंटा',
    '@sys.unit-volume': '2 लीटर',
    '@sys.unit-weight': '5 किलो',
    '@sys.unit-information': '250 मेगाबाइट',
    '@sys.temperature': '25 फारेनहाइट',
    '@sys.currency-name': 'यूरो',
    '@sys.unit-area-name': 'वर्ग मीटर',
    '@sys.unit-length-name': 'मीटर',
    '@sys.unit-speed-name': 'किलोमीटर प्रति घंटा',
    '@sys.unit-volume-name': 'क्यूबिक मीटर',
    '@sys.unit-weight-name': 'किलोग्राम',
    '@sys.unit-information-name': 'मेगाबाइट',
    '@sys.zip-code': '400051',
    '@sys.geo-capital': 'नई दिल्ली',
    '@sys.geo-country': 'भारत',
    '@sys.geo-city': 'मुम्बई',
    '@sys.geo-state': 'उत्तर प्रदेश',
    '@sys.given-name': 'अमित',
    '@sys.last-name': 'जैन',
    '@sys.music-artist': 'अरिजीत सिंह',
    '@sys.music-genre': 'शास्त्रीय',
    '@sys.color': 'हरा',
    '@sys.language': 'अंग्रेज़ी',
    '@sys.any': 'फूल',
  },
  id: {
    '@sys.date-time': '2.30 sore',
    '@sys.date': 'besok',
    '@sys.date-period': 'April',
    '@sys.time': '4.30 sore',
    '@sys.time-period': 'siang',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'kedua',
    '@sys.number-integer': '12',
    '@sys.unit-area': 'sepuluh meter persegi',
    '@sys.unit-currency': '5 rupiah',
    '@sys.unit-length': 'sepuluh meter',
    '@sys.unit-speed': '5 km/j',
    '@sys.unit-volume': '2 liter',
    '@sys.unit-weight': '5 kilo',
    '@sys.unit-information': '250 megabyte',
    '@sys.temperature': '25 C',
    '@sys.currency-name': 'rupiah',
    '@sys.unit-area-name': 'meter persegi',
    '@sys.unit-length-name': 'meter',
    '@sys.unit-speed-name': 'kilometer per jam',
    '@sys.unit-volume-name': 'meter kubik',
    '@sys.unit-weight-name': 'kilogram',
    '@sys.unit-information-name': 'megabyte',
    '@sys.zip-code': '10130',
    '@sys.geo-capital': 'Jakarta',
    '@sys.geo-country': 'Indonesia',
    '@sys.geo-city': 'Denpasar',
    '@sys.geo-state': 'Bali',
    '@sys.given-name': 'Dewi',
    '@sys.last-name': 'Yati',
    '@sys.music-artist': 'Noah',
    '@sys.music-genre': 'Pop',
    '@sys.color': 'hijau',
    '@sys.language': 'Inggris',
    '@sys.any': 'bunga',
  },
  it: {
    '@sys.date-time': '2:30 di sera',
    '@sys.date': 'domani',
    '@sys.date-period': 'aprile',
    '@sys.time': '4:30 di sera',
    '@sys.time-period': 'pomeriggio',
    '@sys.number': 'uno',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5 dollari',
    '@sys.percentage': '50%',
    '@sys.duration': '10 minuti',
    '@sys.age': '5 anni di età',
    '@sys.currency-name': 'dollari ',
    '@sys.address': 'Porta Nuova Isola, Building C, Via Federico Confalonieri 4 20124 Milan Italia',
    '@sys.zip-code': '80135',
    '@sys.geo-country': 'Stati Uniti',
    '@sys.geo-city': 'New York',
    '@sys.location': 'Porta Nuova Isola, Building C, Via Federico Confalonieri 4 20124 Milan Italia',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Filippo',
    '@sys.last-name': 'Ricci',
    '@sys.music-artist': 'Beatles',
    '@sys.color': 'verde',
    '@sys.language': 'Inglese',
    '@sys.any': 'fiore',
    '@sys.url': 'www.dialogflow.com',
  },
  ja: {
    '@sys.date-time': '午後12時',
    '@sys.date': '明日',
    '@sys.date-period': '四月',
    '@sys.time': '４時半',
    '@sys.time-period': '午後',
    '@sys.number': 'いち',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '５ドル',
    '@sys.duration': '10分',
    '@sys.currency-name': 'ドル',
    '@sys.address': '六本木ヒルズ森タワー 六本木6-10-1 東京都港区106-6126 日本',
    '@sys.zip-code': '〒140-0004',
    '@sys.geo-country': '米国',
    '@sys.geo-city': 'ニューヨーク',
    '@sys.place-attraction': '清水寺',
    '@sys.location': '六本木ヒルズ森タワー 六本木6-10-1 東京都港区106-6126 日本',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': '太郎',
    '@sys.last-name': '山田',
    '@sys.music-artist': 'ビートルズ',
    '@sys.color': '緑',
    '@sys.language': '英語',
    '@sys.any': '花',
    '@sys.url': 'www.dialogflow.com',
  },
  ko: {
    '@sys.date-time': '오후 2:30',
    '@sys.date': '내일',
    '@sys.date-period': '4 월',
    '@sys.time': '오후 4시 30 분',
    '@sys.time-period': '오후',
    '@sys.number': '하나',
    '@sys.cardinal': '열',
    '@sys.ordinal': '열 번째',
    '@sys.number-integer': '12',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-area': '10제곱미터',
    '@sys.unit-currency': '3원',
    '@sys.unit-length': '10미터',
    '@sys.unit-speed': '5 km/h',
    '@sys.unit-volume': '2리터',
    '@sys.unit-weight': '5 킬로그램',
    '@sys.unit-information': '250메가바이트',
    '@sys.temperature': '25 C',
    '@sys.currency-name': '원',
    '@sys.unit-area-name': '제곱미터',
    '@sys.unit-length-name': '미터',
    '@sys.unit-speed-name': 'km/h',
    '@sys.unit-volume-name': '세제곱미터',
    '@sys.unit-weight-name': '그램',
    '@sys.unit-information-name': '메가바이트',
    '@sys.zip-code': '100-031',
    '@sys.geo-capital': '서울특별시',
    '@sys.geo-country': '대한민국',
    '@sys.geo-city': '부산광역시',
    '@sys.geo-state': '강원도',
    '@sys.given-name': '수민',
    '@sys.last-name': '김',
    '@sys.music-artist': '방탄소년단',
    '@sys.music-genre': '재즈',
    '@sys.color': '노란색',
    '@sys.language': '영어',
    '@sys.any': '꽃',
    '@sys.url': 'www.dialogflow.com',
  },
  no: {
    '@sys.date-time': '14.3',
    '@sys.date': 'i morgen',
    '@sys.date-period': 'april',
    '@sys.time': '16:30',
    '@sys.time-period': 'ettermiddag',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'tiende',
    '@sys.number-integer': '12',
    '@sys.unit-area': '10 kvadratmeter',
    '@sys.unit-currency': '5 Norske kroner',
    '@sys.unit-length': '10 meter',
    '@sys.unit-speed': '5 km/t',
    '@sys.unit-volume': '2 liter',
    '@sys.unit-weight': '5 kg',
    '@sys.unit-information': '250 megabyte',
    '@sys.temperature': '25 C',
    '@sys.currency-name': 'Norske kroner',
    '@sys.unit-area-name': 'kvadratmeter',
    '@sys.unit-length-name': 'meter',
    '@sys.unit-speed-name': 'km/t',
    '@sys.unit-volume-name': 'kubikkmeter',
    '@sys.unit-weight-name': 'kilo',
    '@sys.unit-information-name': 'megabyte',
    '@sys.zip-code': '151',
    '@sys.geo-capital': 'Oslo',
    '@sys.geo-country': 'Norge',
    '@sys.geo-city': 'Bergen',
    '@sys.geo-state': 'Østfold',
    '@sys.given-name': 'Marte',
    '@sys.last-name': 'Hansen',
    '@sys.music-artist': 'Åge Aleksandersen',
    '@sys.music-genre': 'pop',
    '@sys.color': 'rød',
    '@sys.language': 'engelsk',
    '@sys.any': 'blomst',
  },
  pl: {
    '@sys.date-time': '14:30',
    '@sys.date': 'jutro',
    '@sys.date-period': 'kwiecień',
    '@sys.time': '16:30',
    '@sys.time-period': 'popołudnie',
    '@sys.number': 'jeden',
    '@sys.cardinal': 'dziesięć',
    '@sys.ordinal': 'dziesiąty',
    '@sys.number-integer': '12',
    '@sys.unit-area': '10 metrów kwadratowych',
    '@sys.unit-currency': '5 złotych',
    '@sys.unit-length': '10 metrów',
    '@sys.unit-speed': '5 km/h',
    '@sys.unit-volume': '2 litry',
    '@sys.unit-weight': '5 kg',
    '@sys.unit-information': '250 megabajtów',
    '@sys.temperature': '10 C',
    '@sys.currency-name': 'złoty',
    '@sys.unit-area-name': 'metry kwadratowe',
    '@sys.unit-length-name': 'metry',
    '@sys.unit-speed-name': 'mila na godzinę',
    '@sys.unit-volume-name': 'metry sześcienne',
    '@sys.unit-weight-name': 'kilogram',
    '@sys.unit-information-name': 'megabajty',
    '@sys.zip-code': '44-292',
    '@sys.geo-capital': 'Warszawa',
    '@sys.geo-country': 'Polska',
    '@sys.geo-city': 'Warszawa',
    '@sys.geo-state': 'województwo wielkopolskie',
    '@sys.given-name': 'Anna',
    '@sys.last-name': 'Nowak',
    '@sys.music-artist': 'Dawid Podsiadło',
    '@sys.music-genre': 'blues',
    '@sys.color': 'czerwony',
    '@sys.language': 'angielski',
    '@sys.any': 'kwiat',
  },
  pt: {
    '@sys.date-time': '14h30',
    '@sys.date': 'amanhã',
    '@sys.date-period': 'abril',
    '@sys.time': '4:30 da tarde',
    '@sys.time-period': 'tarde',
    '@sys.number': '1',
    '@sys.flight-number': 'LH4234',
    '@sys.zip-code': '1100-585',
    '@sys.geo-country': 'Estados Unidos',
    '@sys.geo-city': 'Nova York',
    '@sys.location': 'Avenida da Liberdade, 110 Lisbon, Portugal',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.language': 'Inglês',
    '@sys.any': 'flor',
    '@sys.url': 'www.dialogflow.com',
  },
  'pt-BR': {
    '@sys.date-time': '14h30',
    '@sys.date': 'amanhã',
    '@sys.date-period': 'abril',
    '@sys.time': '4:30 da tarde',
    '@sys.time-period': 'tarde',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'décimo',
    '@sys.number-integer': '12',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-area': '10 metros quadrados',
    '@sys.unit-currency': '3 euros',
    '@sys.unit-length': '10 metros',
    '@sys.unit-speed': '5 km/h',
    '@sys.unit-volume': '2 litros',
    '@sys.unit-weight': '5 kg',
    '@sys.unit-information': '250 megabytes',
    '@sys.temperature': '25 C',
    '@sys.currency-name': 'euro',
    '@sys.unit-area-name': 'm quadrado',
    '@sys.unit-length-name': 'metros',
    '@sys.unit-speed-name': 'km/h',
    '@sys.unit-volume-name': 'metros cúbicos',
    '@sys.unit-weight-name': 'quilos',
    '@sys.unit-information-name': 'megabytes',
    '@sys.zip-code': '1100-585',
    '@sys.geo-capital': 'Paris',
    '@sys.geo-country': 'Estados Unidos',
    '@sys.geo-city': 'Nova York',
    '@sys.geo-state': 'Bahia',
    '@sys.location': 'Av. Brigadeiro Faria Lima, 3477 São Paulo 04538-133, Brazil',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Carlos',
    '@sys.last-name': 'Souza',
    '@sys.music-artist': 'Elis Regina',
    '@sys.music-genre': 'samba',
    '@sys.color': 'verde',
    '@sys.language': 'Inglês',
    '@sys.any': 'flor',
    '@sys.url': 'www.dialogflow.com',
  },
  ru: {
    '@sys.date-time': '2:30 вечера',
    '@sys.date': 'завтра',
    '@sys.date-period': 'апрель',
    '@sys.time': '4:30 вечера',
    '@sys.time-period': 'днём',
    '@sys.number': 'один',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5 долларов',
    '@sys.percentage': '50%',
    '@sys.duration': '10 минут',
    '@sys.currency-name': 'доллары',
    '@sys.address': 'Останкинская ул, д.22, Москва, Россия',
    '@sys.zip-code': '127422',
    '@sys.geo-capital': 'Париж',
    '@sys.geo-country': 'США',
    '@sys.geo-city': 'Нью-Йорк',
    '@sys.location': 'ул. Балчуг, 7, Москва, 115035, Россия',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Петя',
    '@sys.last-name': 'Петров',
    '@sys.patronymic-name': 'Петрович',
    '@sys.music-artist': 'Beatles',
    '@sys.color': 'зелёный',
    '@sys.language': 'английский',
    '@sys.any': 'цветок',
    '@sys.url': 'www.dialogflow.com',
  },
  es: {
    '@sys.date-time': '2:30 PM',
    '@sys.date': 'mañana',
    '@sys.date-period': 'abril',
    '@sys.time': '4:30 PM',
    '@sys.time-period': 'tarde',
    '@sys.number': 'uno',
    '@sys.flight-number': 'LH4234',
    '@sys.unit-currency': '5 dólares',
    '@sys.percentage': '50%',
    '@sys.duration': '10 minutos',
    '@sys.currency-name': 'dólares',
    '@sys.address': 'Plaza Pablo Ruiz Picasso, I Madrid 28020, España',
    '@sys.zip-code': '46011',
    '@sys.geo-capital': 'París',
    '@sys.geo-country': 'Estados Unidos',
    '@sys.geo-city': 'Nueva York',
    '@sys.geo-state': 'Andalucía',
    '@sys.location': 'Plaza Pablo Ruiz Picasso, I',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.given-name': 'Javier',
    '@sys.last-name': 'García',
    '@sys.music-artist': 'Beatles',
    '@sys.music-genre': 'clásica',
    '@sys.color': 'verde',
    '@sys.language': 'Inglés',
    '@sys.any': 'flor',
    '@sys.url': 'www.dialogflow.com',
  },
  sv: {
    '@sys.date-time': '14.3',
    '@sys.date': 'i morgon',
    '@sys.date-period': 'april',
    '@sys.time': '16:30',
    '@sys.time-period': 'eftermiddag',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'tionde',
    '@sys.number-integer': '12',
    '@sys.unit-area': 'tio kvadratmeter',
    '@sys.unit-currency': '5 svenska kronor',
    '@sys.unit-length': 'tio meter',
    '@sys.unit-speed': '5 km/h',
    '@sys.unit-volume': '2 liter',
    '@sys.unit-weight': '5 kilo',
    '@sys.unit-information': '250 megabyte',
    '@sys.temperature': '25 F',
    '@sys.currency-name': 'svenska kronor',
    '@sys.unit-area-name': 'kvadratmeter',
    '@sys.unit-length-name': 'meter',
    '@sys.unit-speed-name': 'kilometer i timmen',
    '@sys.unit-volume-name': 'kubikmeter',
    '@sys.unit-weight-name': 'kilogram',
    '@sys.unit-information-name': 'megabyte',
    '@sys.zip-code': '111 22',
    '@sys.geo-capital': 'Stockholm',
    '@sys.geo-country': 'Sverige',
    '@sys.geo-city': 'Malmö',
    '@sys.geo-state': 'Dalarna',
    '@sys.given-name': 'Johan',
    '@sys.last-name': 'Svensson',
    '@sys.music-artist': 'ABBA',
    '@sys.music-genre': 'Pop',
    '@sys.color': 'grön',
    '@sys.language': 'engelsk',
    '@sys.any': 'Blomma',
  },
  th: {
    '@sys.date-time': '14.30 น.',
    '@sys.date': 'พรุ่งนี้',
    '@sys.date-period': 'เมษายน',
    '@sys.time': '16:30 น',
    '@sys.time-period': 'ตอนบ่าย',
    '@sys.number': '1',
    '@sys.cardinal': '10',
    '@sys.ordinal': 'ที่สิบ',
    '@sys.number-integer': '12',
    '@sys.unit-area': '10 ตารางเมตร',
    '@sys.unit-currency': '5 บาท',
    '@sys.unit-length': '10 เมตร',
    '@sys.unit-speed': '5 กม./ชม.',
    '@sys.unit-volume': '2 ลิตร',
    '@sys.unit-weight': '5 กิโลกรัม',
    '@sys.unit-information': '250 เมกะไบต์',
    '@sys.temperature': '25 C',
    '@sys.currency-name': 'เงินบาท',
    '@sys.unit-area-name': 'ตารางเมตร',
    '@sys.unit-length-name': 'เมตร',
    '@sys.unit-speed-name': 'กิโลเมตรต่อชั่วโมง',
    '@sys.unit-volume-name': 'ลูกบาศก์เมตร',
    '@sys.unit-weight-name': 'กิโลกรัม',
    '@sys.unit-information-name': 'เมกะไบต์',
    '@sys.zip-code': '10300',
    '@sys.geo-capital': 'กรุงเทพมหานคร',
    '@sys.geo-country': 'ประเทศไทย',
    '@sys.geo-city': 'เมืองพัทยา',
    '@sys.geo-state': 'เชียงราย',
    '@sys.given-name': 'สุชาติ',
    '@sys.last-name': 'จงเจริญ',
    '@sys.music-artist': 'เบิร์ด ธงชัย',
    '@sys.music-genre': 'ป็อป',
    '@sys.color': 'สีเขียว',
    '@sys.language': 'อังกฤษ',
    '@sys.any': 'ดอกไม้',
  },
  tr: {
    '@sys.date-time': '14:30',
    '@sys.date': 'yarın',
    '@sys.date-period': 'Nisan',
    '@sys.time': '16:30',
    '@sys.time-period': 'öğleden sonra',
    '@sys.number': 'bir',
    '@sys.cardinal': 'on',
    '@sys.ordinal': 'onuncu',
    '@sys.number-integer': '12',
    '@sys.unit-area': '10 metrekare',
    '@sys.unit-currency': '5 dolar',
    '@sys.unit-length': '10 metre',
    '@sys.unit-speed': '5 km saat',
    '@sys.unit-volume': '2 litre',
    '@sys.unit-weight': '5 kilogram',
    '@sys.unit-information': '250 megabayt',
    '@sys.temperature': '10 C',
    '@sys.currency-name': 'dolar',
    '@sys.unit-area-name': 'metrekare',
    '@sys.unit-length-name': 'metre',
    '@sys.unit-speed-name': 'mil bölü saat',
    '@sys.unit-volume-name': 'metreküp',
    '@sys.unit-weight-name': 'kilo',
    '@sys.unit-information-name': 'megabayt',
    '@sys.zip-code': '34975',
    '@sys.geo-capital': 'Ankara',
    '@sys.geo-country': 'Türkiye',
    '@sys.geo-city': 'İstanbul',
    '@sys.geo-state': 'Adana ili',
    '@sys.given-name': '"Abdullah"',
    '@sys.last-name': '"Yıldırım"',
    '@sys.music-artist': 'Tarkan',
    '@sys.music-genre': 'rock',
    '@sys.color': 'yeşil',
    '@sys.language': 'Türkçe',
    '@sys.any': 'çiçek',
  },
  uk: {
    '@sys.date-time': 'завтра о 4:30 вечора',
    '@sys.date': 'завтра',
    '@sys.date-period': 'квітень',
    '@sys.time': '4:30 вечора',
    '@sys.time-period': 'післяобідній час',
    '@sys.number': 'один',
    '@sys.flight-number': 'LH4234',
    '@sys.email': 'user@example.com',
    '@sys.phone-number': '(123) 456 7890',
    '@sys.any': 'квітка',
    '@sys.url': 'www.dialogflow.com',
  },
};

module.exports.LOCALES = {
  HK: 'zh-HK',
  CN: 'zh-CN',
  TW: 'zh-TW',
  DA: 'da',
  NL: 'nl',
  EN: 'en',
  FR: 'fr',
  DE: 'de',
  HI: 'hi',
  ID: 'id',
  IT: 'it',
  JA: 'ja',
  KO: 'ko',
  NO: 'no',
  PL: 'pl',
  PT: 'pt',
  BR: 'pt-BR',
  RU: 'ru',
  ES: 'es',
  SV: 'sv',
  TH: 'th',
  TR: 'tr',
  UK: 'uk',
};

module.exports.WelcomeIntent = {
  name: 'Default Welcome Intent',
  auto: true,
  contexts: [],
  responses: [
    {
      resetContexts: false,
      action: 'input.welcome',
      affectedContexts: [],
      parameters: [],
      messages: [
        {
          type: 0,
          lang: 'en',
          speech: [
            'Hi! How are you doing?',
            'Hello! How can I help you?',
            'Good day! What can I do for you today?',
            'Greetings! How can I assist?',
          ],
        },
      ],
      defaultResponsePlatforms: {},
      speech: [],
    },
  ],
  priority: 500000,
  webhookUsed: true,
  webhookForSlotFilling: false,
  lastUpdate: 1548791074,
  fallbackIntent: false,
  events: [
    {
      name: 'WELCOME',
    },
  ],
};

module.exports.FallbackIntent = {
  name: 'Default Fallback Intent',
  auto: true,
  contexts: [],
  responses: [
    {
      resetContexts: false,
      action: 'input.unknown',
      affectedContexts: [],
      parameters: [],
      messages: [
        {
          type: 0,
          lang: 'en',
          speech: [
            'I didn\u0027t get that. Can you say it again?',
            'I missed what you said. What was that?',
            'Sorry, could you say that again?',
            'Sorry, can you say that again?',
            'Can you say that again?',
            'Sorry, I didn\u0027t get that. Can you rephrase?',
            'Sorry, what was that?',
            'One more time?',
            'What was that?',
            'Say that one more time?',
            'I didn\u0027t get that. Can you repeat?',
            'I missed that, say that again?',
          ],
        },
      ],
      defaultResponsePlatforms: {},
      speech: [],
    },
  ],
  priority: 500000,
  webhookUsed: true,
  webhookForSlotFilling: false,
  lastUpdate: 1548793234,
  fallbackIntent: true,
  events: [],
};

module.exports.WelcomeIntentEntries = [
  {
    id: '6d8403a4-6216-4843-bac3-7fdabac5c676',
    data: [
      {
        text: 'just going to say hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '25f4ea9e-4880-493e-bcdc-70f77aee645a',
    data: [
      {
        text: 'heya',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '37e30f9c-03f4-4c94-80cd-8be57781c9a4',
    data: [
      {
        text: 'hello hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'a99882de-a7e5-480a-8faf-9d1a13645288',
    data: [
      {
        text: 'howdy',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '5e21d4d7-9f38-4313-a8d4-bd3d189d54ab',
    data: [
      {
        text: 'hey there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'efb1af51-96ab-426a-aebb-58f38c3c42a7',
    data: [
      {
        text: 'hi there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 1,
    updated: 0,
  },
  {
    id: 'c5a560e4-4d68-4f53-a294-d0af158d735d',
    data: [
      {
        text: 'greetings',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '25e8269c-d258-4b76-91c8-1f6c8ba86421',
    data: [
      {
        text: 'hey',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'ad989fad-ec0a-49ae-bc79-69c883eaa3ff',
    data: [
      {
        text: 'long time no see',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '84c92606-7819-4584-b744-28a0dd5653f2',
    data: [
      {
        text: 'hello',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '3b45b1c0-5982-4817-8297-540d6628f138',
    data: [
      {
        text: 'lovely day isn\u0027t it',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '943d065c-4cca-4103-ad6a-3dc8e9e028df',
    data: [
      {
        text: 'I greet you',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '55eeca1b-652e-47de-9030-257b20b3217f',
    data: [
      {
        text: 'hello again',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '67d55251-ca6a-4305-9aa1-a09bf904c217',
    data: [
      {
        text: 'hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'c836c669-3bb4-47c0-adf6-df058f4a975b',
    data: [
      {
        text: 'hello there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'e94524f1-6b57-4ca3-9aeb-d3b229539756',
    data: [
      {
        text: 'a good day',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '6d8403a4-6216-4843-bac3-7fdabac5c676',
    data: [
      {
        text: 'just going to say hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '25f4ea9e-4880-493e-bcdc-70f77aee645a',
    data: [
      {
        text: 'heya',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '37e30f9c-03f4-4c94-80cd-8be57781c9a4',
    data: [
      {
        text: 'hello hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'a99882de-a7e5-480a-8faf-9d1a13645288',
    data: [
      {
        text: 'howdy',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '5e21d4d7-9f38-4313-a8d4-bd3d189d54ab',
    data: [
      {
        text: 'hey there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'efb1af51-96ab-426a-aebb-58f38c3c42a7',
    data: [
      {
        text: 'hi there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 1,
    updated: 0,
  },
  {
    id: 'c5a560e4-4d68-4f53-a294-d0af158d735d',
    data: [
      {
        text: 'greetings',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '25e8269c-d258-4b76-91c8-1f6c8ba86421',
    data: [
      {
        text: 'hey',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'ad989fad-ec0a-49ae-bc79-69c883eaa3ff',
    data: [
      {
        text: 'long time no see',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '84c92606-7819-4584-b744-28a0dd5653f2',
    data: [
      {
        text: 'hello',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '3b45b1c0-5982-4817-8297-540d6628f138',
    data: [
      {
        text: 'lovely day isn\u0027t it',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '943d065c-4cca-4103-ad6a-3dc8e9e028df',
    data: [
      {
        text: 'I greet you',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '55eeca1b-652e-47de-9030-257b20b3217f',
    data: [
      {
        text: 'hello again',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: '67d55251-ca6a-4305-9aa1-a09bf904c217',
    data: [
      {
        text: 'hi',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'c836c669-3bb4-47c0-adf6-df058f4a975b',
    data: [
      {
        text: 'hello there',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
  {
    id: 'e94524f1-6b57-4ca3-9aeb-d3b229539756',
    data: [
      {
        text: 'a good day',
        userDefined: false,
      },
    ],
    isTemplate: false,
    count: 0,
    updated: 0,
  },
];
