const testSkill = {
  account_linking: null,
  alexa_events: null,
  amzn_id: null,
  created: '2019-02-15T22:25:56.687Z',
  diagram: 'e9f52b0622f08ff1b21137bae05a242b',
  error_prompt: null,
  fulfillment: {},
  global: ['sessions', 'user_id', 'timestamp', 'platform', 'locale', 'access_token'],
  google_publish_info: {},
  intents: [
    {
      inputs: [],
      key: 'M5s3gMETzsul',
      name: 'intent_one',
      open: true,
    },
  ],
  inv_name: 'Test Skill',
  last_save: '2019-02-15T22:25:57.304Z',
  live: false,
  locales: ['en-US'],
  name: 'Test Skill',
  platform: 'alexa',
  preview: false,
  repeat: 100,
  restart: true,
  resume_prompt: null,
  review: false,
  skill_id: 'L8mr69wm4K',
  slots: [],
};
exports.testSkill = testSkill;
