language: node_js
node_js:
  - "10"
services:
  - postgresql
  - redis-server
before_script:
  - ./scripts/ecr_credentials.sh
  - ./scripts/before_test.sh
stage: 'Unit Tests'
script: npm run unit_tests
stage: 'Integration Tests'
script: npm run integration_tests
after_script:
  - ./scripts/after_test.sh
addons:
  hosts:
    - dynamodb-local