status = [
  "ci/circleci: update_%_track",
  "ci/circleci: unit-tests",
  "ci/circleci: integration-tests",
  "ci/circleci: lint-report",
  "ci/circleci: lint-dockerfile",
  "ci/circleci: sonarcloud-scan",
  "ci/circleci: analyze-dependencies",
  "ci/circleci: dependency-tests",
  "ci/circleci: build",
  # "ci/circleci: run-e2e-tests",
  "ci/circleci: run-smoke-tests",
  # "ci/circleci: build-e2e-tests",
  "ci/circleci: provision-env",
  "ci/circleci: prepare-env",
  "ci/circleci: release-env",
]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = "### Implementation details. How do you make this change?"
required_approvals = 1
update_base_for_deletes = true
