status = [
  "ci/circleci: update_%s_track",
  "ci/circleci: test",
  "ci/circleci: build",
  "ci/circleci: run-e2e-tests",
  "ci/circleci: build-e2e-tests",
  "ci/circleci: provision-env",
  "ci/circleci: prepare-env",
  "ci/circleci: old_e2e_tests",
]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = "### Implementation details. How do you make this change?"
required_approvals=1
