FROM node:11 AS build

ARG build_NPM_TOKEN
ENV NODE_OPTIONS=--max-old-space-size=2048
ENV NPM_TOKEN=${build_NPM_TOKEN}

WORKDIR /app
COPY . .

RUN echo $NPM_TOKEN > .npmrc
RUN yarn install
RUN yarn storybook:build

FROM nginx:stable

COPY --from=build /app/storybook_build /var/www
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
