sonar.organization=voiceflow
sonar.projectKey=voiceflow_creator-app
sonar.projectName=creator-app
sonar.sources=src
sonar.tests=test
sonar.eslint.reportPaths=sonar/report.json
sonar.typescript.tsconfigPath=./tsconfig.json
sonar.javascript.lcov.reportPaths=nyc_coverage_unit/lcov.info,jest_coverage/lcov.info
sonar.css.stylelint.reportPaths=sonar/report_css.json
