sonar.organization=voiceflow
sonar.projectKey=voiceflow_creator-app
sonar.projectName=creator-app
sonar.sources=src
sonar.tests=test
sonar.eslint.reportPaths=sonar/report.json
sonar.typescript.tsconfigPath=./tsconfig.json
sonar.coverage.exclusions=**/**
sonar.css.stylelint.reportPaths=sonar/report_css.json
