import * as utils from '../../utils';
import { createDividerMenuItemOption } from '../NestedMenu';

export interface Country {
  value: string;
  divider?: boolean;
  booster: number;
  alternative: string;
  code: string;
  searchAlternative: string;
  searchValue: string;
}

const COUNTRIES = [
  {
    value: 'United States',
    alternative: 'US USA United States of America',
    code: 'US',
    booster: 3.5,
  },
  createDividerMenuItemOption('divider'),
  { value: 'Afghanistan', alternative: 'AF افغانستان', code: 'AF' },
  { value: 'Aland Islands', alternative: 'AX Aaland Aland', booster: 0.5, code: 'AX' },
  { value: 'Albania', alternative: 'AL', code: 'AL' },
  { value: 'Algeria', alternative: 'DZ الجزائر', code: 'DZ' },
  { value: 'American Samoa', alternative: 'AS', booster: 0.5, code: 'AS' },
  { value: 'Andorra', alternative: 'AD', booster: 0.5, code: 'AD' },
  { value: 'Angola', alternative: 'AO', code: 'AO' },
  { value: 'Anguilla', alternative: 'AI', booster: 0.5, code: 'AI' },
  { value: 'Antarctica', alternative: 'AQ', booster: 0.5, code: 'AQ' },
  { value: 'Antigua and Barbuda', alternative: 'AG', booster: 0.5, code: 'AG' },
  { value: 'Argentina', alternative: 'AR', code: 'AR' },
  { value: 'Armenia', alternative: 'AM Հայաստան', code: 'AM' },
  { value: 'Aruba', alternative: 'AW', booster: 0.5, code: 'AW' },
  { value: 'Australia', alternative: 'AU', booster: 1.5, code: 'AU' },
  { value: 'Austria', alternative: 'AT Österreich Osterreich Oesterreich ', code: 'AT' },
  { value: 'Azerbaijan', alternative: 'AZ', code: 'AZ' },
  { value: 'Bahamas', alternative: 'BS', code: 'BS' },
  { value: 'Bahrain', alternative: 'BH البحرين', code: 'BH' },
  { value: 'Bangladesh', alternative: 'BD বাংলাদেশ', booster: 2, code: 'BD' },
  { value: 'Barbados', alternative: 'BB', code: 'BB' },
  { value: 'Belarus', alternative: 'BY Беларусь', code: 'BY' },
  {
    value: 'Belgium',
    alternative: 'BE België Belgie Belgien Belgique',
    booster: 1.5,
    code: 'BE',
  },
  { value: 'Belize', alternative: 'BZ', code: 'BZ' },
  { value: 'Benin', alternative: 'BJ', code: 'BJ' },
  { value: 'Bermuda', alternative: 'BM', booster: 0.5, code: 'BM' },
  { value: 'Bhutan', alternative: 'BT भूटान', code: 'BT' },
  { value: 'Bolivia', alternative: 'BO', code: 'BO' },
  { value: 'Bonaire, Saint Eustatius and Saba', alternative: 'BQ', code: 'BQ' },
  {
    value: 'Bosnia and Herzegovina',
    alternative: 'BA BiH Bosna i Hercegovina Босна и Херцеговина',
    code: 'BA',
  },
  { value: 'Botswana', alternative: 'BW', code: 'BW' },
  { value: 'Bouvet Island', alternative: 'BV', code: 'BV' },
  { value: 'Brazil', alternative: 'BR Brasil', booster: 2, code: 'BR' },
  { value: 'British Indian Ocean Territory', alternative: 'IO', code: 'IO' },
  { value: 'British Virgin Islands', alternative: 'VG', booster: 0.5, code: 'VG' },
  { value: 'Brunei', alternative: 'BN', code: 'BN' },
  { value: 'Bulgaria', alternative: 'BG България', code: 'BG' },
  { value: 'Burkina Faso', alternative: 'BF', code: 'BF' },
  { value: 'Burundi', alternative: 'BI', code: 'BI' },
  { value: 'Cambodia', alternative: 'KH កម្ពុជា', code: 'KH' },
  { value: 'Cameroon', alternative: 'CM', code: 'CM' },
  { value: 'Canada', alternative: 'CA', booster: 2.5, code: 'CA' },
  { value: 'Cape Verde', alternative: 'CV Cabo', code: 'CV' },
  { value: 'Cayman Islands', alternative: 'KY', booster: 0.5, code: 'KY' },
  { value: 'Central African Republic', alternative: 'CF', code: 'CF' },
  { value: 'Chad', alternative: 'TD تشاد‎ Tchad', code: 'TD' },
  { value: 'Chile', alternative: 'CL', code: 'CL' },
  {
    value: 'China',
    alternative: 'CN Zhongguo Zhonghua Peoples Republic 中国/中华',
    booster: 3.5,
    code: 'CN',
  },
  { value: 'Christmas Island', alternative: 'CX', booster: 0.5, code: 'CX' },
  { value: 'Cocos Islands', alternative: 'CC', booster: 0.5, code: 'CC' },
  { value: 'Colombia', alternative: 'CO', code: 'CO' },
  { value: 'Comoros', alternative: 'KM جزر القمر', code: 'KM' },
  { value: 'Cook Islands', alternative: 'CK', booster: 0.5, code: 'CK' },
  { value: 'Costa Rica', alternative: 'CR', code: 'CR' },
  { value: 'Croatia', alternative: 'HR Hrvatska', code: 'HR' },
  { value: 'Cuba', alternative: 'CU', code: 'CU' },
  { value: 'Curacao', alternative: 'CW', code: 'CW' },
  { value: 'Cyprus', alternative: 'CY Κύπρος Kýpros Kıbrıs', code: 'CY' },
  { value: 'Czech Republic', alternative: 'CZ Česká Ceska', code: 'CZ' },
  { value: 'Democratic Republic of the Congo', alternative: 'CD Congo-Brazzaville Repubilika ya Kongo', code: 'CD' },
  { value: 'Denmark', alternative: 'DK Danmark', booster: 1.5, code: 'DK' },
  { value: 'Djibouti', alternative: 'DJ جيبوتي‎ Jabuuti Gabuuti', code: 'DJ' },
  { value: 'Dominica', alternative: 'DM Dominique', booster: 0.5, code: 'DM' },
  { value: 'Dominican Republic', alternative: 'DO', code: 'DO' },
  { value: 'East Timor', alternative: 'TL', code: 'TL' },
  { value: 'Ecuador', alternative: 'EC', code: 'EC' },
  { value: 'Egypt', alternative: 'EG', booster: 1.5, code: 'EG' },
  { value: 'El Salvador', alternative: 'SV', code: 'SV' },
  { value: 'Equatorial Guinea', alternative: 'GQ', code: 'GQ' },
  { value: 'Eritrea', alternative: 'ER إرتريا ኤርትራ', code: 'ER' },
  { value: 'Estonia', alternative: 'EE Eesti', code: 'EE' },
  { value: 'Ethiopia', alternative: 'ET ኢትዮጵያ', code: 'ET' },
  { value: 'Falkland Islands', alternative: 'FK', booster: 0.5, code: 'FK' },
  { value: 'Faroe Islands', alternative: 'FO Føroyar Færøerne', booster: 0.5, code: 'FO' },
  { value: 'Fiji', alternative: 'FJ Viti फ़िजी', code: 'FJ' },
  { value: 'Finland', alternative: 'FI Suomi', code: 'FI' },
  { value: 'France', alternative: 'FR République française', booster: 2.5, code: 'FR' },
  { value: 'French Guiana', alternative: 'GF', code: 'GF' },
  { value: 'French Polynesia', alternative: 'PF Polynésie française', code: 'PF' },
  { value: 'French Southern Territories', alternative: 'TF', code: 'TF' },
  { value: 'Gabon', alternative: 'GA République Gabonaise', code: 'GA' },
  { value: 'Gambia', alternative: 'GM', code: 'GM' },
  { value: 'Georgia', alternative: 'GE საქართველო', code: 'GE' },
  { value: 'Germany', alternative: 'DE Bundesrepublik Deutschland', booster: 3, code: 'DE' },
  { value: 'Ghana', alternative: 'GH', code: 'GH' },
  { value: 'Gibraltar', alternative: 'GI', booster: 0.5, code: 'GI' },
  { value: 'Greece', alternative: 'GR Ελλάδα', booster: 1.5, code: 'GR' },
  { value: 'Greenland', alternative: 'GL grønland', booster: 0.5, code: 'GL' },
  { value: 'Grenada', alternative: 'GD', code: 'GD' },
  { value: 'Guadeloupe', alternative: 'GP', code: 'GP' },
  { value: 'Guam', alternative: 'GU', code: 'GU' },
  { value: 'Guatemala', alternative: 'GT', code: 'GT' },
  { value: 'Guernsey', alternative: 'GG', booster: 0.5, code: 'GG' },
  { value: 'Guinea', alternative: 'GN', code: 'GN' },
  { value: 'Guinea-Bissau', alternative: 'GW', code: 'GW' },
  { value: 'Guyana', alternative: 'GY', code: 'GY' },
  { value: 'Haiti', alternative: 'HT', code: 'HT' },
  { value: 'Heard Island and McDonald Islands', alternative: 'HM', code: 'HM' },
  { value: 'Honduras', alternative: 'HN', code: 'HN' },
  { value: 'Hong Kong', alternative: 'HK 香港', code: 'HK' },
  { value: 'Hungary', alternative: 'HU Magyarország', code: 'HU' },
  { value: 'Iceland', alternative: 'IS Island', code: 'IS' },
  { value: 'India', alternative: 'IN भारत गणराज्य Hindustan', booster: 3, code: 'IN' },
  { value: 'Indonesia', alternative: 'ID', booster: 2, code: 'ID' },
  { value: 'Iran', alternative: 'IR ایران', code: 'IR' },
  { value: 'Iraq', alternative: 'IQ العراق‎', code: 'IQ' },
  { value: 'Ireland', alternative: 'IE Éire', booster: 1.2, code: 'IE' },
  { value: 'Isle of Man', alternative: 'IM', booster: 0.5, code: 'IM' },
  { value: 'Israel', alternative: 'IL إسرائيل ישראל', code: 'IL' },
  { value: 'Italy', alternative: 'IT Italia', booster: 2, code: 'IT' },
  { value: 'Ivory Coast', alternative: 'CI Cote dIvoire', code: 'CI' },
  { value: 'Jamaica', alternative: 'JM', code: 'JM' },
  { value: 'Japan', alternative: 'JP Nippon Nihon 日本', booster: 2.5, code: 'JP' },
  { value: 'Jersey', alternative: 'JE', booster: 0.5, code: 'JE' },
  { value: 'Jordan', alternative: 'JO الأردن', code: 'JO' },
  { value: 'Kazakhstan', alternative: 'KZ Қазақстан Казахстан', code: 'KZ' },
  { value: 'Kenya', alternative: 'KE', code: 'KE' },
  { value: 'Kiribati', alternative: 'KI', code: 'KI' },
  { value: 'Kosovo', alternative: 'XK', code: 'XK' },
  { value: 'Kuwait', alternative: 'KW الكويت', code: 'KW' },
  { value: 'Kyrgyzstan', alternative: 'KG Кыргызстан', code: 'KG' },
  { value: 'Laos', alternative: 'LA', code: 'LA' },
  { value: 'Latvia', alternative: 'LV Latvija', code: 'LV' },
  { value: 'Lebanon', alternative: 'LB لبنان', code: 'LB' },
  { value: 'Lesotho', alternative: 'LS', code: 'LS' },
  { value: 'Liberia', alternative: 'LR', code: 'LR' },
  { value: 'Libya', alternative: 'Libyan Arab Jamahiriya LY ليبيا', code: 'LY' },
  { value: 'Liechtenstein', alternative: 'LI', code: 'LI' },
  { value: 'Lithuania', alternative: 'LT Lietuva', code: 'LT' },
  { value: 'Luxembourg', alternative: 'LU', code: 'LU' },
  { value: 'Macao', alternative: 'MO', code: 'MO' },
  { value: 'Macedonia', alternative: 'MK Македонија', code: 'MK' },
  { value: 'Madagascar', alternative: 'MG Madagasikara', code: 'MG' },
  { value: 'Malawi', alternative: 'MW', code: 'MW' },
  { value: 'Malaysia', alternative: 'MY', code: 'MY' },
  { value: 'Maldives', alternative: 'MV', code: 'MV' },
  { value: 'Mali', alternative: 'ML', code: 'ML' },
  { value: 'Malta', alternative: 'MT', code: 'MT' },
  { value: 'Marshall Islands', alternative: 'MH', booster: 0.5, code: 'MH' },
  { value: 'Martinique', alternative: 'MQ', code: 'MQ' },
  { value: 'Mauritania', alternative: 'MR الموريتانية', code: 'MR' },
  { value: 'Mauritius', alternative: 'MU', code: 'MU' },
  { value: 'Mayotte', alternative: 'YT', code: 'YT' },
  { value: 'Mexico', alternative: 'MX Mexicanos', booster: 1.5, code: 'MX' },
  { value: 'Micronesia', alternative: 'FM', code: 'FM' },
  { value: 'Moldova', alternative: 'MD', code: 'MD' },
  { value: 'Monaco', alternative: 'MC', code: 'MC' },
  { value: 'Mongolia', alternative: 'MN Mongγol ulus Монгол улс', code: 'MN' },
  { value: 'Montenegro', alternative: 'ME', code: 'ME' },
  { value: 'Montserrat', alternative: 'MS', booster: 0.5, code: 'MS' },
  { value: 'Morocco', alternative: 'MA المغرب', code: 'MA' },
  { value: 'Mozambique', alternative: 'MZ Moçambique', code: 'MZ' },
  { value: 'Myanmar', alternative: 'MM', code: 'MM' },
  { value: 'Namibia', alternative: 'NA Namibië', code: 'NA' },
  { value: 'Nauru', alternative: 'NR Naoero', booster: 0.5, code: 'NR' },
  { value: 'Nepal', alternative: 'NP नेपाल', code: 'NP' },
  { value: 'Netherlands', alternative: 'NL Holland Nederland', booster: 1.5, code: 'NL' },
  { value: 'New Caledonia', alternative: 'NC', booster: 0.5, code: 'NC' },
  { value: 'New Zealand', alternative: 'NZ Aotearoa', code: 'NZ' },
  { value: 'Nicaragua', alternative: 'NI', code: 'NI' },
  { value: 'Niger', alternative: 'NE Nijar', code: 'NE' },
  { value: 'Nigeria', alternative: 'NG Nijeriya Naíjíríà', booster: 1.5, code: 'NG' },
  { value: 'Niue', alternative: 'NU', booster: 0.5, code: 'NU' },
  { value: 'Norfolk Island', alternative: 'NF', booster: 0.5, code: 'NF' },
  { value: 'North Korea', alternative: 'KP North Korea', code: 'KP' },
  { value: 'Northern Mariana Islands', alternative: 'MP', booster: 0.5, code: 'MP' },
  { value: 'Norway', alternative: 'NO Norge Noreg', booster: 1.5, code: 'NO' },
  { value: 'Oman', alternative: 'OM عمان', code: 'OM' },
  { value: 'Pakistan', alternative: 'PK پاکستان', booster: 2, code: 'PK' },
  { value: 'Palau', alternative: 'PW', booster: 0.5, code: 'PW' },
  { value: 'Palestinian Territory', alternative: 'PS فلسطين', code: 'PS' },
  { value: 'Panama', alternative: 'PA', code: 'PA' },
  { value: 'Papua New Guinea', alternative: 'PG', code: 'PG' },
  { value: 'Paraguay', alternative: 'PY', code: 'PY' },
  { value: 'Peru', alternative: 'PE', code: 'PE' },
  { value: 'Philippines', alternative: 'PH Pilipinas', booster: 1.5, code: 'PH' },
  { value: 'Pitcairn', alternative: 'PN', booster: 0.5, code: 'PN' },
  { value: 'Poland', alternative: 'PL Polska', booster: 1.25, code: 'PL' },
  { value: 'Portugal', alternative: 'PT Portuguesa', booster: 1.5, code: 'PT' },
  { value: 'Puerto Rico', alternative: 'PR', code: 'PR' },
  { value: 'Qatar', alternative: 'QA قطر', code: 'QA' },
  { value: 'Republic of the Congo', alternative: 'CG', code: 'CG' },
  { value: 'Reunion', alternative: 'RE Reunion', code: 'RE' },
  { value: 'Romania', alternative: 'RO Rumania Roumania România', code: 'RO' },
  { value: 'Russia', alternative: 'RU Rossiya Российская Россия', booster: 2.5, code: 'RU' },
  { value: 'Rwanda', alternative: 'RW', code: 'RW' },
  { value: 'Saint Barthelemy', alternative: 'BL St. Barthelemy', code: 'BL' },
  { value: 'Saint Helena', alternative: 'SH St.', code: 'SH' },
  { value: 'Saint Kitts and Nevis', alternative: 'KN St.', code: 'KN' },
  { value: 'Saint Lucia', alternative: 'LC St.', code: 'LC' },
  { value: 'Saint Martin', alternative: 'MF St.', code: 'MF' },
  { value: 'Saint Pierre and Miquelon', alternative: 'PM St.', code: 'PM' },
  { value: 'Saint Vincent and the Grenadines', alternative: 'VC St.', code: 'VC' },
  { value: 'Samoa', alternative: 'WS', code: 'WS' },
  { value: 'San Marino', alternative: 'SM RSM Repubblica', code: 'SM' },
  { value: 'Sao Tome and Principe', alternative: 'ST', code: 'ST' },
  { value: 'Saudi Arabia', alternative: 'SA السعودية', code: 'SA' },
  { value: 'Senegal', alternative: 'SN Sénégal', code: 'SN' },
  { value: 'Serbia', alternative: 'RS Србија Srbija', code: 'RS' },
  { value: 'Seychelles', alternative: 'SC', booster: 0.5, code: 'SC' },
  { value: 'Sierra Leone', alternative: 'SL', code: 'SL' },
  { value: 'Singapore', alternative: 'SG Singapura  சிங்கப்பூர் குடியரசு 新加坡共和国', code: 'SG' },
  { value: 'Sint Maarten', alternative: 'SX', code: 'SX' },
  { value: 'Slovakia', alternative: 'SK Slovenská Slovensko', code: 'SK' },
  { value: 'Slovenia', alternative: 'SI Slovenija', code: 'SI' },
  { value: 'Solomon Islands', alternative: 'SB', code: 'SB' },
  { value: 'Somalia', alternative: 'SO الصومال', code: 'SO' },
  { value: 'South Africa', alternative: 'ZA RSA Suid-Afrika', code: 'ZA' },
  { value: 'South Georgia and the South Sandwich Islands', alternative: 'GS', code: 'GS' },
  { value: 'South Korea', alternative: 'KR South Korea', booster: 1.5, code: 'KR' },
  { value: 'South Sudan', alternative: 'SS', code: 'SS' },
  { value: 'Spain', alternative: 'ES España', booster: 2, code: 'ES' },
  { value: 'Sri Lanka', alternative: 'LK ශ්‍රී ලංකා இலங்கை Ceylon', code: 'LK' },
  { value: 'Sudan', alternative: 'SD السودان', code: 'SD' },
  { value: 'Suriname', alternative: 'SR शर्नम् Sarnam Sranangron', code: 'SR' },
  { value: 'Svalbard and Jan Mayen', alternative: 'SJ', booster: 0.5, code: 'SJ' },
  { value: 'Swaziland', alternative: 'SZ weSwatini Swatini Ngwane', code: 'SZ' },
  { value: 'Sweden', alternative: 'SE Sverige', booster: 1.5, code: 'SE' },
  {
    value: 'Switzerland',
    alternative: 'CH Swiss Confederation Schweiz Suisse Svizzera Svizra',
    booster: 1.5,
    code: 'CH',
  },
  { value: 'Syria', alternative: 'SY Syria سورية', code: 'SY' },
  { value: 'Taiwan', alternative: 'TW 台灣 臺灣', code: 'TW' },
  { value: 'Tajikistan', alternative: 'TJ Тоҷикистон Toçikiston', code: 'TJ' },
  { value: 'Tanzania', alternative: 'TZ', code: 'TZ' },
  { value: 'Thailand', alternative: 'TH ประเทศไทย Prathet Thai', code: 'TH' },
  { value: 'Togo', alternative: 'TG Togolese', code: 'TG' },
  { value: 'Tokelau', alternative: 'TK', booster: 0.5, code: 'TK' },
  { value: 'Tonga', alternative: 'TO', code: 'TO' },
  { value: 'Trinidad and Tobago', alternative: 'TT', code: 'TT' },
  { value: 'Tunisia', alternative: 'TN تونس', code: 'TN' },
  { value: 'Turkey', alternative: 'TR Türkiye Turkiye', code: 'TR' },
  { value: 'Turkmenistan', alternative: 'TM Türkmenistan', code: 'TM' },
  { value: 'Turks and Caicos Islands', alternative: 'TC', booster: 0.5, code: 'TC' },
  { value: 'Tuvalu', alternative: 'TV', booster: 0.5, code: 'TV' },
  { value: 'Uganda', alternative: 'UG', code: 'UG' },
  { value: 'Ukraine', alternative: 'UA Ukrayina Україна', code: 'UA' },
  {
    value: 'United Kingdom',
    alternative: 'GB Great Britain England UK Wales Scotland Northern Ireland',
    booster: 2.5,
    code: 'GB',
  },
  { value: 'United States Minor Outlying Islands', alternative: 'UM', code: 'UM' },
  { value: 'United Arab Emirates', alternative: 'AE UAE الإمارات', code: 'AE' },
  { value: 'Uruguay', alternative: 'UY', code: 'UY' },
  { value: 'Uzbekistan', alternative: "UZ Ўзбекистон O'zbekstan O‘zbekiston", code: 'UZ' },
  { value: 'U.S. Virgin Islands', alternative: 'VI', booster: 0.5, code: 'VI' },
  { value: 'Vanuatu', alternative: 'VU', code: 'VU' },
  { value: 'Vatican', alternative: 'VA', booster: 0.5, code: 'VA' },
  { value: 'Venezuela', alternative: 'VE', code: 'VE' },
  { value: 'Vietnam', alternative: 'VN Việt Nam', booster: 1.5, code: 'VN' },
  { value: 'Wallis and Futuna', alternative: 'WF', booster: 0.5, code: 'WF' },
  { value: 'Western Sahara', alternative: 'EH لصحراء الغربية', code: 'EH' },
  { value: 'Yemen', alternative: 'YE اليمن', code: 'YE' },
  { value: 'Zambia', alternative: 'ZM', code: 'ZM' },
  { value: 'Zimbabwe', alternative: 'ZW', code: 'ZW' },
].map((country) => {
  if ('menuItemProps' in country) return country;

  const searchValue = utils.stripAccents(country.value ?? '').toLowerCase();
  const searchAlternative = utils.stripAccents(country.alternative ?? '').toLowerCase();

  return {
    ...country,
    alternative: country.alternative ?? '',
    label: country.value,
    searchValue,
    searchAlternative,
    booster: country.booster ?? 0.1,
  };
});

export const CONTRIES_MAPPER = COUNTRIES.reduce<Record<string, Country>>((acc, country) => {
  if ((country as Country).alternative) {
    const countryData = country as Country;
    acc[countryData.value] = countryData;
  }
  return acc;
}, {});

export default COUNTRIES;
