import { BaseVersion } from '@voiceflow/base-types';

export interface Project {
  _id: string;
  project_id: number;
  name: string;
  dev_version: number;
  created: string;
  creator_id: number;
  team_id: number;
  module_reference: string | null;
  skill_id: number;
  diagram: string;
  amzn_id: string | null;
  summary: string;
  description: string;
  keywords: string[];
  invocations: { value: string[] };
  small_icon: string | null;
  large_icon: string | null;
  category: string | null;
  purchase: boolean;
  personal: boolean;
  copa: boolean;
  ads: boolean;
  export: boolean;
  instructions: string;
  inv_name: string;
  stage: number;
  review: boolean;
  live: boolean;
  locales: string[];
  restart: boolean;
  global: string[];
  privacy_policy: string;
  terms_and_cond: string;
  intents: string[];
  slots: string[];
  used_intents: string[];
  used_choices: string[];
  preview: boolean;
  resumePrompt: {
    voice: string;
    content: string;
    follow_content?: string;
    follow_voice?: string;
  };
  errorPrompt: {
    voice: string;
    content: string;
  };
  fulfillment: any;
  accountLinking: any;
  access_token_variable: null;
  alexa_permissions: string[] | null;
  alexa_interfaces: null;
  alexa_events: string | null;
  repeat: number;
  last_save: string;
  google_publish_info: unknown;
  platform: string;
  dialogflow_token: string | null;
  cert_requested: string | null;
  cert_approved: string | null;
  google_versions: any;
  settings: any;
  image: string;
  seats: number;
  projects: number;
  website: null;
  status: number;
  stripe_id: string | null;
  stripe_sub_id: string | null;
  stripe_status: string | null;
  expiry: string | null;
  boards: { board_id: string; name: string; projects: string[] }[];
  plan: string;
  period: null;
  beta_flag: number;
  board_name: string;
  board_created: string;
  skill_created: string;
  skill_name: string;
  role: string;
  version?: BaseVersion.Version;
}
