version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  node-executor:
    working_directory: ~/voiceflow # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:12 # ...with this image as the primary container; this is where all `steps` will run
    environment:
      NODE_OPTIONS: --max-old-space-size=4096
    resource_class: medium+
  image_builder:
    working_directory: /tmp/vf-build
    docker:
      - image: voiceflow/ci-image:v3

commands:
  install_dependencies:
    description: Restore/update node_modules in cache
    steps:
      - restore_cache: # special step to restore the dependency cache
          key: creator-app-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile
      - save_cache: # Update dependency cache
          key: creator-app-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: git tag --merged production
      - run: npx semantic-release@15
  build-app:
    executor: node-executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build app
          command: |
            if [ "$CIRCLE_BRANCH" == "production" ]; then
              export VF_APP_API_HOST=api.voiceflow.com
              export VF_APP_BUILD_ENV=production
              export VF_APP_MAINTENANCE_STATUS_SOURCE=https://s3.amazonaws.com/com.voiceflow.maintenance/maintenance.json
            else
              export VF_APP_BUILD_ENV=staging
              export VF_APP_API_HOST=api-$CIRCLE_BRANCH.development.voiceflow.com
              export VF_APP_MAINTENANCE_STATUS_SOURCE=https://s3.amazonaws.com/com.voiceflow.dev.maintenance/maintenance.json
            fi
            yarn build
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - build
            - app.dockerfile
            - config
  build-storybook:
    executor: node-executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: (Build App)
          command: yarn storybook:build
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - storybook_build
            - storybook.dockerfile
  build-admin:
    executor: node-executor
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build admin static artifacts
          command: |
            if [ "$CIRCLE_BRANCH" == "admin" ]; then
              export VF_APP_API_HOST=api-master.development.voiceflow.com
              export VF_APP_BUILD_ENV=staging
            elif [ "$CIRCLE_BRANCH" == "admin-prod" ]; then
              export VF_APP_API_HOST=api.voiceflow.com
              export VF_APP_BUILD_ENV=production
            fi
            yarn build:admin
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - admin_build
            - admin.dockerfile
            - config
  test-integration: # Run integration tests in parallel
    executor: node-executor
    steps: # a collection of executable commands
      - checkout
      - install_dependencies
      - run:
          name: (Integration Tests)
          command: yarn test:integration --coverage --detectOpenHandles
      - codecov/upload:
          file: jest_coverage/lcov.info
          flags: integration
  test: # Main unit, style, and dependency tests
    executor: node-executor
    steps: # a collection of executable commands
      - checkout
      - install_dependencies
      - run:
          name: (Unit Tests)
          command: yarn test:unit
      - codecov/upload:
          file: nyc_coverage/lcov.info
          flags: unit
      - run:
          name: (Code Style)
          command: yarn lint:quiet
      - run:
          name: (Dependency Tests)
          command: yarn test:dependencies # Run dependency test here

  build-deploy-app-image:
    executor: image_builder
    environment:
      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            docker build \
              -f app.dockerfile \
              -t $IMAGE_NAME .
      - run:
          name: "Push docker images"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker push $IMAGE_NAME
            docker tag $IMAGE_NAME $IMAGE_REPO:latest-$CIRCLE_BRANCH
            docker push $IMAGE_REPO:latest-$CIRCLE_BRANCH
      - run:
          name: Deploy image
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "staging" ]; then
              aws eks --region us-east-1 update-kubeconfig --name development
            fi
            if [ "$CIRCLE_BRANCH" == "production" ]; then
              aws eks --region us-east-1 update-kubeconfig --name production
            fi
            kubectl set image --namespace voiceflow-v1 statefulset/creator-app-$CIRCLE_BRANCH app=$IMAGE_NAME

  build-deploy-storybook-image:
    executor: image_builder
    environment:
      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - setup_remote_docker
      - run:
          name: "Build storybook docker image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            docker build \
              -f storybook.dockerfile \
              -t $IMAGE_NAME .
      - run:
          name: "Push storybook docker images"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker push $IMAGE_NAME
            docker tag $IMAGE_NAME $IMAGE_REPO:latest-$CIRCLE_BRANCH
            docker push $IMAGE_REPO:latest-$CIRCLE_BRANCH
      - run:
          name: Update image
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "staging" ]; then
              aws eks --region us-east-1 update-kubeconfig --name development
            fi
            if [ "$CIRCLE_BRANCH" == "production" ]; then
              aws eks --region us-east-1 update-kubeconfig --name production
            fi
            kubectl set image --namespace voiceflow-v1 deployment/storybook-$CIRCLE_BRANCH storybook=168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-$CIRCLE_SHA1

  build-deploy-admin-image:
    executor: image_builder
    environment:
      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-admin"
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - setup_remote_docker
      - run:
          name: "Build admin docker image"
          command: |
            if [ "$CIRCLE_BRANCH" == "admin" ]; then
              export DEPLOY_SUFFIX=development
            elif [ "$CIRCLE_BRANCH" == "admin-prod" ]; then
              export DEPLOY_SUFFIX=production
            fi
            echo $DEPLOY_SUFFIX > /tmp/deploy_suffix
            docker build \
              -f admin.dockerfile \
              -t $IMAGE_REPO:k8s-$DEPLOY_SUFFIX-$CIRCLE_SHA1 .
      - run:
          name: "Push admin docker images"
          command: |
            DEPLOY_SUFFIX=$(cat /tmp/deploy_suffix)
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker push $IMAGE_REPO:k8s-$DEPLOY_SUFFIX-$CIRCLE_SHA1
            docker tag $IMAGE_REPO:k8s-$DEPLOY_SUFFIX-$CIRCLE_SHA1 $IMAGE_REPO:latest-$DEPLOY_SUFFIX
            docker push $IMAGE_REPO:latest-$DEPLOY_SUFFIX
      - run:
          name: "Deploy admin docker image"
          command: |
            DEPLOY_SUFFIX=$(cat /tmp/deploy_suffix)
            if [ "$CIRCLE_BRANCH" == "admin" ]; then
              aws eks --region us-east-1 update-kubeconfig --name development
            elif [ "$CIRCLE_BRANCH" == "admin-prod" ]; then
              aws eks --region us-east-1 update-kubeconfig --name production
            fi
            kubectl set image --namespace voiceflow-v1 deployment/admin-ui-$DEPLOY_SUFFIX app=$IMAGE_REPO:k8s-$DEPLOY_SUFFIX-$CIRCLE_SHA1

  build-app-dev-environment:
    executor: node-executor
    environment:
      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
    steps:
      - checkout
      - run:
          name: If container with this git SHA already exists, don't build
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            $(aws ecr get-login --no-include-email --region us-east-1)
            set +e
            DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE_NAME > /dev/null 2>&1
            SEARCH_IMAGE_RESULT=$?
            set -e
            if [[ $SEARCH_IMAGE_RESULT -eq 0 ]]; then  
              circleci-agent step halt  # Image exists, skip following steps
            fi
      - install_dependencies
      - run:
          name: Build app, if docker container does not exist
          command: |
            ENV_NAME="${CIRCLE_BRANCH%%_*}"
            export VF_APP_BUILD_ENV=staging
            export VF_APP_API_HOST=api-$ENV_NAME.development.voiceflow.com
            export VF_APP_MAINTENANCE_STATUS_SOURCE=https://s3.amazonaws.com/com.voiceflow.dev.maintenance/maintenance.json
            yarn build
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - build
            - app.dockerfile
            - config

  deploy-app-dev-environment:
    executor: image_builder
    environment:
      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
    steps:
      - checkout # special step to check out source code to working directory
      - add_ssh_keys: # To enable write access to repository for removing dev environment branches
          fingerprints:
            - "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
      - attach_workspace:
          at: /tmp/vf-build
      - setup_remote_docker
      - run:
          name: "Build and push dev environment image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            $(aws ecr get-login --no-include-email --region us-east-1)
            set +e
            DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE_NAME > /dev/null 2>&1
            SEARCH_IMAGE_RESULT=$?
            set -e
            if [[ $SEARCH_IMAGE_RESULT -ne 0 ]]; then   # Only build the image if there are no existing images 
              docker build \
                -f app.dockerfile \
                -t $IMAGE_NAME .
              $(aws ecr get-login --no-include-email --region us-east-1)
              docker push $IMAGE_NAME
            fi
            git push origin --delete $CIRCLE_BRANCH --no-verify # Clean up branch
      - run:
          name: Install latest envcli utility
          command: |
            API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/envcli"
            ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[2].id')
            curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output envcli.tar.gz
            tar -xf envcli.tar.gz
      - run:
          name: "Deploy dev environment image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            ENV_NAME="${CIRCLE_BRANCH%%_*}"
            aws eks --region us-east-1 update-kubeconfig --name development
            NON_INTERACTIVE=true ./envcli edit component creatorapp creatorapp -n $ENV_NAME -i $IMAGE_NAME
      - run:
          name: "Notify Slack (if applicable)"
          command: |
            set +e
            aws s3 cp s3://com.voiceflow.ci.states/github-actions/dev-env/creator-app-notify-$CIRCLE_SHA1.json state.json
            CHANNEL=$(cat state.json | jq -r '.channel')
            set -e
            if [[ $CHANNEL != "" ]]; then
              echo "Notifying slack..."
              MESSAGE=$(cat state.json | jq -r '.message')
              curl -O https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
              chmod +x ./slack
              ./slack chat send "$MESSAGE" "#${CHANNEL}"
              aws s3 rm s3://com.voiceflow.ci.states/github-actions/dev-env/creator-app-notify-$CIRCLE_SHA1.json 
            fi

workflows:
  dev-environment:
    jobs:
      - build-app-dev-environment:
          context: dev-test
          filters:
            branches:
              only:
                - /env-.*/
      - deploy-app-dev-environment:
          context: dev-test
          requires:
            - build-app-dev-environment
          filters:
            branches:
              only:
                - /env-.*/

  admin:
    jobs:
      - build-admin:
          context: dev-test
          filters:
            branches:
              only:
                - admin
                - admin-prod
      - build-deploy-admin-image:
          context: dev-test
          requires:
            - build-admin
          filters:
            branches:
              only:
                - admin
                - admin-prod

  storybook:
    jobs:
      - build-storybook:
          context: dev-test
          filters:
            branches:
              ignore:
                - /env-.*/
                - production
      - build-deploy-storybook-image:
          context: dev-test
          requires:
            - build-storybook
          filters:
            branches:
              only:
                - master
                - staging

  app:
    jobs:
      - test-integration:
          context: dev-test
          filters:
            branches:
              ignore:
                - /env-.*/
                - staging
      - test:
          context: dev-test
          filters:
            branches:
              ignore:
                - /env-.*/
                - staging
      - build-app:
          context: dev-test
          filters:
            branches:
              ignore:
                - /env-.*/
                - staging
      - build-deploy-app-image:
          context: dev-test
          requires:
            - test
            - test-integration
            - build-app
          filters:
            branches:
              only:
                - master
                - production
      - release:
          context: dev-test
          requires:
            - test
            - test-integration
            - build-app
          filters:
            branches:
              only: production

  app-staging:
    jobs:
      - build-app:
          context: dev-test
          filters:
            branches:
              only:
                - staging
      - build-deploy-app-image:
          context: dev-test
          requires:
            - build-app
          filters:
            branches:
              only:
                - staging
