version: 2.1

executors:
  node_11:
    working_directory: ~/voiceflow # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:11 # ...with this image as the primary container; this is where all `steps` will run
    environment:
      NODE_OPTIONS: --max-old-space-size=2048

commands:
  run_tests:
    description: Run tests against codebase
    parameters:
      tests:
        type: steps
        default: []
      saveCache:
        type: boolean
        default: false
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache: # special step to restore the dependency cache
          key: react-cache-{{ checksum "package.json" }}
      - run:
          name: yarn install packages
          command: yarn
      - when:
          condition: << parameters.saveCache >>
          steps:
            - save_cache: # special step to save the dependency cache
                key: react-cache-{{ checksum "package.json" }}
                paths:
                  - ./node_modules
      - steps: << parameters.tests >>

jobs:
  release:
    docker:
      - image: node:11
    steps:
      - checkout
      - run: git tag --merged production
      - run: npm i -g semantic-release@15
      - run: semantic-release
  test: # runs not using Workflows must have a `build` job as entry point
    executor: node_11
    steps: # a collection of executable commands
      - run_tests:
          saveCache: true
          tests:
            - run:
                name: (React Tests)
                command: npm run test -- --detectOpenHandles --runInBand
            - run:
                name: (Code Style)
                command: npm run lint:quiet
            - run:
                name: (Dependency Tests)
                command: npm run test:dependencies
  build:
    executor: node_11
    steps:
      - run_tests:
          tests:
            - run:
                name: (Build App)
                command: npm run build
            - run:
                name: (Build Storybook)
                command: npm run storybook:build
  deploy-production:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Update Elastic Beanstalk Dockerrunfile.aws.json'
          command: 'sed -i".json" "s/VERSION/$CIRCLE_BUILD_NUM/g" Dockerrun.aws.json'
      - run:
          name: 'Build docker image'
          command: docker build --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --build-arg build_VF_APP_API_HOST=api.voiceflow.com --build-arg build_VF_APP_BUILD_ENV=production --squash -t voiceflow/creator-app:$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push docker image'
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push voiceflow/creator-app:$CIRCLE_BUILD_NUM
      - run:
          name: 'Update PIP && Install AWS EB'
          command: |
            rm Dockerfile
            git config user.email "build@voiceflow.com"
            git config user.name "build"
            git add -u
            git commit -m "$CIRCLE_BUILD_NUM BUILD"
            pip install awsebcli
            eb init --region us-east-1 --platform docker creator-app
            eb use CreatorApp-production
      - run:
          name: Push to Elastic Beanstalk
          command: eb deploy CreatorApp-production --staged -l $CIRCLE_BUILD_NUM --nohang
  deploy-creator-master:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Build creator-app docker image'
          command: docker build --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --build-arg build_VF_APP_API_HOST=api.master.voiceflow.com --build-arg build_VF_APP_BUILD_ENV=staging --squash -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-master-$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push creator-app docker images'
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-master-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-master
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-master-$CIRCLE_BUILD_NUM
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-master
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo cp ./aws-iam-authenticator /usr/bin
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install -y python3-pip python3-dev
            sudo pip3 install awscli
      - run:
          name: Get credentials
          command: |
            aws eks --region us-east-1 update-kubeconfig --name development
      - run:
          name: Update creator-app image
          command: |
            kubectl set image --namespace voiceflow-v1 deployment/creator-app-master app=168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-master-$CIRCLE_BUILD_NUM
  deploy-storybook-master:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Build storybook docker image'
          command: docker build -f Dockerfile-storybook --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --squash -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-master-$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push storybook docker images'
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-master-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:latest-master
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-master-$CIRCLE_BUILD_NUM
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:latest-master
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo cp ./aws-iam-authenticator /usr/bin
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install -y python3-pip python3-dev
            sudo pip3 install awscli
      - run:
          name: Get credentials
          command: |
            aws eks --region us-east-1 update-kubeconfig --name development
      - run:
          name: Update storybook image
          command: |
            kubectl set image --namespace voiceflow-v1 deployment/storybook-master storybook=168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-master-$CIRCLE_BUILD_NUM
  deploy-creator-staging:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Build docker image'
          command: docker build --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --build-arg build_VF_APP_API_HOST=api.staging.voiceflow.com --build-arg build_VF_APP_BUILD_ENV=staging --squash -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-staging-$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push docker images'
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-staging-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-staging
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-staging-$CIRCLE_BUILD_NUM
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-staging
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo cp ./aws-iam-authenticator /usr/bin
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install -y python3-pip python3-dev
            sudo pip3 install awscli
      - run:
          name: Get credentials
          command: |
            aws eks --region us-east-1 update-kubeconfig --name development
      - run:
          name: Update image
          command: |
            kubectl set image --namespace voiceflow-v1 deployment/creator-app-staging app=168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-staging-$CIRCLE_BUILD_NUM
  deploy-storybook-staging:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Build docker image'
          command: docker build --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --squash -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-staging-$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push docker images'
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-staging-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:latest-staging
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-staging-$CIRCLE_BUILD_NUM
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:latest-staging
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo cp ./aws-iam-authenticator /usr/bin
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install -y python3-pip python3-dev
            sudo pip3 install awscli
      - run:
          name: Get credentials
          command: |
            aws eks --region us-east-1 update-kubeconfig --name development
      - run:
          name: Update image
          command: |
            kubectl set image --namespace voiceflow-v1 deployment/storybook-staging app=168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook:k8s-staging-$CIRCLE_BUILD_NUM
  deploy-k8s-production:
    machine: true
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Add token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: # Need this for --squash to work
          name: set docker daemon to experimental
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: 'Build docker image'
          command: docker build --build-arg build_NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} --build-arg build_VF_APP_API_HOST=api.k8s.voiceflow.com --build-arg build_VF_APP_BUILD_ENV=production --squash -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-production-$CIRCLE_BUILD_NUM .
      - run:
          name: 'Push docker images'
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-production-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-production
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-production-$CIRCLE_BUILD_NUM
            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:latest-production
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo cp ./aws-iam-authenticator /usr/bin
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install -y python3-pip python3-dev
            sudo pip3 install awscli
      - run:
          name: Get credentials
          command: |
            aws eks --region us-east-1 update-kubeconfig --name production
      - run:
          name: Update image
          command: |
            kubectl set image --namespace voiceflow-v1 deployment/creator-app-production app=168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app:k8s-production-$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore:
                - production
                - master
                - staging
      - deploy-production:
          requires:
            - test
          filters:
            branches:
              only: production
      - deploy-creator-master:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-storybook-master:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-creator-staging:
          requires:
            - test
          filters:
            branches:
              only: staging
      - deploy-storybook-staging:
          requires:
            - test
          filters:
            branches:
              only: staging
      - deploy-k8s-production:
          requires:
            - test
          filters:
            branches:
              only: production
      - release:
          requires:
            - test
            - deploy-production
          filters:
            branches:
              only: production
