version: 2.1

orbs:
  vfcommon: voiceflow/common@0.0.91
  sonarcloud: sonarsource/sonarcloud@1.0.2
  jira: circleci/jira@1.3.1

# Reusable YAML chunks
defaults:
  prod_deploy_filters: &prod_deploy_filters
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]*(\.[0-9]*)*$/

  ignore_dev_env_autorebase_filters: &ignore_dev_env_autorebase_filters
    branches:
      ignore:
        - /rebase-pull-request-.*/
        - /cherry-pick-rebase-pull-request-.*/
        - /env-.*/

  ignore_dev_env_autorebase_staging_filters:
    &ignore_dev_env_autorebase_staging_filters
    branches:
      ignore:
        - /rebase-pull-request-.*/
        - /cherry-pick-rebase-pull-request-.*/
        - /env-.*/
        - staging

  slack-fail-post-step: &slack-fail-post-step
    post-steps:
      - vfcommon/notify_slack:
          channel: dev_general
          event: fail
          mentions: "@eng_creator"
          template: basic_fail_1
          branch_pattern: master

jobs:
  build-app:
    parameters:
      check_image:
        description: Checks if the Docker image exists
        type: boolean
        default: false
      strict:
        description: Run typechecking and other build-time analyses
        type: boolean
        default: false
    executor: vfcommon/node-executor
    steps:
      - checkout
      - when:
          condition: << parameters.check_image >>
          steps:
            - vfcommon/install_aws_cli
            - vfcommon/check_image_exists:
                image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
      - vfcommon/install_node_modules:
          avoid_post_install_scripts: false
      - run:
          name: Build app, if docker container does not exist
          command: |
            if [[ -z "$CIRCLE_BRANCH" && ! -z "$CIRCLE_TAG" ]]; then
              echo "Building production image!"
              export VF_APP_API_HOST=api.voiceflow.com
              export VF_APP_BUILD_ENV=production
              export VF_APP_MAINTENANCE_STATUS_SOURCE=https://s3.amazonaws.com/com.voiceflow.maintenance/maintenance.json
            else
              echo "Building development image!"
              export VF_APP_BUILD_ENV=staging
              export VF_APP_API_HOST=api-$CIRCLE_BRANCH.development.voiceflow.com
              export VF_APP_MAINTENANCE_STATUS_SOURCE=https://s3.amazonaws.com/com.voiceflow.dev.maintenance/maintenance.json
            fi
            yarn build <<# parameters.strict >> --validate <</ parameters.strict >>
            <<# parameters.strict >> yarn types <</ parameters.strict >>
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - build
            - app.dockerfile
            - config

  build-storybook:
    executor: vfcommon/node-executor
    steps:
      - checkout
      - vfcommon/install_node_modules:
          avoid_post_install_scripts: false
      - vfcommon/install_node_modules:
          avoid_post_install_scripts: false
          working_directory: ~/voiceflow/packages/storybook
          yarn_lock_restore_cache_directory: ~/voiceflow/packages/storybook
      - run:
          name: Build storybook
          command: yarn storybook:build
          working_directory: ~/voiceflow/packages/storybook
      - persist_to_workspace:
          root: ~/voiceflow/packages/storybook
          paths:
            - build
            - dockerfile

  build-admin:
    executor: vfcommon/node-executor
    steps:
      - checkout
      - vfcommon/install_node_modules:
          avoid_post_install_scripts: false
      - run:
          name: Build admin static artifacts
          command: |
            export VF_APP_API_HOST=api-master.development.voiceflow.com
            export VF_APP_BUILD_ENV=production
            yarn build:admin
      - persist_to_workspace:
          root: ~/voiceflow
          paths:
            - admin_build
            - admin.dockerfile
            - config

  test-integration: # Run integration tests in parallel
    executor: vfcommon/node-executor
    steps: # a collection of executable commands
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/integration_tests:
          step_name: Integration Tests
          extra_args: --coverage --detectOpenHandles

  test: # Main unit, style, and dependency tests
    executor: vfcommon/node-executor
    steps: # a collection of executable commands
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/unit_tests:
          step_name: Unit Tests
      - run:
          name: Lint Styles
          command: yarn lint:css --quiet
      - vfcommon/lint_report
      - vfcommon/lint_dockerfile
      - vfcommon/dependency_tests:
          step_name: Dependency Tests
      - sonarcloud/scan

  build-deploy-app-image:
    parameters:
      tagged:
        description: Running on a git tag?
        type: boolean
        default: false
      sentry:
        description: Report deploy to sentry?
        type: boolean
        default: false
    executor: vfcommon/build-executor
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - vfcommon/build_push_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
          dockerfile: app.dockerfile
          checkout: false
      - vfcommon/deploy_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
          namespace: "voiceflow-v1"
          target: "statefulset/creator-app"
          tagged: << parameters.tagged >>
          sentry: << parameters.sentry >>
      - run:
          name: Wait for deployment rollout
          command: |
            sleep 120

  build-deploy-storybook-dev-environment:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/build_deploy_dev_env:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
          component: "storybook"
          ssh_key: "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
          dockerfile: dockerfile
          clean_dev_env_branch: false

  build-deploy-storybook-image:
    executor: vfcommon/build-executor
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - vfcommon/build_push_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
          dockerfile: dockerfile
          checkout: false
      - vfcommon/deploy_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/storybook"
          namespace: "voiceflow-v1"
          target: "deployment/storybook"
          container_name: storybook
          tagged: false

  build-deploy-admin-dev-environment:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/build_deploy_dev_env:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-admin"
          component: "adminui"
          ssh_key: "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
          dockerfile: admin.dockerfile
          clean_dev_env_branch: false

  build-deploy-admin-image:
    executor: vfcommon/build-executor
    steps:
      - attach_workspace:
          at: /tmp/vf-build
      - vfcommon/build_push_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-admin"
          dockerfile: admin.dockerfile
          checkout: false
      - vfcommon/deploy_image:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-admin"
          namespace: "voiceflow-v1"
          target: "deployment/admin-ui"
          tagged: false

  deploy-app-dev-environment:
    executor: vfcommon/build-executor
    steps:
      - vfcommon/build_deploy_dev_env:
          image_repo: "168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app"
          component: "creatorapp"
          ssh_key: "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"
          dockerfile: app.dockerfile
          clean_dev_env_branch: false
      - run:
          name: "Notify Slack (if applicable)"
          command: |
            set +e
            aws s3 cp s3://com.voiceflow.ci.states/github-actions/dev-env/creator-app-notify-$CIRCLE_SHA1.json state.json
            CHANNEL=$(cat state.json | jq -r '.channel')
            set -e
            if [[ $CHANNEL != "" ]]; then
              echo "Notifying slack..."
              MESSAGE=$(cat state.json | jq -r '.message')
              curl -O https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
              chmod +x ./slack
              ./slack chat send "$MESSAGE" "#${CHANNEL}"
              aws s3 rm s3://com.voiceflow.ci.states/github-actions/dev-env/creator-app-notify-$CIRCLE_SHA1.json
            fi

  delete-branch:
    executor: vfcommon/build-executor
    steps:
      - checkout
      - vfcommon/delete_branch:
          branch_name: $CIRCLE_BRANCH
          ssh_key: "93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a"

workflows:
  dev-environment:
    jobs:
      - build-app:
          check_image: true
          context: dev-test
          filters:
            branches:
              only:
                - /env-.*/
      - deploy-app-dev-environment:
          context: dev-test
          post-steps:
            - jira/notify:
                environment: ${CIRCLE_BRANCH%%_*}
                environment_type: testing
                job_type: deployment
          requires:
            - build-app
          filters:
            branches:
              only:
                - /env-.*/

      - build-storybook:
          context: dev-test
          filters:
            branches:
              only:
                - /env-.*/
      - build-deploy-storybook-dev-environment:
          context: dev-test
          requires:
            - build-storybook
          filters:
            branches:
              only:
                - /env-.*/

      - build-admin:
          context: dev-test
          filters:
            branches:
              only:
                - /env-.*/
      - build-deploy-admin-dev-environment:
          context: dev-test
          requires:
            - build-admin
          filters:
            branches:
              only:
                - /env-.*/

      - delete-branch:
          context: dev-test
          requires:
            - build-deploy-admin-dev-environment
            - build-deploy-storybook-dev-environment
            - deploy-app-dev-environment
          filters:
            branches:
              only:
                - /env-.*/
  admin:
    jobs:
      - build-admin:
          <<: *slack-fail-post-step
          context: dev-test
          filters:
            <<: *ignore_dev_env_autorebase_filters

      - build-deploy-admin-image:
          context: dev-test
          requires:
            - build-admin
          filters:
            branches:
              only:
                - master

  storybook:
    jobs:
      - build-storybook:
          <<: *slack-fail-post-step
          context: dev-test
          filters:
            <<: *ignore_dev_env_autorebase_filters

      - build-deploy-storybook-image:
          context: dev-test
          requires:
            - build-storybook
          filters:
            branches:
              only:
                - master
                - staging

  test-and-release-app:
    jobs:
      - test-integration:
          <<: *slack-fail-post-step
          context: dev-test
          filters:
            <<: *ignore_dev_env_autorebase_staging_filters

      - test:
          <<: *slack-fail-post-step
          context: dev-test
          filters:
            <<: *ignore_dev_env_autorebase_staging_filters

      - vfcommon/test_e2e:
          context: dev-test
          github_username: GITHUB_USERNAME
          github_token: GITHUB_TOKEN
          creator_app_commit: CIRCLE_SHA1
          <<: *slack-fail-post-step
          filters:
            <<: *ignore_dev_env_autorebase_staging_filters

      - build-app:
          <<: *slack-fail-post-step
          context: dev-test
          strict: true
          post-steps:
            - jira/notify
          filters:
            <<: *ignore_dev_env_autorebase_staging_filters

      - vfcommon/release:
          <<: *slack-fail-post-step
          sentry_project: creator-app
          context: dev-test
          requires:
            - test
            - test-integration
            - vfcommon/test_e2e
            - build-app
          filters:
            branches:
              only: master

  deploy-app:
    jobs:
      - build-app:
          <<: *prod_deploy_filters
          context: dev-test
          post-steps:
            - jira/notify
      - build-deploy-app-image:
          <<: *prod_deploy_filters
          tagged: true
          sentry: true
          context: dev-test
          post-steps:
            - jira/notify:
                environment: public
                environment_type: production
                job_type: deployment
          requires:
            - build-app

  app-staging:
    jobs:
      - build-app:
          context: dev-test
          filters:
            branches:
              only:
                - staging
      - build-deploy-app-image:
          context: dev-test
          post-steps:
            - jira/notify:
                environment: staging
                environment_type: staging
                job_type: deployment
          requires:
            - build-app
          filters:
            branches:
              only:
                - staging
