version: 2.1

parameters:
  container-image-url-creator-app:
    type: string
    default: '168387678261.dkr.ecr.us-east-1.amazonaws.com/creator-app'
  container-image-url-showcase:
    type: string
    default: '168387678261.dkr.ecr.us-east-1.amazonaws.com/showcase'
  container-image-url-realtime:
    type: string
    default: '168387678261.dkr.ecr.us-east-1.amazonaws.com/realtime'
  container-image-url-ml-gateway:
    type: string
    default: '168387678261.dkr.ecr.us-east-1.amazonaws.com/ml-gateway'
  k8s-asset-creator-app:
    type: string
    default: 'deployment/creator-app'
  k8s-asset-showcase:
    type: string
    default: 'deployment/showcase'
  k8s-asset-realtime:
    type: string
    default: 'deployment/realtime'
  k8s-asset-ml-gateway:
    type: string
    default: 'deployment/ml-gateway'
  k8s-namespace:
    type: string
    default: 'voiceflow' # This is usually voiceflow
  ssh-fingerprint:
    type: string
    default: '93:f8:51:53:5e:bd:75:0e:29:24:4d:6a:3f:ef:e1:4a'
  track-component-creator-app:
    type: string
    default: 'creator-app'
  track-component-showcase:
    type: string
    default: 'showcase'
  track-component-realtime:
    type: string
    default: 'realtime'
  track-component-ml-gateway:
    type: string
    default: 'ml-gateway'
  build-creator-app:
    type: boolean
    default: false
  build-showcase:
    type: boolean
    default: false
  build-realtime:
    type: boolean
    default: false
  build-ml-gateway:
    type: boolean
    default: false
  build-all:
    type: boolean
    default: false
  build-any:
    type: boolean
    default: false
  build-frontend:
    type: boolean
    default: false
  build-backend:
    type: boolean
    default: false

orbs:
  vfcommon: voiceflow/common@dev:8c38ab14e82828f3115dba671916565661a3eb16

  sonarcloud: sonarsource/sonarcloud@1.0.2
  jira: circleci/jira@1.3.1

# Reusable YAML chunks
defaults:
  trying_staging_filters: &trying_staging_filters
    branches:
      only:
        - staging
        - trying

  prod_deploy_filters: &prod_deploy_filters
    filters:
      branches:
        only:
          - production

  ignore_master_prod_break_glass_filters: &ignore_master_prod_break_glass_filters
    branches:
      ignore:
        - master
        - production
        - /^break-glass.*$/

  ignore_break_glass_deploy_filters: &ignore_break_glass_deploy_filters
    filters:
      branches:
        ignore:
          - /^break-glass.*$/

  slack-fail-post-step: &slack-fail-post-step
    post-steps:
      - vfcommon/notify_slack:
          channel: dev_general
          event: fail
          mentions: '@eng_cxd'
          template: basic_fail_1
          branch_pattern: master

jobs:
  test: # Main unit, style, and dependency tests
    executor: vfcommon/node-executor
    steps: # a collection of executable commands
      - checkout
      - attach_workspace:
          at: ~/voiceflow
      - vfcommon/install_node_modules
      - restore_cache:
          name: Restoring eslint Cache
          keys:
            - eslint-cache-{{ .Branch }}
            - eslint-cache-master
      - vfcommon/monorepo_unit_tests:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - vfcommon/monorepo_integration_tests:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - vfcommon/monorepo_lint_report:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - vfcommon/monorepo_analyze_dependencies:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - vfcommon/monorepo_lint_dockerfile:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - vfcommon/monorepo_dependency_tests:
          force_execution: << pipeline.parameters.build-all >>
          run_on_root: << pipeline.parameters.build-all >>
      - save_cache:
          name: Saving eslint Cache
          key: eslint-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - ~/voiceflow/apps/creator-app/.eslintcache
      - when:
          condition: << pipeline.parameters.build-any >>
          steps:
            - sonarcloud/scan:
                cache_version: 2

workflows:
  # Merge Queue jobs
  queue-jobs:
    jobs:
      - vfcommon/test_e2e:
          github_username: GITHUB_USERNAME
          github_token: GITHUB_TOKEN
          enable: << pipeline.parameters.build-any >>
          force_execute: << pipeline.parameters.build-all >>
          vf_monorepo_services: '@voiceflow/{realtime,ml-gateway}'
          vf_service_profile: platform
          context: dev-test
          filters:
            <<: *trying_staging_filters

  test-and-release:
    jobs:
      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          name: build-ui-test
          force_execute: true
          package: ui
          package_folder: libs
          container_folder_to_copy: libs/ui/build
          post-steps:
            - jira/notify

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          name: build-socket-utils-test
          force_execute: true
          package: socket-utils
          package_folder: libs
          container_folder_to_copy: libs/socket-utils/build
          post-steps:
            - jira/notify

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          name: build-ml-sdk-test
          force_execute: true
          package: ml-sdk
          package_folder: libs
          container_folder_to_copy: libs/ml-sdk/build
          post-steps:
            - jira/notify

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          name: build-platform-config-test
          force_execute: true
          package: platform-config
          package_folder: libs
          attach_workspace: true
          container_folder_to_copy: libs/platform-config/build
          post-steps:
            - jira/notify
          requires:
            - build-ui-test

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          name: build-realtime-sdk-test
          attach_workspace: true
          force_execute: true
          package: realtime-sdk
          package_folder: libs
          container_folder_to_copy: libs/realtime-sdk/build
          post-steps:
            - jira/notify
          requires:
            - build-platform-config-test

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          attach_workspace: true
          name: build-app-test
          force_execute: << pipeline.parameters.build-frontend >>
          package: creator-app
          package_folder: apps
          container_folder_to_copy: apps/creator-app/build
          post-steps:
            - jira/notify
          requires:
            - build-ml-sdk-test
            - build-platform-config-test
            - build-realtime-sdk-test
            - build-ui-test

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          attach_workspace: true
          name: build-showcase-test
          force_execute: << pipeline.parameters.build-frontend >>
          package: showcase
          package_folder: apps
          container_folder_to_copy: apps/showcase/build
          post-steps:
            - jira/notify
          requires:
            - build-ui-test

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          attach_workspace: true
          name: build-realtime-test
          force_execute: << pipeline.parameters.build-backend >>
          package: realtime
          package_folder: apps
          container_folder_to_copy: apps/realtime/build
          post-steps:
            - jira/notify
          requires:
            - build-platform-config-test
            - build-realtime-sdk-test
            - build-socket-utils-test

      - vfcommon/install_and_build:
          <<: *slack-fail-post-step
          context: dev-test
          avoid_post_install_scripts: false
          attach_workspace: true
          name: build-ml-gateway-test
          force_execute: << pipeline.parameters.build-backend >>
          package: ml-gateway
          package_folder: apps
          container_folder_to_copy: apps/ml-gateway/build
          post-steps:
            - jira/notify
          requires:
            - build-ml-sdk-test
            - build-socket-utils-test

      - test:
          <<: *slack-fail-post-step
          context: dev-test
          name: test-master
          requires:
            - build-ml-sdk-test
            - build-platform-config-test
            - build-realtime-sdk-test
            - build-ui-test
            - build-socket-utils-test
          filters:
            branches:
              only: master

      - test:
          <<: *slack-fail-post-step
          context: dev-test
          filters:
            <<: *ignore_master_prod_break_glass_filters
          requires:
            - build-ml-sdk-test
            - build-platform-config-test
            - build-realtime-sdk-test
            - build-ui-test
            - build-socket-utils-test

      - vfcommon/monorepo_release:
          <<: *slack-fail-post-step
          sentry_project: creator-app
          avoid_post_install_scripts: false
          ssh_key: << pipeline.parameters.ssh-fingerprint >>
          context: dev-test
          requires:
            - test
            - test-master
            - build-app-test
            - build-showcase-test
            - build-realtime-test
            - build-ml-gateway-test
          filters:
            branches:
              only: master

      - vfcommon/update_track:
          <<: *ignore_break_glass_deploy_filters
          context: dev-test
          name: update-track-creator-app
          force_execute: << pipeline.parameters.build-frontend >>
          image_repo: << pipeline.parameters.container-image-url-creator-app >>
          component: << pipeline.parameters.track-component-creator-app >>
          build_context: apps/creator-app
          package: creator-app
          post-steps:
            - jira/notify:
                environment: ${CIRCLE_BRANCH%%_*}
                environment_type: testing
                job_type: deployment
          requires:
            - test-master
            - build-app-test
            - vfcommon/monorepo_release

      - vfcommon/update_track:
          <<: *ignore_break_glass_deploy_filters
          context: dev-test
          name: update-track-showcase
          force_execute: << pipeline.parameters.build-frontend >>
          image_repo: << pipeline.parameters.container-image-url-showcase >>
          component: << pipeline.parameters.track-component-showcase >>
          build_context: apps/showcase
          package: showcase
          requires:
            - test-master
            - build-showcase-test
            - vfcommon/monorepo_release

      - vfcommon/update_track:
          <<: *ignore_break_glass_deploy_filters
          context: dev-test
          name: update-track-realtime
          force_execute: << pipeline.parameters.build-backend >>
          local_registry: true
          image_repo: << pipeline.parameters.container-image-url-realtime >>
          component: << pipeline.parameters.track-component-realtime >>
          build_context: apps/realtime
          package: realtime
          requires:
            - test-master
            - build-realtime-test
            - vfcommon/monorepo_release

      - vfcommon/update_track:
          <<: *ignore_break_glass_deploy_filters
          context: dev-test
          name: update-track-ml-gateway
          local_registry: true
          force_execute: << pipeline.parameters.build-backend >>
          image_repo: << pipeline.parameters.container-image-url-ml-gateway >>
          component: << pipeline.parameters.track-component-ml-gateway >>
          build_context: apps/ml-gateway
          package: ml-gateway
          post-steps:
            - jira/notify:
                environment: ${CIRCLE_BRANCH%%_*}
                environment_type: testing
                job_type: deployment
          requires:
            - test-master
            - build-ml-gateway-test
            - vfcommon/monorepo_release

      - vfcommon/sync_branches:
          check_commit_message: '[bugfix]'
          ssh_key: << pipeline.parameters.ssh-fingerprint >>
          checkout: true
          context: dev-test
          name: sync-branches-bugfix
          requires:
            - test
            - test-master
            - build-app-test
            - build-showcase-test
            - build-realtime-test
            - build-ml-gateway-test
            - vfcommon/monorepo_release
          filters:
            branches:
              only: master

      - vfcommon/sync_branches:
          check_commit_message: "[breakglass]"
          ssh_key: << pipeline.parameters.ssh-fingerprint >>
          checkout: true
          context: dev-test
          name: sync-branches-break-glass
          requires:
            - build-app-test
            - build-showcase-test
            - build-realtime-test
            - build-ml-gateway-test
          filters:
            branches:
              only: master

      # Deploy services
      - vfcommon/post_image_push_actions:
          <<: *prod_deploy_filters
          context: dev-test
          name: ml-gateway-release-post-actions
          force_execute: << pipeline.parameters.build-backend >>
          namespace: << pipeline.parameters.k8s-namespace >>
          component: << pipeline.parameters.track-component-ml-gateway >>
          package: ml-gateway
          tagged: true
          success_slack_notify: false
          requires:
            - update-track-ml-gateway

      - vfcommon/build_push_image:
          name: build-push-ml-gateway-image-e2e
          context: dev-test
          monorepo_directory: ~/voiceflow
          image_repo: << pipeline.parameters.container-image-url-ml-gateway >>
          force_execute: << pipeline.parameters.build-backend >>
          package: ml-gateway
          build_context: apps/ml-gateway
          dockerfile: 'Dockerfile.e2e'
          image_tag: 'latest-master-e2e'
          requires:
            - update-track-ml-gateway
          filters:
            branches:
              only: master

      - vfcommon/post_image_push_actions:
          <<: *prod_deploy_filters
          context: dev-test
          name: realtime-release-post-actions
          force_execute: << pipeline.parameters.build-backend >>
          namespace: << pipeline.parameters.k8s-namespace >>
          component: << pipeline.parameters.track-component-realtime >>
          package: realtime
          tagged: true
          success_slack_notify: false
          requires:
            - update-track-realtime
      - vfcommon/build_push_image:
          name: build-push-realtime-image-e2e
          context: dev-test
          monorepo_directory: ~/voiceflow
          image_repo: << pipeline.parameters.container-image-url-realtime >>
          build_context: apps/realtime
          force_execute: << pipeline.parameters.build-backend >>
          package: realtime
          dockerfile: 'Dockerfile.e2e'
          image_tag: 'latest-master-e2e'
          requires:
            - update-track-realtime
          filters:
            branches:
              only: master

      - vfcommon/post_image_push_actions:
          <<: *prod_deploy_filters
          context: dev-test
          name: creator-app-release-post-actions
          force_execute: << pipeline.parameters.build-frontend >>
          namespace: << pipeline.parameters.k8s-namespace >>
          component: << pipeline.parameters.track-component-creator-app >>
          package: creator-app
          tagged: true
          post-steps:
            - jira/notify:
                environment: public
                environment_type: production
                job_type: deployment
          requires:
            - update-track-creator-app
      - vfcommon/post_image_push_actions:
          <<: *prod_deploy_filters
          context: dev-test
          force_execute: << pipeline.parameters.build-frontend >>
          namespace: << pipeline.parameters.k8s-namespace >>
          component: << pipeline.parameters.track-component-showcase >>
          package: showcase
          name: showcase-release-post-actions
          tagged: true
          success_slack_notify: false
          requires:
            - update-track-showcase
