export enum LimitType {
  PROJECTS = 'PROJECTS',
  WORKSPACES = 'WORKSPACES',
  MARKUP_IMAGE = 'MARKUP_IMAGE',
  MARKUP_VIDEO = 'MARKUP_VIDEO',
  EDITOR_SEATS = 'EDITOR_SEATS',
  VIEWER_SEATS = 'VIEWER_SEATS',
  VARIABLE_STATES = 'VARIABLE_STATES',
}
