import { VoiceflowConstants } from '@voiceflow/voiceflow-types';

const BUILT_IN_NO_REPLIES_BY_LANGUAGE = {
  [VoiceflowConstants.Language.EN]: [
    "I'm sorry, I didn't receive a response. Can you please let me know how I can assist you?",
    'I apologize if my previous message was unclear. Could you please let me know what you need help with?',
    "It looks like I didn't receive a reply from you. Is there something specific you'd like to know or discuss?",
    "I'm here to help with any questions or concerns you have. Is there anything you'd like to ask or talk about?",
    "I apologize if I missed your response. Is there anything you'd like to know or discuss?",
    "I'm here to assist you with any questions or concerns. Is there anything you'd like to ask me about?",
    "I'm sorry if my previous message was not helpful. Is there anything else you'd like to know or discuss?",
    'I apologize if my previous message was confusing. Could you please let me know what you need help with?',
    "I didn't receive a response from you. Is there anything specific you'd like to know or discuss?",
    "I'm here to help with any questions or concerns you have. Is there something specific you'd like to ask or talk about?",
  ],

  [VoiceflowConstants.Language.AR]: [
    'أعتذر، لم يتم تلقي رد. هل يمكنك المساعدة في تحديد كيف يمكنني مساعدتك؟',
    'أعتذر إذا كان رسالتي السابقة غير واضحة. هل يمكنك المساعدة في تحديد ما الذي تحتاج إلى المساعدة فيه؟',
    'يبدو أنني لم أتلق رد. هل هناك شيء معين يريد معرفته أو مناقشته؟',
    'أنا هنا للمساعدة في أي استفسارات أو مخاوف لديك. هل هناك شيء معين يريد أن يسألني عنه أو يتحدث عنه؟',
    'أعتذر إذا فاتتني ردودك. هل هناك شيء معين يريد معرفته أو مناقشته؟',
    'أنا هنا للمساعدة في أي استفسارات أو مخاوف لديك. هل هناك شيء معين يريد أن يسألني عنه؟',
    'أعتذر إذا كان رسالتي السابقة لا تساعد. هل هناك شيء آخر يريد معرفته أو مناقشته؟',
    'أعتذر إذا كان رسالتي السابقة مربكة. هل يمكنك المساعدة في تحديد ما الذي تحتاج إلى المساعدة فيه؟',
  ],

  [VoiceflowConstants.Language.ZH]: [
    '对不起，我没有收到回复。请告诉我如何帮助您。',
    '如果我之前的消息不清楚，我深表歉意。您需要帮助哪方面？',
    '看起来我没有收到您的回复。您有什么特别想知道或讨论的吗？',
    '我来帮助您解答任何问题或疑虑。您有什么要问或谈论的吗？',
    '如果我错过了您的回复，我深表歉意。您有什么想知道或讨论的吗？',
    '我来帮助您解决任何问题或疑虑。您有什么想问我的吗？',
    '如果我之前的消息没有帮助，我深表歉意。您还有什么想知道或讨论的吗？',
    '如果我之前的消息令您困惑，我深表歉意。您需要帮助哪方面？',
    '我没有收到您的回复。您有什么特别想知道或讨论的吗？',
    '我来帮助您解决任何问题或疑虑。您有什么特别要问或谈论的吗？',
  ],

  [VoiceflowConstants.Language.NL]: [
    'Het spijt me, ik heb geen reactie ontvangen. Kunt u me alstublieft laten weten hoe ik u kan helpen?',
    'Als mijn vorige bericht onduidelijk was, bied ik mijn verontschuldigingen aan. Kunt u me alstublieft laten weten waarmee u hulp nodig heeft?',
    'Het lijkt erop dat ik geen antwoord van u heb ontvangen. Heeft u iets specifieks waarover u wilt weten of waarover u wilt praten?',
    'Ik ben hier om te helpen met eventuele vragen of zorgen die u heeft. Heeft u iets wat u wilt vragen of waarover u wilt praten?',
    'Als ik uw reactie heb gemist, bied ik mijn verontschuldigingen aan. Heeft u iets waarover u wilt weten of waarover u wilt praten?',
    'Ik ben hier om u te helpen met eventuele vragen of zorgen. Heeft u iets wat u mij wilt vragen?',
    'Als mijn vorige bericht niet behulpzaam was, bied ik mijn verontschuldigingen aan. Heeft u nog iets anders waarover u wilt weten of waarover u wilt praten?',
    'Als mijn vorige bericht verwarrend was, bied ik mijn verontschuldigingen aan. Kunt u me alstublieft laten weten waarmee u hulp nodig heeft?',
    'Ik heb geen reactie van u ontvangen. Heeft u iets specifieks waarover u wilt weten of waarover u wilt praten?',
    'Ik ben hier om te helpen met eventuele vragen of zorgen die u heeft. Heeft u iets specifieks waarover u wilt vragen of waarover u wilt praten?',
  ],

  [VoiceflowConstants.Language.FR]: [
    "Désolé, je n'ai pas reçu de réponse. Pouvez-vous me dire comment je peux vous aider ?",
    "Si mon précédent message n'était pas clair, je vous présente mes excuses. Pourriez-vous me dire en quoi vous avez besoin d'aide ?",
    "Il semble que je n'ai pas reçu de réponse de votre part. Y a-t-il quelque chose de spécifique que vous aimeriez savoir ou discuter ?",
    'Je suis là pour vous aider avec toutes les questions ou les préoccupations que vous pourriez avoir. Y a-t-il quelque chose que vous aimeriez me demander ou discuter ?',
    "Si j'ai manqué votre réponse, je vous présente mes excuses. Y a-t-il quelque chose que vous aimeriez savoir ou discuter ?",
    'Je suis là pour vous aider avec toutes les questions ou les préoccupations que vous pourriez avoir. Y a-t-il quelque chose que vous aimeriez me demander ?',
    "Si mon précédent message n'était pas utile, je vous présente mes excuses. Y a-t-il autre chose que vous aimeriez savoir ou discuter ?",
    "Si mon précédent message était confus, je vous présente mes excuses. Pourriez-vous me dire en quoi vous avez besoin d'aide ?",
  ],

  [VoiceflowConstants.Language.DE]: [
    'Entschuldigung, ich habe keine Antwort erhalten. Können Sie mir bitte sagen, wie ich Ihnen helfen kann?',
    'Wenn meine vorherige Nachricht unklar war, bitte ich um Entschuldigung. Können Sie mir bitte sagen, wo Sie Hilfe benötigen?',
    'Es sieht so aus, als hätte ich keine Antwort von Ihnen erhalten. Gibt es etwas Spezielles, das Sie wissen oder besprechen möchten?',
    'Ich bin hier, um Ihnen bei allen Fragen oder Bedenken zu helfen. Gibt es etwas, das Sie mich fragen oder besprechen möchten?',
    'Wenn ich Ihre Antwort verpasst habe, bitte ich um Entschuldigung. Gibt es etwas, das Sie wissen oder besprechen möchten?',
    'Ich bin hier, um Ihnen bei allen Fragen oder Bedenken zu helfen. Gibt es etwas, das Sie mich fragen möchten?',
    'Wenn meine vorherige Nachricht nicht hilfreich war, bitte ich um Entschuldigung. Gibt es etwas anderes, das Sie wissen oder besprechen möchten?',
    'Wenn meine vorherige Nachricht verwirrend war, bitte ich um Entschuldigung. Können Sie mir bitte sagen, wo Sie Hilfe benötigen?',
    'Ich habe keine Antwort von Ihnen erhalten. Gibt es etwas Spezielles, das Sie wissen oder besprechen möchten?',
    'Ich bin hier, um Ihnen bei allen Fragen oder Bedenken zu helfen. Gibt es etwas Spezielles, das Sie mich fragen oder besprechen möchten?',
  ],

  [VoiceflowConstants.Language.GU]: [
    'માફ કરશો, મને જવાબ મળી નથી. તમે મને કોઈ મદદ કરી શકો છો કે મને કેવું મદદ કરી શકૂં તે જણાવીને?',
    'જો મારા પહેલાનો સંદેશ અસ્પષ્ટ હોય હોય તો, માફ કરશો. તમે કોઈ મદદ કરી માંગો છો કે મને કેવું મદદ કરી શકૂં તે જણાવીને?',
  ],

  [VoiceflowConstants.Language.HI]: [
    'आपने उत्तर नहीं दिया है, क्या आप सुनना चाहते हैं?',
    'आपने अभी तक कोई जवाब नहीं दिया है, क्या आपकी समस्याएं हैं?',
    'आपने अभी तक कोई उत्तर नहीं दिया है, क्या आपको मेरा सवाल समझ में आ गया?',
    'आपने अभी तक कोई जवाब नहीं दिया है, क्या आपको कोई सहायता चाहिए?',
    'आपने अभी तक कोई उत्तर नहीं दिया है, क्या आप संभवतः हमारे बातें सुन रहे हैं?',
    'आपने अभी तक कोई जवाब नहीं दिया है, आपको कोई और सुझाव चाहिए?',
    'आपने अभी तक कोई उत्तर नहीं दिया है, क्या आपको कोई अन्य सवाल है?',
  ],

  [VoiceflowConstants.Language.IT]: [
    'Non hai ancora risposto, vuoi sentire di nuovo la domanda?',
    'Non hai ancora risposto, hai dei problemi?',
    'Non hai ancora risposto, hai capito la mia domanda?',
    'Non hai ancora risposto, hai bisogno di aiuto?',
    'Non hai ancora risposto, stai ascoltando attentamente quello che dico?',
    'Non hai ancora risposto, vuoi che ti faccia altre proposte?',
    'Non hai ancora risposto, hai altre domande?',
    'Non hai ancora risposto, vuoi descrivermi il tuo problema in modo più dettagliato?',
    "Non hai ancora risposto, c'è qualcos'altro che posso fare per te?",
    'Non hai ancora risposto, vuoi che ti spieghi di nuovo il concetto in modo diverso?',
  ],

  [VoiceflowConstants.Language.JA]: [
    '返答がありませんでした、もう一度質問を聞きますか？',
    '返答がありませんでした、問題がありますか？',
    '返答がありませんでした、私の質問がわかりましたか？',
    '返答がありませんでした、助けが必要ですか？',
    '返答がありませんでした、私の話を注意深く聞いていますか？',
    '返答がありませんでした、他のアイデアを紹介しますか？',
    '返答がありませんでした、他に質問はありますか？',
    '返答がありませんでした、もっと詳しく問題を説明しますか？',
    '返答がありませんでした、あなたに他にできることはありますか？',
    '返答がありませんでした、別の方法で概念を説明しますか？',
  ],

  [VoiceflowConstants.Language.KO]: [
    '아직 응답하지 않으셨습니다. 질문을 다시 듣고 싶으신가요?',
    '아직 응답하지 않으셨습니다. 어려움이 있으신가요?',
    '아직 응답하지 않으셨습니다. 내 질문을 이해하셨나요?',
    '아직 응답하지 않으셨습니다. 도움이 필요하신가요?',
    '아직 응답하지 않으셨습니다. 내 얘기를 정중히 듣고 계신가요?',
    '아직 응답하지 않으셨습니다. 다른 아이디어를 제시해 드릴까요?',
    '아직 응답하지 않으셨습니다. 다른 질문이 있으신가요?',
    '아직 응답하지 않으셨습니다. 자세히 설명해 주시겠어요?',
    '아직 응답하지 않으셨습니다. 다른 것을 할 수 있겠어요?',
    '아직 응답하지 않으셨습니다. 다른 방식으로 개념을 설명해 드릴까요?',
  ],

  [VoiceflowConstants.Language.MR]: [
    'आपण तुमच्या जवाबाची आणि आपल्या प्रश्नाची माहिती नमूद केलेली नाही, आपण जवाब देण्याची इच्छा आहे का?',
    'आपण तुमच्या जवाबाची आणि आपल्या प्रश्नाची माहिती नमूद केलेली नाही, तुम्ही काही समस्यांसहित आहात का?',
    'आपण तुमच्या जवाबाची आणि आपल्या प्रश्नाची माहिती नमूद केलेली नाही, माझे प्रश्न तुम्ही समजले आहे का?',
    'आपण तुमच्या जवाबाची आणि आपल्या प्रश्नाची माहिती नमूद केलेली नाही, तुम्ही मदत करण्याची जरूरी आहे का?',
  ],

  [VoiceflowConstants.Language.PT]: [
    'Desculpe, eu não consegui entender o que você escreveu. Poderia me explicar de outra maneira?',
    'Não consegui entender o que você quer. Poderia ser mais específico(a)?',
    'Desculpe, eu não consegui entender o que você está tentando dizer. Poderia reformular sua pergunta?',
    'Eu não consegui entender sua mensagem. Poderia me dizer de outra maneira o que você precisa?',
    'Desculpe, eu não consegui entender o que você escreveu. Poderia me explicar de outra maneira?',
    'Não consegui entender o que você quer. Poderia ser mais claro(a)?',
    'Desculpe, eu não consegui entender sua mensagem. Poderia reformular sua pergunta?',
    'Eu não consegui entender o que você está tentando dizer. Poderia me dizer de outra maneira o que você precisa?',
  ],

  [VoiceflowConstants.Language.ES]: [
    '¿Sigues ahí? ¿Puedes decirme lo que necesitas?',
    'No entendí lo que quisiste decir. ¿Podrías reformular tu pregunta?',
    'Lo siento, no entendí lo que escribiste. ¿Podrías explicarlo de otra manera?',
    'No entendí lo que quieres. ¿Podrías ser más específico?',
    'Lo siento, no entendí lo que estás tratando de decir. ¿Podrías reformular tu pregunta?',
    'No entendí tu mensaje. ¿Podrías decirme de otra manera lo que necesitas?',
    'Lo siento, no entendí lo que escribiste. ¿Podrías explicarlo de otra manera?',
    'No entendí lo que quieres. ¿Podrías ser más claro?',
    'Lo siento, no entendí tu mensaje. ¿Podrías reformular tu pregunta?',
    'No entendí lo que estás tratando de decir. ¿Podrías decirme de otra manera lo que necesitas?',
  ],

  [VoiceflowConstants.Language.TA]: [
    'நீங்கள் இன்னும் இங்கே உள்ளார்களா? நீங்களுக்கு எவை தேவையாகிறது என்று எனக்கு சொல்லவும்?',
    'எனக்கு உங்களுடன் எந்தவை பேச விட்டுள்ளது என்பதை நினைவில்லை. உங்கள் கேள்வியை மறுவிவரிக்க முடியுமா?',
    'என்ன வேண்டும் என்று நினைவில்லை. முன்னிருப்புக்கூடியதாக பயன்படுத்தவும்?',
    'மன்னிக்கவும், எனக்கு உங்கள் சொல்லின் என்ன போன்றதை பார்க்க முடியவில்லை. உங்கள் கேள்வியை மறுவிவரிக்க முடியுமா?',
  ],

  [VoiceflowConstants.Language.TE]: [
    'మీరు ఇంకా ఇక్కడ ఉన్నారు? మీరు ఎవరైనా అవసరం ఉంటే నాకు తెలుసుకోవాలనుకుంటున్నారు?',
    'నేను మీరు ఏమం చెప్పారు తెలుసలేదు. మీ ప్రశ్నని మళ్ళీ తరలించాలనుకుంటున్నారా?',
    'క్షమించండి, నేను మీరు చెప్పిన అంశాన్ని తెలుసలేదు. మీరు ఇంకా ఎలా వివరించాలనుకుంటున్నారు?',
  ],

  [VoiceflowConstants.Language.TR]: [
    'Hala buradasın mı? Ne ihtiyacın olduğunu bana söyleyebilir misin?',
    'Ne demek istediğini anlamadım. Sorma şeklini değiştirebilir misin?',
    'Ne istediğini anlamadım. Daha spesifik olabilir misin?',
    'Özür dilerim, ne demek istediğini anlayamadım. Sorma şeklini değiştirebilir misin?',
    'Mesajını anlayamadım. Ne ihtiyacın olduğunu başka bir şekilde söyleyebilir misin?',
    'Özür dilerim, yazdıklarını anlayamadım. Başka bir şekilde açıklayabilir misin?',
    'Ne istediğini anlamadım. Daha açık olabilir misin?',
    'Özür dilerim, mesajını anlayamadım. Sorma şeklini değiştirebilir misin?',
    'Ne demek istediğini anlayamadım. Ne ihtiyacın olduğunu başka bir şekilde söyleyebilir misin?',
  ],

  [VoiceflowConstants.Language.BG]: [
    'Съжалявам, не получих отговор. Можете ли да ми кажете как мога да ви помогна?',
    'Извинявам се, ако предишното ми съобщение беше неясно. Можете ли да ми кажете с какво се нуждаете от помощ?',
    'Изглежда, че не получих отговор от вас. Имате ли конкретен въпрос или тема, за която бихте искали да знаете или обсъдите?',
    'Тук съм, за да помогна с всякакви въпроси или загрижености, които имате. Има ли нещо, което бихте искали да попитате или обсъдите?',
    'Извинявам се, ако пропуснах вашия отговор. Има ли нещо, което бихте искали да знаете или обсъдите?',
    'Тук съм, за да ви помогна с всякакви въпроси или притеснения. Има ли нещо, което бихте искали да ме попитате?',
    'Съжалявам, ако предишното ми съобщение не беше полезно. Има ли нещо друго, което бихте искали да знаете или обсъдите?',
    'Извинявам се, ако предишното ми съобщение беше объркващо. Можете ли да ми кажете с какво се нуждаете от помощ?',
    'Не получих отговор от вас. Има ли нещо конкретно, което бихте искали да знаете или обсъдите?',
    'Тук съм, за да помогна с всякакви въпроси или загрижености, които имате. Има ли нещо конкретно, което бихте искали да попитате или обсъдите?',
  ],
  [VoiceflowConstants.Language.CA]: [
    'Em sap greu, no he rebut cap resposta. Podries fer-me saber com puc ajudar-te, si us plau?',
    'Lamento si el meu missatge anterior no va ser clar. Podries fer-me saber en què necessites ajuda?',
    "Sembla que no he rebut cap resposta teva. Hi ha alguna cosa concreta que t'agradaria saber o discutir?",
    "Estic aquí per ajudar-te amb qualsevol pregunta o preocupació que tinguis. Hi ha alguna cosa que t'agradaria preguntar o parlar-ne?",
    "Em sap greu si he oblidat la teva resposta. Hi ha alguna cosa que t'agradaria saber o discutir?",
    "Estic aquí per ajudar-te amb qualsevol pregunta o preocupació. Hi ha alguna cosa que t'agradaria preguntar-me?",
    "Lamento si el meu missatge anterior no va ser útil. Hi ha alguna altra cosa que t'agradaria saber o discutir?",
    'Lamento si el meu missatge anterior va ser confús. Podries fer-me saber en què necessites ajuda?',
    "No he rebut cap resposta teva. Hi ha alguna cosa concreta que t'agradaria saber o discutir?",
    "Estic aquí per ajudar-te amb qualsevol pregunta o preocupació que tinguis. Hi ha alguna cosa concreta que t'agradaria preguntar o parlar-ne?",
  ],
  [VoiceflowConstants.Language.CS]: [
    'Omlouvám se, nedostal jsem odpověď. Mohl byste mi prosím sdělit, jak vám mohu pomoci?',
    'Omlouvám se, pokud byla má předchozí zpráva nejasná. Mohl(a) byste mi prosím sdělit, co potřebujete?',
    'Zdá se, že jsem od vás nedostal odpověď. Je něco konkrétního, o čem byste chtěl(a) vědět nebo diskutovat?',
    'Jsem tu, abych vám pomohl(a) s jakýmikoli otázkami nebo obavami, které máte. Je něco, o čem byste chtěl(a) něco vědět nebo diskutovat?',
    'Omlouvám se, pokud jsem přehlédl vaši odpověď. Je něco, co byste chtěl(a) vědět nebo projednat?',
    'Jsem tu, abych vám pomohl(a) s jakýmkoli otázkami nebo obavami. Je něco, co byste se mě chtěl(a) na něco zeptat?',
    'Omlouvám se, pokud má předchozí zpráva nepomohla. Je něco dalšího, o čem byste chtěl(a) vědět nebo diskutovat?',
    'Omlouvám se, pokud byla má předchozí zpráva matoucí. Mohl(a) byste mi prosím sdělit, co potřebujete?',
    'Od vás jsem nedostal odpověď. Je něco konkrétního, o čem byste chtěl(a) vědět nebo diskutovat?',
    'Jsem tu, abych vám pomohl(a) s jakýmikoli otázkami nebo obavami, které máte. Je něco konkrétního, o čem byste se chtěl(a) zeptat nebo diskutovat?',
  ],
  [VoiceflowConstants.Language.DA]: [
    'Jeg beklager, jeg modtog ikke et svar. Kan du venligst lade mig vide, hvordan jeg kan hjælpe dig?',
    'Jeg beklager, hvis min tidligere besked var uklar. Kunne du venligst lade mig vide, hvad du har brug for hjælp til?',
    'Det ser ud til, at jeg ikke modtog et svar fra dig. Er der noget specifikt, du gerne vil vide eller diskutere?',
    'Jeg er her for at hjælpe med eventuelle spørgsmål eller bekymringer, du måtte have. Er der noget, du gerne vil spørge eller tale om?',
    'Jeg beklager, hvis jeg har overset dit svar. Er der noget, du gerne vil vide eller diskutere?',
    'Jeg er her for at hjælpe dig med eventuelle spørgsmål eller bekymringer. Er der noget, du gerne vil spørge mig om?',
    'Jeg beklager, hvis min tidligere besked ikke var hjælpsom. Er der noget andet, du gerne vil vide eller diskutere?',
    'Jeg beklager, hvis min tidligere besked var forvirrende. Kunne du venligst lade mig vide, hvad du har brug for hjælp til?',
    'Jeg modtog ikke et svar fra dig. Er der noget specifikt, du gerne vil vide eller diskutere?',
    'Jeg er her for at hjælpe med eventuelle spørgsmål eller bekymringer, du måtte have. Er der noget specifikt, du gerne vil spørge eller tale om?',
  ],
  [VoiceflowConstants.Language.ET]: [
    'Vabandust, ma ei saanud vastust. Kas saaksite palun öelda, kuidas ma saan teid aidata?',
    'Vabandust, kui mu eelmine sõnum oli arusaamatu. Kas saaksite palun öelda, millega te abi vajate?',
    'Tundub, et ma ei saanud teilt vastust. Kas teil on midagi konkreetset, millest tahaksite teada saada või arutada?',
    'Olen siin, et aidata kõikide teie küsimuste või muredega. Kas teil on midagi, mida soovite küsida või arutada?',
    'Vabandust, kui ma jätsin teie vastuse märkamata. Kas on midagi, millest soovite teada saada või arutada?',
    'Olen siin, et aidata teid kõikide küsimuste või muredega. Kas on midagi, millest soovite minult küsida?',
    'Vabandust, kui mu eelmine sõnum ei olnud abiks. Kas on midagi muud, millest soovite teada saada või arutada?',
    'Vabandust, kui mu eelmine sõnum oli segadust tekitav. Kas saaksite palun öelda, millega te abi vajate?',
    'Ma ei saanud teilt vastust. Kas teil on midagi konkreetset, millest tahaksite teada saada või arutada?',
    'Olen siin, et aidata kõikide teie küsimuste või muredega. Kas teil on midagi konkreetset, millest tahaksite küsida või rääkida?',
  ],
  [VoiceflowConstants.Language.HE]: [
    'מצטער, לא קיבלתי תשובה. האם תוכל להגיד לי איך אני יכול לסייע לך?',
    'אני מתנצל אם הודעתי הקודמת שלי לא הייתה ברורה. האם תוכל להגיד לי במה אתה זקוק לעזרה?',
    'נראה שלא קיבלתי תשובה ממך. האם יש משהו מסוים שתרצה לדעת או לדון עליו?',
    'אני כאן כדי לעזור עם כל שאלה או דאגה שיש לך. האם יש משהו שתרצה לשאול או לשוחח עליו?',
    'אני מתנצל אם פספסתי את התגובה שלך. האם יש משהו שתרצה לדעת או לדון עליו?',
    'אני כאן כדי לסייע לך עם כל שאלה או דאגה. האם יש משהו שתרצה לשאול אותי עליו?',
    'מצטער אם הודעתי הקודמת שלי לא הייתה מועילה. האם יש משהו אחר שתרצה לדעת או לדון עליו?',
    'אני מתנצל אם הודעתי הקודמת שלי הייתה מבלבלת. האם תוכל להגיד לי במה אתה זקוק לעזרה?',
    'לא קיבלתי תשובה ממך. האם יש משהו מסוים שתרצה לדעת או לדון עליו?',
    'אני כאן כדי לעזור עם כל שאלה או דאגה שיש לך. האם יש משהו מסוים שתרצה לשאול או לשוחח עליו?',
  ],
  [VoiceflowConstants.Language.HU]: [
    'Sajnálom, nem kaptam választ. Kérlek, tudasd velem, hogyan segíthetek neked?',
    'Elnézést kérek, ha az előző üzenetem nem volt egyértelmű. Meg tudnád mondani, miben segíthetek?',
    'Úgy tűnik, nem kaptam választ tőled. Van valami konkrét dolog, amiről szeretnél tudni vagy beszélgetni?',
    'Itt vagyok, hogy segítsek minden kérdésben vagy aggodalomban, amivel hozzám fordulsz. Van valami, amit kérdezni szeretnél vagy meg szeretnél beszélni?',
    'Elnézést kérek, ha nem vettem észre a válaszodat. Van valami, amiről szeretnél tudni vagy beszélgetni?',
    'Itt vagyok, hogy segítsek minden kérdésben vagy aggodalomban. Van valami, amire kérdésed van felém?',
    'Elnézést kérek, ha az előző üzenetem nem volt hasznos. Van valami más, amiről szeretnél tudni vagy beszélgetni?',
    'Elnézést kérek, ha az előző üzenetem zavaros volt. Meg tudnád mondani, miben segíthetek?',
    'Nem kaptam választ tőled. Van valami konkrét dolog, amiről szeretnél tudni vagy beszélgetni?',
    'Itt vagyok, hogy segítsek minden kérdésben vagy aggodalomban, amivel hozzám fordulsz. Van valami konkrét, amiről kérdésed van vagy beszélgetnél?',
  ],
  [VoiceflowConstants.Language.PL]: [
    'Przepraszam, nie otrzymałem odpowiedzi. Czy możesz mi proszę powiedzieć, jak mogę pomóc?',
    'Przepraszam, jeśli moja poprzednia wiadomość była niejasna. Czy możesz mi proszę powiedzieć, w czym potrzebujesz pomocy?',
    'Wygląda na to, że nie otrzymałem od ciebie odpowiedzi. Czy jest coś konkretnego, o czym chciałbyś się dowiedzieć lub porozmawiać?',
    'Jestem tutaj, aby pomóc w razie pytań lub wątpliwości. Czy jest coś, o co chciałbyś zapytać lub porozmawiać?',
    'Przepraszam, jeśli przeoczyłem twoją odpowiedź. Czy jest coś, o co chciałbyś się dowiedzieć lub porozmawiać?',
    'Jestem tutaj, aby pomóc w razie pytań lub wątpliwości. Czy jest coś, o co chciałbyś mnie zapytać?',
    'Przepraszam, jeśli moja poprzednia wiadomość była niewystarczająca. Czy jest coś innego, o co chciałbyś się dowiedzieć lub porozmawiać?',
    'Przepraszam, jeśli moja poprzednia wiadomość była myląca. Czy możesz mi proszę powiedzieć, w czym potrzebujesz pomocy?',
    'Nie otrzymałem odpowiedzi od ciebie. Czy jest coś konkretnego, o czym chciałbyś się dowiedzieć lub porozmawiać?',
    'Jestem tutaj, aby pomóc w razie pytań lub wątpliwości. Czy jest coś konkretnego, o co chciałbyś zapytać lub porozmawiać?',
  ],
  [VoiceflowConstants.Language.RO]: [
    'Îmi pare rău, nu am primit un răspuns. Puteți să-mi spuneți, vă rog, cum vă pot ajuta?',
    'Îmi cer scuze dacă mesajul meu anterior nu a fost clar. Ați putea să-mi spuneți cu ce aveți nevoie de ajutor?',
    'Se pare că nu am primit un răspuns de la dumneavoastră. Există ceva anume despre care doriți să știți sau să discutați?',
    'Sunt aici să vă ajut cu orice întrebări sau nelămuriri aveți. Există ceva ce doriți să întrebați sau să discutați?',
    'Îmi cer scuze dacă am ratat răspunsul dumneavoastră. Există ceva despre care doriți să știți sau să discutați?',
    'Sunt aici să vă ajut cu orice întrebări sau nelămuriri aveți. Există ceva despre care doriți să mă întrebați?',
    'Îmi pare rău dacă mesajul meu anterior nu a fost de ajutor. Există altceva despre care doriți să știți sau să discutați?',
    'Îmi cer scuze dacă mesajul meu anterior a fost confuz. Ați putea să-mi spuneți cu ce aveți nevoie de ajutor?',
    'Nu am primit un răspuns de la dumneavoastră. Există ceva anume despre care doriți să știți sau să discutați?',
    'Sunt aici să vă ajut cu orice întrebări sau nelămuriri aveți. Există ceva anume despre care doriți să întrebați sau să discutați?',
  ],
  [VoiceflowConstants.Language.RU]: [
    'Извините, я не получил ответа. Можете ли вы, пожалуйста, сообщить мне, как я могу вам помочь?',
    'Прошу прощения, если моё предыдущее сообщение было неясным. Не могли бы вы сообщить мне, в чём вам нужна помощь?',
    'Похоже, я не получил ответа от вас. Есть ли что-то конкретное, о чём вы хотели бы узнать или обсудить?',
    'Я здесь, чтобы помочь с любыми вопросами или заботами, которые у вас есть. Есть ли что-то, о чём вы хотели бы спросить или поговорить?',
    'Прошу прощения, если я упустил ваш ответ. Есть ли что-то, о чём вы хотели бы узнать или обсудить?',
    'Я здесь, чтобы помочь вам с любыми вопросами или заботами. Есть ли что-то, о чём вы хотели бы меня спросить?',
    'Прошу прощения, если моё предыдущее сообщение было бесполезным. Есть ли что-то ещё, о чём вы хотели бы узнать или обсудить?',
    'Прошу прощения, если моё предыдущее сообщение вызвало путаницу. Не могли бы вы сообщить мне, в чём вам нужна помощь?',
    'Я не получил ответа от вас. Есть ли что-то конкретное, о чём вы хотели бы узнать или обсудить?',
    'Я здесь, чтобы помочь с любыми вопросами или заботами, которые у вас есть. Есть ли что-то конкретное, о чём вы хотели бы спросить или поговорить?',
  ],
  [VoiceflowConstants.Language.UK]: [
    'Вибачте, я не отримав відповіді. Чи можете ви, будь ласка, повідомити мені, як я можу вам допомогти?',
    'Вибачте, якщо моє попереднє повідомлення було незрозумілим. Чи можете ви, будь ласка, повідомити мені, в чому ви потребуєте допомоги?',
    'Схоже, що я не отримав від вас відповіді. Чи є щось конкретне, що ви хочете знати або обговорити?',
    'Я тут, щоб допомогти з будь-якими питаннями чи стурбованостями, які у вас є. Чи є що-небудь, про що ви хотіли б запитати або поговорити?',
    'Вибачте, якщо я пропустив вашу відповідь. Чи є щось, про що ви хотіли б дізнатися або обговорити?',
    'Я тут, щоб допомогти вам з будь-якими питаннями чи стурбованостями. Чи є що-небудь, про що ви хотіли б мене запитати?',
    'Вибачте, якщо моє попереднє повідомлення не було корисним. Чи є щось ще, про що ви хотіли б дізнатися або обговорити?',
    'Вибачте, якщо моє попереднє повідомлення було заплутане. Чи можете ви, будь ласка, повідомити мені, в чому ви потребуєте допомоги?',
    'Я не отримав відповіді від вас. Чи є щось конкретне, що ви хотіли б дізнатися або обговорити?',
    'Я тут, щоб допомогти з будь-якими питаннями чи стурбованостями, які у вас є. Чи є щось конкретне, про що ви хотіли б запитати чи поговорити?',
  ],
  [VoiceflowConstants.Language.VI]: [
    'Tôi xin lỗi, tôi không nhận được phản hồi. Bạn có thể cho tôi biết làm thế nào để tôi có thể hỗ trợ bạn không?',
    'Tôi xin lỗi nếu tin nhắn trước của tôi không rõ ràng. Bạn có thể cho tôi biết bạn cần giúp đỡ với vấn đề gì không?',
    'Có vẻ như tôi không nhận được phản hồi từ bạn. Bạn có điều gì cụ thể mà bạn muốn biết hoặc thảo luận?',
    'Tôi ở đây để giúp đỡ bất kỳ câu hỏi hoặc lo ngại nào bạn có. Có điều gì bạn muốn hỏi hoặc thảo luận về không?',
    'Tôi xin lỗi nếu tôi đã bỏ sót phản hồi của bạn. Có điều gì bạn muốn biết hoặc thảo luận không?',
    'Tôi ở đây để hỗ trợ bạn với bất kỳ câu hỏi hoặc lo ngại nào. Có điều gì bạn muốn hỏi tôi không?',
    'Tôi xin lỗi nếu tin nhắn trước của tôi không hữu ích. Có điều gì khác bạn muốn biết hoặc thảo luận không?',
    'Tôi xin lỗi nếu tin nhắn trước của tôi gây nhầm lẫn. Bạn có thể cho tôi biết bạn cần giúp đỡ với vấn đề gì không?',
    'Tôi không nhận được phản hồi từ bạn. Có điều gì cụ thể mà bạn muốn biết hoặc thảo luận không?',
    'Tôi ở đây để giúp đỡ bất kỳ câu hỏi hoặc lo ngại nào bạn có. Có điều gì cụ thể mà bạn muốn hỏi hoặc thảo luận về không?',
  ],
} as const;

export const DEFAULT_BUILT_IN_NO_REPLIES = BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.EN];

export const BUILT_IN_NO_REPLIES_BY_LOCALE: Partial<Record<VoiceflowConstants.Locale, readonly string[]>> = {
  [VoiceflowConstants.Locale.EN_US]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.EN],
  [VoiceflowConstants.Locale.AR_AR]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.AR],
  [VoiceflowConstants.Locale.BG_BG]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.BG],
  [VoiceflowConstants.Locale.CA_ES]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.CA],
  [VoiceflowConstants.Locale.CS_CZ]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.CS],
  [VoiceflowConstants.Locale.ZH_TW]: [
    '很抱歉，我沒有收到回應。您能告訴我如何協助您嗎？',
    '如果我之前的訊息不清楚，我深感抱歉。您能告訴我您需要什麼幫助嗎？',
    '看起來我沒有收到您的回覆。您是否有特定的事情想要知道或討論？',
    '我在這裡，可以回答您任何問題或疑慮。您有任何想要詢問或討論的事嗎？',
    '如果我錯過了您的回覆，深感抱歉。您是否有任何想要知道或討論的事情？',
    '我在這裡協助您處理任何問題或疑慮。您有任何想要詢問我的事情嗎？',
    '如果我之前的訊息沒有幫助，我深感抱歉。您是否有其他想要知道或討論的事情？',
    '如果我之前的訊息令人困惑，您能告訴我您需要什麼幫助嗎？',
    '我沒有收到您的回應。您是否有特定的事情想要知道或討論？',
    '我在這裡，可以回答您任何問題或疑慮。您是否有特定的事情想要詢問或討論？',
  ],
  [VoiceflowConstants.Locale.ZH_CN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.ZH],
  [VoiceflowConstants.Locale.DA_DK]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.DA],
  [VoiceflowConstants.Locale.NL_NL]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.NL],
  [VoiceflowConstants.Locale.NL_BE]: [
    'Het spijt me, ik heb geen antwoord ontvangen. Kun je me alsjeblieft laten weten hoe ik je kan helpen?',
    'Mijn verontschuldigingen als mijn vorig bericht onduidelijk was. Kun je me alsjeblieft laten weten waarmee je hulp nodig hebt?',
    'Het lijkt erop dat ik geen antwoord van je heb ontvangen. Is er iets specifieks dat je zou willen weten of bespreken?',
    'Ik ben hier om te helpen met alle vragen of zorgen die je hebt. Is er iets dat je zou willen vragen of bespreken?',
    'Mijn verontschuldigingen als ik je antwoord gemist heb. Is er iets dat je zou willen weten of bespreken?',
    'Ik ben hier om je te helpen met alle vragen of zorgen. Is er iets dat je mij zou willen vragen?',
    'Het spijt me als mijn vorig bericht niet nuttig was. Is er nog iets anders dat je zou willen weten of bespreken?',
    'Mijn verontschuldigingen als mijn vorig',
  ],
  [VoiceflowConstants.Locale.ET_EE]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.ET],
  [VoiceflowConstants.Locale.FR_FR]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.FR],
  [VoiceflowConstants.Locale.DE_DE]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.DE],
  [VoiceflowConstants.Locale.HE_IL]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.HE],
  [VoiceflowConstants.Locale.HI_IN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.HI],
  [VoiceflowConstants.Locale.HU_HU]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.HU],
  [VoiceflowConstants.Locale.IT_IT]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.IT],
  [VoiceflowConstants.Locale.JA_JP]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.JA],
  [VoiceflowConstants.Locale.KO_KR]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.KO],
  [VoiceflowConstants.Locale.MR_IN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.MR],
  [VoiceflowConstants.Locale.PT_BR]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.PT],
  [VoiceflowConstants.Locale.PT_PT]: [
    'Peço desculpa, não recebi uma resposta. Pode informar-me por favor como posso ajudar?',
    'Peço desculpa se a minha mensagem anterior não foi clara. Poderia informar-me sobre o que precisa de ajuda?',
    'Parece que não recebi uma resposta da sua parte. Há algo específico que gostaria de saber ou discutir?',
    'Estou aqui para ajudar com quaisquer perguntas ou preocupações que tenha. Há algo que gostaria de perguntar ou discutir?',
    'Peço desculpa se perdi a sua resposta. Há algo que gostaria de saber ou discutir?',
    'Estou aqui para ajudar com quaisquer perguntas ou preocupações. Há algo que gostaria de me perguntar?',
    'Lamento se a minha mensagem anterior não foi útil. Há algo mais que gostaria de saber ou discutir?',
    'Peço desculpa se a minha mensagem anterior foi confusa. Poderia informar-me sobre o que precisa de ajuda?',
    'Não recebi uma resposta da sua parte. Há algo específico que gostaria de saber ou discutir?',
    'Estou aqui para ajudar com quaisquer perguntas ou preocupações que tenha. Há algo específico que gostaria de perguntar ou discutir?',
  ],
  [VoiceflowConstants.Locale.PL_PL]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.PL],
  [VoiceflowConstants.Locale.RO_RO]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.RO],
  [VoiceflowConstants.Locale.RU_RU]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.RU],
  [VoiceflowConstants.Locale.ES_ES]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.ES],
  [VoiceflowConstants.Locale.ES_MX]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.ES],
  [VoiceflowConstants.Locale.TA_IN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.TA],
  [VoiceflowConstants.Locale.TE_IN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.TE],
  [VoiceflowConstants.Locale.TR_TR]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.TR],
  [VoiceflowConstants.Locale.UK_UA]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.UK],
  [VoiceflowConstants.Locale.VI_VN]: BUILT_IN_NO_REPLIES_BY_LANGUAGE[VoiceflowConstants.Language.VI],

  [VoiceflowConstants.Locale.FR_CA]: [
    "Désolé, j'ai pas tout compris ce que tu voulais dire. Pourrais-tu reformuler ta question ou ta demande, s'il te plaît ?",
    "Pourrais-tu fournir plus de contexte ou préciser ta question, s'il te plaît ?",
    "J'ai de la misère à comprendre ton message. Pourrais-tu le reformuler de manière différente, s'il te plaît ?",
    "Désolé, mais je suis pas sûr de ce que tu me demandes. Pourrais-tu développer ou donner plus de détails, s'il te plaît ?",
    "Pourrais-tu fournir plus d'informations ou préciser ta question, s'il te plaît ? Je suis pas sûr de comprendre ce que tu me demandes.",
    "Désolé, j'ai pas compris ton message. Pourrais-tu l'expliquer de manière différente, s'il te plaît ?",
    "J'ai de la misère à suivre ta question. Pourrais-tu donner plus de détails ou la reformuler, s'il te plaît ?",
    "Désolé, mais je suis pas sûr de ce que tu veux dire. Pourrais-tu l'expliquer de manière différente, s'il te plaît ?",
    "Pourrais-tu préciser ta question ou fournir plus d'informations, s'il te plaît ? J'arrive pas à comprendre ce que tu me demandes.",
    "Désolé, j'ai pas compris ton message. Pourrais-tu le reformuler ou fournir plus de contexte, s'il te plaît ?",
  ],
};
