export enum Identifier {
  DESIGN_MENU = 'vf-design-menu',
  FLOW_MENU = 'vf-flow-menu',
  STEP_MENU = 'vf-step-menu',
  RESOURCE_MENU = 'vf-resource-menu',
  PROTOTYPE = 'vf-prototype',
  PROTOTYPE_RESET = 'vf-prototype__reset',
  PROTOTYPE_RESPONSE = 'vf-prototype__response',
  UPLOAD = 'vf-upload',
  PROJECT_TITLE = 'vf-project-title',
  CANVAS = 'vf-canvas',
  BLOCK_EDITOR = 'vf-block-editor',
  CANVAS_HOME_BUTTON = 'vf-canvas__home-button',
  ADD_COLLABORATORS = 'vf-add-collaborators',
}

export enum ClassName {
  BUTTON = 'vf-button',
  TABS = 'vf-tabs',
  TAB = 'vf-tab',
  LOADER = 'vf-loader',
  MENU = 'vf-menu',
  MENU_ITEM = 'vf-menu__item',
  TEXT_EDITOR = 'vf-text-editor',
  SSML_PLAY_AUDIO = 'vf-ssml__play-audio',
  CANVAS_EDITOR = 'vf-canvas__editor',
  CANVAS_NODE = 'vf-canvas__node',
  CANVAS_BLOCK = 'vf-canvas__block',
  CANVAS_STEP = 'vf-canvas__step',
  CANVAS_PORT = 'vf-canvas__port',
  CANVAS_LINK = 'vf-canvas__link',
  FLOW_MENU_ITEM = 'vf-flow-menu__item',
  STEP_MENU_ITEM = 'vf-step-menu__item',
  DROPDOWN = 'vf-dropdown',
}
