export type Charge = {
  amount: number;
  amount_captured: number;
  amount_refunded: number;
  application: null;
  application_fee: null;
  application_fee_amount: null;
  balance_transaction: string;
  billing_details: {
    address: any;
  };
  calculated_statement_descriptor: string;
  captured: boolean;
  created: number;
  currency: string;
  customer: string;
  description: string;
  destination: null;
  dispute: null;
  disputed: boolean;
  failure_code: null;
  failure_message: null;
  fraud_details: any;
  id: string;
  invoice: string;
  livemode: boolean;
  metadata: any;
  object: string;
  on_behalf_of: null;
  order: null;
  outcome: any;
  paid: true;
  payment_intent: string;
  payment_method: string;
  payment_method_details: { card: any; type: string };
  receipt_email: string;
  receipt_number: null;
  receipt_url: string;
  refunded: boolean;
  refunds: any;
  review: null;
  shipping: null;
  source: { id: string; object: string; amount: number | null };
  source_transfer: null;
  statement_descriptor: null;
  statement_descriptor_suffix: null;
  status: string;
  transfer_data: null;
  transfer_group: null;
};
