export enum LimitType {
  DOMAINS = 'DOMAINS',
  PROJECTS = 'PROJECTS',
  NLU_IMPORT = 'NLU_IMPORT',
  MARKUP_IMAGE = 'MARKUP_IMAGE',
  MARKUP_VIDEO = 'MARKUP_VIDEO',
  VARIABLE_STATES = 'VARIABLE_STATES',
}
