export enum Identifier {
  TEST = 'vf-test',
  DESIGN_MENU = 'vf-design-menu',
  STEP_MENU = 'vf-step-menu',
  RESOURCE_MENU = 'vf-resource-menu',
  MARKUP_MENU = 'vf-markup-menu',
  PROTOTYPE = 'vf-prototype',
  PROTOTYPE_START = 'vf-prototype__start',
  PROTOTYPE_RESET = 'vf-prototype__reset',
  PROTOTYPE_RESPONSE = 'vf-prototype__response',
  PROTOTYPE_RESPONSE_SEND = 'vf-prototype__response_send',
  UPLOAD = 'vf-upload',
  HEADER_BACK = 'vf-header-back',
  PROJECT_TITLE = 'vf-project-title',
  CANVAS = 'vf-canvas',
  CANVAS_OFFSET = 'vf-canvas-offset',
  CANVAS_CONTAINER = 'vf-canvas-container',
  BLOCK_EDITOR = 'vf-block-editor',
  ADD_COLLABORATORS = 'vf-add-collaborators',
  THREAD_HISTORY_DRAWER = 'vf-thread-history-drawer',
  SPOTLIGHT = 'vf-spotlight',
  UPGRADE_BUTTON = 'vf-upgrade-button',
  PAYMENT_DETAILS_SECTION = 'vf-payment-details-section',
  PAYMENT_UPGRADE_BUTTON = 'vf-payment-upgrade-button',
  PAYMENT_MODAL_BILLING_CYCLE_DROPDOWN = 'vf-payment-modal-billing-cycle-dropdown',
  PAYMENT_SEATS_INPUT = 'vf-input-seats-input',
  COLLAB_SEND_INVITE_BUTTON = 'vf-collab-invite-button',
  MEMBERS_CONTAINER = 'vf-members-container',
  COPY_INVITE_BUTTON = 'vf-copy-invite-button',
  UPGRADE_PLAN_SECTION = 'vf-upgrade-plan-section',
  PAYMENT_MODAL_UNIT_COST_CONTAINER = 'vf-payment-modal-unit-cost-conatiner',
  CONTEXT_MENU = 'vf-context-menu',
  DESIGN_TAB = 'vf-design-tab',
  LAUNCH_TAB = 'vf-launch-tab',
  SETTINGS_PAGE = 'vf-settings-page',
  ACCOUNT_PAGE = 'vf-account-page',
  TEST_TYPE_SELECTOR = 'vf-test-type-selector',
  SHARE_BUTTON = 'vf-share-button',
  SHARE_COPY_LINK_BUTTON = 'vf-share-link-button',
  SPEECH_BAR = 'vf-speech-bar',
  APPEARANCE_AND_BRANDING_DD = 'vf-appearance-and-branding-dd',
  PROTOTYPE_PASSWORD_DD = 'vf-prototype-password-dd',
  BRAND_IMAGE_INPUT_CONTAINER = 'vf-brand-image-input-container',
  MESSAGE_ICON_INPUT_CONTAINER = 'vf-message-icon-input-container',
  PUBLIC_SHARE_PROTOTYPE_IMAGE = 'vf-public-share-prototype-image',
  PROTO_MENU_DISPLAY_BUTTON = 'vf-proto-menu-display-button',
  PROTO_MENU_DEVELOPER_BUTTON = 'vf-proto-menu-developer-button',
  PROTO_MENU_SETTINGS_BUTTON = 'vf-proto-menu-settings-button',
  PROTO_MENU_CANVAS_BUTTON = 'vf-proto-menu-canvas-button',

  VERIFY_EMAIL_TITLE = 'vf-verify-email-title',

  DISPLAY_CANVAS_CONTAINER = 'vf-display-canvas-container',
  PROTO_VARIABLES_MENU_CONTAINER = 'vf-proto-variables-menu-container',
  PROTO_SETTINGS_MENU_CONTAINER = 'vf-proto-settings-menu-container',
  NEW_PROJECT_NAME_INPUT = 'vf-project-name-input',
  NEW_PROJECT_BUTTON = 'vf-new-project-button',
  NEW_PROJECT_ICON_UPLOAD_CONTAINER = 'vf-new-project-icon-upload-container',

  // Project Creation
  PROJECT_CREATION_STEP_TITLE = 'vf-project-creation-step-title',
  INVOCATION_NAME_INPUT = 'vf-invocation-name-input',
  PROJECT_CREATE_SELECT_CHANNEL = 'vf-project-create__select--channel',
  PROJECT_CREATE_SELECT_NLU = 'vf-project-create__select--nlu',
  PROJECT_CREATE_SELECT_LOCALE = 'vf-project-create__select--locale',
  PROJECT_CREATE_SELECT_MODALITY = 'vf-project-create__select--modality',
  PROJECT_CREATE_SELECT_MULTIPLE_LOCALES = 'vf-project-create__select--multiple-locale',

  // Transcripts
  SAVE_TRANSCRIPT_BUTTON = 'vf-save-conversations-button',
  DELETE_TRANSCRIPT_BUTTON = 'vf-delete-transcript-button',
  MARK_AS_REVIEWED_TRANSCRIPT_BUTTON = 'vf-mark-reviewed-transcript-button',
  SAVE_FOR_LATER_TRANSCRIPT_BUTTON = 'vf-save-for-later-transcript-button',
  EMPTY_TRANSCRIPTS_CONTAINER = 'vf-empty-transcripts-container',
  EMPTY_REPORTS_CONTAINER = 'vf-empty-reports-container',
  CONVERSATIONS_PAGE = 'vf-conversations-container',

  NEW_LINK = 'vf-new-link',

  // Account Page

  USER_NAME_INPUT = 'vf-user-name-input',
  USER_EMAIL_INPUT = 'vf-user-email-input',
}

export enum ClassName {
  INPUT_GROUP = 'vf-input-group',
  BUTTON = 'vf-button',
  TABS = 'vf-tabs',
  TAB = 'vf-tab',
  LOADER = 'vf-loader',
  MENU = 'vf-menu',
  MENU_ITEM = 'vf-menu__item',
  TEXT_EDITOR = 'vf-text-editor',
  SSML = 'vf-ssml',
  TOOLTIP = 'vf-tooltip',
  SSML_PLAY_AUDIO = 'vf-ssml__play-audio',
  CANVAS_EDITOR = 'vf-canvas__editor',
  CANVAS_NODE = 'vf-canvas__node',
  CANVAS_THREAD = 'vf-canvas__thread',
  CANVAS_CHIP = 'vf-canvas__chip',
  CANVAS_BLOCK = 'vf-canvas__block',
  CANVAS_STEP = 'vf-canvas__step',
  CANVAS_STEP_ITEM = 'vf-canvas__step-item',
  CANVAS_STEP_ITEM_LABEL = 'vf-canvas__step-item-label',
  CANVAS_PORT = 'vf-canvas__port',
  CANVAS_LINK = 'vf-canvas__link',
  CANVAS_CONTROL = 'vf-canvas__control',
  STEP_MENU_ITEM = 'vf-step-menu__item',
  SUB_STEP_MENU = 'vf-sub-step-menu',
  SUB_STEP_MENU_ITEM = 'vf-sub-step-menu__item',
  DROPDOWN = 'vf-dropdown',
  SVG_ICON = 'vf-svg-icon',
  MODAL = 'vf-modal',
  THREAD_EDITOR = 'vf-thread-editor',
  THREAD_EDITOR_REPLY = 'vf-thread-editor__reply',
  THREAD_EDITOR_NEW = 'vf-thread-editor--new',
  THREAD_EDITOR_COMMENT = 'vf-thread-editor__comment-editor',
  THREAD_INDICATOR = 'vf-canvas__thread__indicator',
  COLLABORATOR_LINE_ITEM = 'vf-collaborator-line-item',
  INVITE_ROLE_BUTTON = 'vf-invite-role-button',
  MEMBER_ROLE_BUTTON = 'vf-member-role-button',
  LINK_SETTINGS = 'vf-link-settings',
  TEST_TYPE_OPTION = 'vf-test-type-option',
  PRIMARY_NAV = 'vf-header_primary-nav',
  SECONDARY_NAV = 'vf-header_secondary-nav',
  HEADER_ACTIONS_CENTER = 'vf-header_primary-nav__center',
  HEADER_ACTIONS_RIGHT = 'vf-header_primary-nav__right',
  HEADER_USER_MENU = 'vf-header_user-menu',
  SVG_ICON_CLOSE = 'vf-svg-icon--close',
  HOME_CHIP = 'vf-canvas__chip--home',
  MENTION_INPUT = 'mentionInput',
  CHAT_DIALOG_MESSAGE = 'vf-chat-dialog__message',
  CHAT_DIALOG_LOADING_MESSAGE = 'vf-chat-dialog__message--loading',
  CHAT_DIALOG_SPEAK_MESSAGE = 'vf-chat-dialog__message--speak',
  VISUAL = 'vf-visual',
  VISUAL_IMAGE = 'vf-visual--image',
  VISUAL_APL = 'vf-visual--apl',
  PROTOTYPE_MESSAGE_ICON = 'vf-prototype-message-icon',
  EDITOR_FOOTER_BUTTON = 'vf-editor-footer-button',
  INTENT_SELECT_INPUT = 'vf-intent-select-input',
  PROTOTYPE_BUTTON = 'vf-prototype-button',
  DISPLAY_TYPE_ITEM = 'vf-display-type-item',
  SCALE_CONTAINER = 'vf-scale-container',
  PLATFORM_CARD = 'vf-platform-card',
  MULTISELECT_DROPDOWN = 'vf-multi-select-dropdown',
  MULTISELECT_ITEM = 'vf-multi-select-item',
  MULTISELECT_SELECTED_VALUE = 'vf-multi-select-selected-value',
  COLLAPSE = 'vf-collapse',
  COLLAPSE_HEADER = 'vf-collapse__header',
  COLLAPSE_CONTENT = 'vf-collapse__content',
  // Project Creation
  CREATE_PROJECT_LEFT_ACTION = 'vf-create-project-left-action',
  CREATE_PROJECT_RIGHT_ACTION = 'vf-create-project-right-action',

  TRANSCRIPT_FILTERS_TAGS_INPUT = 'vf-transcripts-filters-tags-input',
  TRANSCRIPT_FILTERS_DATE_CHECKBOX = 'vf-transcripts-filters-date-checkbox',
  TRANSCRIPT_FILTERS_TAGS_CHECKBOX = 'vf-transcripts-filters-tags-checkbox',
  TRANSCRIPT_FILTERS_MENU_APPLY_BUTTON = 'vf-transcripts-filters-menu-apply-button',
  TRANSCRIPT_FILTERS_MENU_TEXT = 'vf-transcript-filters-menu-text',
  TRANSCRIPT_ITEM = 'vf-transcript-item',
  TRANSCRIPT_ITEM_DROPDOWN_BUTTON = 'vf-transcript-item-dropdown-item',
  TRANSCRIPT_ITEM_STATUSES = 'vf-transcript-item-statuses',
  TRANSCRIPT_USER_NAME = 'vf-transcript-user-name',
  TRANSCRIPT_CONTEXT_META = 'vf-transcript-context-meta',
  TRANSCRIPT_DIALOG_LOADING = 'vf-transcript-dialog--loading',
  TRANSCRIPT_LOADING = 'vf-transcript-page--loading',
  TRANSCRIPT_DATE = 'vf-conversations-transcript-date',
  MARK_AS_REVIEWED_CONTAINER = 'vf-mark-as-reviewed-container',
  SAVED_FOR_LATER_CONTAINER = 'vf-saved-for-later-container',
  BASE_REPORT_TAG_INPUT = 'vf-conversations-report-tag-input',
  TRANSCRIPT_ITEM_META = 'vf-conversations-transcript-meta',
  DELETE_TAG_BUTTON = 'vf-conversations-delete-tag-button',
  TAG_MODAL_INPUT_FIELD = 'vf-conversations-tag-input-field',

  SIDEBAR_ICON_MENU = 'vf-sidebar-icon-menu',
  SIDEBAR_ICON_MENU_ITEM = 'vf-sidebar-icon-menu__item',

  POPPER = 'vf-popper',
  POPPER_NAV_ITEM = 'vf-popper__nav_item',

  BASE_REPORT_TAG_INPUT_ICON = 'vf-base-report-tag-input-icon',

  FORMS_MULTIPLE_BUTTON = 'vf-forms-multiple-button',

  RADIO_GROUP = 'vf-radio-group',
  RADIO_GROUP_ITEM = 'vf-radio-group__item',

  COLOR_INPUT = 'vf-color-input',
}

export enum DashboardClassName {
  DASHBOARD = 'dashboard',
  LISTS_CONTAINER = 'board-container-body',
  LISTS_CONTAINER_INNER = 'board-container-body-inner',
  LISTS = 'main-lists',
  LISTS_INNER = 'main-lists-inner',
  LIST = 'main-list',
  LIST_DROPZONE = 'main-list-dropzone',
  LIST_DRAGZONE = 'main-list__dragzone',
  LIST_HEADER = 'main-list-header',
  LIST_HEADER_MAIN = 'main-list-header__main',
  LIST_HEADER_TITLE = 'main-list-header__title',
  LIST_HEADER_ASIDE = 'main-list-header__aside',
  LIST_FOOTER = 'main-list-footer',
  LIST_FOOTER_CENTER = 'main-list-footer-center',
  LIST_BODY = 'main-list-body',
  LIST_BODY_INNER = 'main-list-body-inner',
  PROJECT_LIST = 'project-list',
  PROJECT_LIST_ITEM = 'project-list__list-item',
  PROJECT_LIST_ITEM_TITLE = 'project-list__item-title',
  PROJECT_LIST_ITEM_ACTIONS = 'project-list__item-actions',
  PROJECT_LIST_ITEM_STATUS = 'project-list__item-status',
  ADD_LIST_BUTTON = 'list__add-button',
  PLAN_BUBBLE = 'vf-plan-bubble',
}
