server {
    listen 80;
    server_name _;

    root /var/www/;
    index index.html;

    # Force all paths to load either itself (js files) or go through index.html.

    location / {
        resolver 8.8.8.8;
        if ($http_user_agent ~* "googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|WhatsApp|Twitterbot|showyoubot|outbrain|vkShare|Slack-ImgProxy|Slackbot-LinkExpanding|Site Analyzer|SiteAnalyzerBot|Viber|Whatsapp|Telegram|developers.google.com/\+/web/snippet/|redditbot|Discordbot|W3C_Validator") {

            proxy_pass https://api.voiceflow.com/metadata?url=$uri$is_args$args;
        }
        try_files $uri /index.html;
    }

    location ~* \.(js|css|png|svg|jpg|jpeg|gif|ico)$ {
        expires 30m;
        add_header Cache-Control "public, no-transform";
    }
}
