export enum GoogleStageType {
  IDLE = 'IDLE',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  PROGRESS = 'PROGRESS',
  WAIT_ACCOUNT = 'WAIT_ACCOUNT',
  WAIT_PROJECT = 'WAIT_PROJECT',
}

export enum GooglePublishJobErrorType {
  RENDERING = 'RENDERING',
  ENABLING_SKILL = 'ENABLING_SKILL',
  SUBMITTING_PROJECT = 'SUBMITTING_PROJECT',
  SUBMITTING_FOR_REVIEW = 'SUBMITTING_FOR_REVIEW',
  CHECKING_INTERACTION_MODEL_STATUS = 'CHECKING_INTERACTION_MODEL_STATUS',
}
