export enum SMSPublishStageType {
  IDLE = 'IDLE',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  CHECK_API_SECRETS = 'CHECK_API_SECRETS',
  CHECK_MESSAGING_SERVICE = 'CHECK_MESSAGING_SERVICE',
  VALIDATE_NUMBERS = 'VALIDATE_NUMBERS',
  COMPILE = 'COMPILE',
  TRAIN_NLP = 'TRAIN_NLP',
}
