export const PASSWORD_NUMBER_REGEX = /\d+/;
export const PASSWORD_ELEVEN_CHAR_REGEX = /.{11,}/;
export const PASSWORD_SPECIAL_CHAR_REGEX = /[!#$%&()*+.=@^_-]+/;
export const PASSWORD_LOWERCASE_CHAR_REGEX = /[a-z]+/;
export const PASSWORD_UPPERCASE_CHAR_REGEX = /[A-Z]+/;

export const PASSWORD_REGEXES = [
  PASSWORD_NUMBER_REGEX,
  PASSWORD_ELEVEN_CHAR_REGEX,
  PASSWORD_LOWERCASE_CHAR_REGEX,
  PASSWORD_UPPERCASE_CHAR_REGEX,
  PASSWORD_SPECIAL_CHAR_REGEX,
];
