import type { ProjectAIAssistSettings } from '@voiceflow/dtos';
import React from 'react';

import { Permission } from '@/constants/permissions';
import { useActiveWorkspace } from '@/hooks';
import { useModal } from '@/hooks/modal.hook';
import { usePermission } from '@/hooks/permission';
import { useLocalStorageState } from '@/hooks/storage.hook';
import Disclaimer, { DisclaimerModalProps } from '@/ModalsV2/modals/Disclaimer';

const AI_PLAYGROUND_DISCLAIMER_DISCLAIMER: DisclaimerModalProps = {
  title: 'AI-enabled Technology Disclaimer',
  body: (
    <>
      <p>
        <strong>Here is a plain language summary of what the disclaimer below says, but please read the disclaimer before accepting.</strong>
      </p>
      <ul style={{ marginTop: 0 }}>
        <li>Voiceflow's AI features are powered by third party vendors like OpenAI with large language models like ChatGPT that generate content</li>
        <li>
          Voiceflow doesn't control the content generated by the AI features, so Voiceflow won't be responsible for inaccurate or offensive content
          given to end-users
        </li>
        <li>You're responsible for all input and content provided to the AI features by you or your end-users</li>
        <li>Make sure your use of the AI features is in compliance with your organization's policies and requirements</li>
        <li>You're responsible for all testing before deploying</li>
        <li>But most of all - Have fun!</li>
      </ul>
      <p>
        <br />
        <strong>
          BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF ARTIFICIAL INTELLIGENCE
          TECHNOLOGY AND FEATURES ENABLED ON VOICEFLOW (“AI-ENABLED TECHNOLOGY”), YOU AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE FOLLOWING
          DISCLAIMER.
        </strong>
      </p>
      <p>
        <strong>Voiceflow AI-Enabled Technology Disclaimer</strong>
      </p>
      <p>
        <strong>(the “Disclaimer”)</strong>
      </p>
      <p>
        The Voiceflow artificial intelligence technology and features, if enabled, automatically generates content (via OpenAI's GPT language model)
        and communicates such content to you and your “<strong>end user(s)</strong>” (including, without limitation, your customers, employees,
        personnel, contractors, or other third parties) upon specific events and interactions with your end users (i) on Voiceflow's platform (without
        limitation, internal testing and prototyping) or (ii) in a production environment (without limitation, your organization's, product's, or
        website's chatbot or conversation channel with customers) (the “<strong>AI-Enabled Technology</strong>”).
      </p>
      <p>
        By enabling the AI-Enabled Technology via creation of an AI Assistant, or otherwise on the Voiceflow platform, you and your organization
        (collectively, “<strong>you</strong>” and “<strong>your</strong>”) acknowledge and agree to the following principles:
      </p>
      <ol style={{ marginTop: 0 }}>
        <li>
          Use of the AI-Enabled Technology and any reliance on the content generated by AI-Enabled Technology is SOLELY AT YOUR OWN RISK AND YOU
          ASSUME ALL RISKS AND COSTS WITH THE USE OF THE AI-ENABLED TECHNOLOGY.
          <br />
          <br />
        </li>

        <li>
          <strong>
            The content provided by the AI-Enabled Technology is provided directly and automatically by OpenAI's GPT language model and Voiceflow does
            not control how such content is generated or communicated. You acknowledge
          </strong>
          <strong>that the AI-Enabled Technology</strong>
          <strong>could generate content that could be offensive to you or your end-users.</strong>
          <br />
          <br />
        </li>

        <li>
          NOTWITHSTANDING ANYTHING TO THE CONTRARY, VOICEFLOW SHALL BEAR NO LIABILITY WHATSOEVER FOR (i) USE OF THE AI-ENABLED TECHNOLOGY; (ii) ITS
          CONTENT; AND (iii) ANY AND ALL INACCURACIES, ERRORS, OMISSIONS AND PROBLEMS OF THE CONTENT GENERATED BY THE AI-ENABLED TECHNOLOGY.
          <br />
          <br />
        </li>

        <li>
          The AI-Enabled Technology is an experimental technology; THE AI-ENABLED TECHNOLOGY AND ALL CONTENT PROVIDED BY IT ARE PROVIDED ON AN “AS-IS”
          AND “AS AVAILABLE” BASIS. VOICEFLOW DOES NOT GIVE ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, AS TO (i) THE SUITABILITY OR USABILITY OF THE
          AI-ENABLED TECHNOLOGY OR ANY OF ITS CONTENT; OR (ii) THE ACCURACY, ADEQUACY, VALIDITY, RELIABILITY, AVAILABILITY OR COMPLETENESS OF ANY
          CONTENT GENERATED BY THE AI-ENABLED TECHNOLOGY.
          <br />
          <br />
        </li>

        <li>
          YOU SHALL BE RESPONSIBLE FOR THE COMMUNICATION OF ANY DISCLAIMERS TO YOUR END USERS REGARDING THE NATURE, RELIANCE ON, AND RISKS ASSOCIATED
          WITH THE USE OF THE AI-ENABLED TECHNOLOGY AND THE CONTENT GENERATED BY THE AI-ENABLED TECHNOLOGY, INCLUDING ANY DISCLAIMER RELATING TO THE
          DISCLOSURE OF ANY PERSONAL INFORMATION.
          <br />
          <br />
        </li>

        <li>
          The use of the AI-Enabled Technology may require the disclosure of your end-user data (which may include personal information) to OpenAI's
          GPT language model (the “<strong>End-User Data</strong>”).
          <strong>
            {' '}
            You understand that you shall be fully responsible for the use of the AI-Enabled Technology, including any End-User Data that you or your
            end-users may disclose to the AI-Enabled Technology. To the extent permitted by applicable law, Voiceflow shall have no liability
            whatsoever for End-User Data (including personal information) that you choose to submit, integrate with, access, or otherwise process
            through the AI-Enabled Technology.
          </strong>
          <br />
          <br />
        </li>

        <li>
          You acknowledge that End-User Data containing personal information is not intended to be used with AI-Enabled Technology and that any such
          input shall be at your own risk and you shall be fully responsible for any such End-User Data.
          <br />
          <br />
        </li>

        <li>
          Yourepresent and warrant to, and covenant with Voiceflow that in the event that your end-users provide any End-User Data to and for use with
          the AI-Enabled Technology, such End-User Data will only contain Personal Information in respect of which you have provided all notices and
          disclosures, obtained all applicable third party consents and permissions and otherwise has all authority, in each case as required by
          applicable laws, to enable the use of the AI-Enabled Technology, including with respect to the collection, storage, access, use, disclosure,
          processing and transmission of personal information, including to or from all applicable third parties.
          <br />
          <br />
        </li>

        <li>
          The AI-Enabled Technology may contain errors, design flaws, vulnerabilities, performance issues, bugs or other problems.
          <br />
          <br />
        </li>

        <li>
          Voiceflow provides no assurance that any specific errors or discrepancies in the AI-Enabled Technology will be corrected.
          <br />
          <br />
        </li>

        <li>
          Any and all content provided by the AI-Enabled Technology is NOT intended to be relied on for any reason whatsoever (including, without
          limitation, for any reason regarding medical advice, financial advice, technical advice, training and educational purposes, or advice of any
          type). The AI-Enabled Technology is no substitute for the advice of a professional, who should be consulted in all cases, where a
          professional is required.
          <br />
          <br />
        </li>

        <li>
          You are responsible for the entirety of testing the AI-Enabled Technology.
          <br />
          <br />
        </li>

        <li>
          You acknowledge and agree that you are fully responsible for ensuring that all content generated by your use of the AI-Enabled Technology
          complies with (i) applicable laws, and (ii) you and your organization's requirements for any applicable intellectual property rights and
          ownership.{' '}
          <strong>
            Voiceflow assumes no liability whatsoever for any losses or damages arising from intellectual property registration issues or intellectual
            property infringement as a result of the content generated by your use of the AI-Enabled Technology.
          </strong>
          <br />
          <br />
        </li>
      </ol>

      <p>
        <strong>
          BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE AI-ENABLED TECHNOLOGY,
          YOU AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE DISCLAIMER.
        </strong>
      </p>
    </>
  ),
};

export const useGetAIAssistSettings = () => {
  const settings = { aiPlayground: true };
  const workspace = useActiveWorkspace();
  const disclaimerModal = useModal(Disclaimer);
  const aiPlaygroundDisclaimer = usePermission(Permission.FEATURE_AI_PLAYGROUND_DISCLAIMER);
  const [allowedForWorkspace, setAllowedForWorkspace] = useLocalStorageState(`ai_assist_${workspace?.id}`, false);

  return async ({ disclaimer } = { disclaimer: true }): Promise<ProjectAIAssistSettings | null> => {
    if (allowedForWorkspace) {
      return settings;
    }

    if (!disclaimer && aiPlaygroundDisclaimer.allowed) {
      return null;
    }

    if (aiPlaygroundDisclaimer.allowed && !(await disclaimerModal.openVoid(AI_PLAYGROUND_DISCLAIMER_DISCLAIMER))) {
      return null;
    }

    if (!allowedForWorkspace && workspace?.id) {
      setAllowedForWorkspace(true);
    }

    return settings;
  };
};
