import React from 'react';

import { DisclaimerModalProps } from '@/ModalsV2/modals/Disclaimer';

export const GENERATE_NO_MATCH_DISCLAIMER: DisclaimerModalProps = {
  title: 'Generate No Match Feature Disclaimer',
  body: (
    <>
      <b>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE GENERATE NO MATCH FEATURE
        (FORMERLY THE FREESTYLE FEATURE), YOU AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE FOLLOWING DISCLAIMER.
      </b>
      <br />
      <br />
      <b>
        Voiceflow Generate No Match Feature Disclaimer
        <br />
        (the “Disclaimer”)
      </b>
      <br />
      <br />
      <>
        The Voiceflow Generate No Match (formerly the Freestyle Feature), if enabled, automatically generates content (via OpenAI’s GPT-3 language
        model) and communicates such content to your <b>“end user(s)”</b> (including, without limitation, your customers, employees, personnel,
        contractors, or other third parties) upon specific events and interactions with your end users (i) on Voiceflow’s platform (without
        limitation, internal testing and prototyping) or (ii) in a production environment (without limitation, your organization’s, product’s, or
        website’s chatbot or conversation channel with customers) (the <b>“Generate No Match Feature”</b>).
        <br />
        <br />
        By enabling the Generate No Match Feature, you and your organization (collectively, “<b>you</b>” and “<b>your</b>”) acknowledge and agree to
        the following principles:
      </>
      <br />
      <br />
      <>
        1. Use of the Generate No Match Feature and any reliance on the content generated by Generate No Match Feature is SOLELY AT YOUR OWN RISK AND
        YOU ASSUME ALL RISKS AND COSTS WITH THE USE OF THE GENERATE NO MATCH FEATURE.
      </>
      <br />
      <br />
      <>
        2.{' '}
        <b>
          The content provided by the Generate No Match Feature is provided directly and automatically by OpenAI’s GPT-3 language model and Voiceflow
          does not control how such content is generated or communicated. You acknowledge that the Generate No Match Feature could generate content
          that could be offensive to you or your end-users.
        </b>
      </>
      <br />
      <br />
      <>
        3. NOTWITHSTANDING ANYTHING TO THE CONTRARY, VOICEFLOW SHALL BEAR NO LIABILITY WHATSOEVER FOR (i) USE OF THE GENERATE NO MATCH FEATURE; (ii)
        ITS CONTENT; AND (iii) ANY AND ALL INACCURACIES, ERRORS, OMISSIONS AND PROBLEMS OF THE CONTENT GENERATED BY THE GENERATE NO MATCH FEATURE.
      </>
      <br />
      <br />
      <>
        4. The Generate No Match Feature is an experimental technology; THE GENERATE NO MATCH FEATURE AND ALL CONTENT PROVIDED BY IT ARE PROVIDED ON
        AN “AS-IS” AND “AS AVAILABLE” BASIS. VOICEFLOW DOES NOT GIVE ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, AS TO (i) THE SUITABILITY OR
        USABILITY OF THE GENERATE NO MATCH FEATURE OR ANY OF ITS CONTENT; OR (ii) THE ACCURACY, ADEQUACY, VALIDITY, RELIABILITY, AVAILABILITY OR
        COMPLETENESS OF ANY CONTENT GENERATED BY THE GENERATE NO MATCH FEATURE.
      </>
      <br />
      <br />
      <>
        5. YOU SHALL BE RESPONSIBLE FOR THE COMMUNICATION OF ANY DISCLAIMERS TO YOUR END USERS REGARDING THE NATURE, RELIANCE ON, AND RISKS ASSOCIATED
        WITH THE USE OF THE GENERATE NO MATCH FEATURE AND THE CONTENT GENERATED BY THE GENERATE NO MATCH FEATURE, INCLUDING ANY DISCLAIMER RELATING TO
        THE DISCLOSURE OF ANY PERSONAL INFORMATION.
      </>
      <br />
      <br />
      <>
        6. The use of the Generate No Match Feature may require the disclosure of your end-user data (which may include personal information) to
        OpenAI’s GPT-3 language model (the <b>“End-User Data”</b>).{' '}
        <b>
          You understand that you shall be responsible for the use of the Generate No Match Feature, including any End-User Data that you or your
          end-users may disclose to the Generate No Match Feature. To the extent permitted by applicable law, Voiceflow shall have no liability
          whatsoever for End-User Data (including personal information) that you choose to submit, integrate with, access, or otherwise process
          through the Generate No Match Feature.
        </b>
      </>
      <br />
      <br />
      <>
        7. You represent and warrant to, and covenant with Voiceflow that in the event that your end-users provide any End-User Data, such End-User
        Data will only contain Personal Information in respect of which you have provided all notices and disclosures, obtained all applicable third
        party consents and permissions and otherwise has all authority, in each case as required by applicable laws, to enable the use of the Generate
        No Match Feature, including with respect to the collection, storage, access, use, disclosure, processing and transmission of personal
        information, including by or to Voiceflow and to or from all applicable third parties.
      </>
      <br />
      <br />
      <>8. The Generate No Match Feature may contain errors, design flaws, vulnerabilities, performance issues, bugs or other problems.</>
      <br />
      <br />
      <>9. Voiceflow provides no assurance that any specific errors or discrepancies in the Generate No Match Feature will be corrected.</>
      <br />
      <br />
      <>
        10. Any and all content provided by the Generate No Match Feature is NOT intended to be relied on for any reason whatsoever (including,
        without limitation, for any reason regarding medical advice, financial advice, technical advice, training and educational purposes, or advice
        of any type). The Generate No Match Feature is no substitute for the advice of a professional, who should be consulted in all cases, where a
        professional is required.
      </>
      <br />
      <br />
      <>11. You are responsible for the entirety of testing the Generate No Match Feature.</>
      <br />
      <br />
      <b>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE GENERATE NO MATCH FEATURE
        (FORMERLY THE FREESTYLE FEATURE), YOU AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE DISCLAIMER.
      </b>
    </>
  ),
};

export const GENERATE_STEP_DISCLAIMER: DisclaimerModalProps = {
  title: 'Generate Step Feature Disclaimer',
  body: (
    <>
      <b>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE GENERATE STEP FEATURE, YOU
        AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE FOLLOWING DISCLAIMER.
      </b>
      <br />
      <br />
      <b>
        Voiceflow Generate Step Feature Disclaimer
        <br />
        (the “Disclaimer”)
      </b>
      <br />
      <br />
      <>
        The Voiceflow Generate Step, if enabled, automatically generates content (via OpenAI’s GPT-3 language model) and communicates such content to
        your <b>“end user(s)”</b> (including, without limitation, your customers, employees, personnel, contractors, or other third parties) upon
        specific events and interactions with your end users (i) on Voiceflow’s platform (without limitation, internal testing and prototyping) or
        (ii) in a production environment (without limitation, your organization’s, product’s, or website’s chatbot or conversation channel with
        customers) (the <b>“Generate Step Feature”</b>).
        <br />
        <br />
        By enabling the Generate Step Feature, you and your organization (collectively, “<b>you</b>” and “<b>your</b>”) acknowledge and agree to the
        following principles:
      </>
      <br />
      <br />
      <>
        1. Use of the Generate Step Feature and any reliance on the content generated by Generate Step Feature is SOLELY AT YOUR OWN RISK AND YOU
        ASSUME ALL RISKS AND COSTS WITH THE USE OF THE GENERATE STEP FEATURE.
      </>
      <br />
      <br />
      <>
        2.{' '}
        <b>
          The content provided by the Generate Step Feature is provided directly and automatically by OpenAI’s GPT-3 language model and Voiceflow does
          not control how such content is generated or communicated. You acknowledge that the Generate Step Feature could generate content that could
          be offensive to you or your end-users.
        </b>
      </>
      <br />
      <br />
      <>
        3. NOTWITHSTANDING ANYTHING TO THE CONTRARY, VOICEFLOW SHALL BEAR NO LIABILITY WHATSOEVER FOR (i) USE OF THE GENERATE STEP FEATURE; (ii) ITS
        CONTENT; AND (iii) ANY AND ALL INACCURACIES, ERRORS, OMISSIONS AND PROBLEMS OF THE CONTENT GENERATED BY THE GENERATE STEP FEATURE.
      </>
      <br />
      <br />
      <>
        4. The Generate Step Feature is an experimental technology; THE GENERATE STEP FEATURE AND ALL CONTENT PROVIDED BY IT ARE PROVIDED ON AN
        “AS-IS” AND “AS AVAILABLE” BASIS. VOICEFLOW DOES NOT GIVE ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, AS TO (i) THE SUITABILITY OR USABILITY
        OF THE GENERATE STEP FEATURE OR ANY OF ITS CONTENT; OR (ii) THE ACCURACY, ADEQUACY, VALIDITY, RELIABILITY, AVAILABILITY OR COMPLETENESS OF ANY
        CONTENT GENERATED BY THE GENERATE STEP FEATURE.
      </>
      <br />
      <br />
      <>
        5. YOU SHALL BE RESPONSIBLE FOR THE COMMUNICATION OF ANY DISCLAIMERS TO YOUR END USERS REGARDING THE NATURE, RELIANCE ON, AND RISKS ASSOCIATED
        WITH THE USE OF THE GENERATE STEP FEATURE AND THE CONTENT GENERATED BY THE GENERATE STEP FEATURE, INCLUDING ANY DISCLAIMER RELATING TO THE
        DISCLOSURE OF ANY PERSONAL INFORMATION.
      </>
      <br />
      <br />
      <>
        6. The use of the Generate Step Feature may require the disclosure of your end-user data (which may include personal information) to OpenAI’s
        GPT-3 language model (the <b>“End-User Data”</b>).{' '}
        <b>
          You understand that you shall be responsible for the use of the Generate Step Feature, including any End-User Data that you or your
          end-users may disclose to the Generate Step Feature. To the extent permitted by applicable law, Voiceflow shall have no liability whatsoever
          for End-User Data (including personal information) that you choose to submit, integrate with, access, or otherwise process through the
          Generate Step Feature.
        </b>
      </>
      <br />
      <br />
      <>
        7. You represent and warrant to, and covenant with Voiceflow that in the event that your end-users provide any End-User Data, such End-User
        Data will only contain Personal Information in respect of which you have provided all notices and disclosures, obtained all applicable third
        party consents and permissions and otherwise has all authority, in each case as required by applicable laws, to enable the use of the Generate
        Step Feature, including with respect to the collection, storage, access, use, disclosure, processing and transmission of personal information,
        including by or to Voiceflow and to or from all applicable third parties.
      </>
      <br />
      <br />
      <>8. The Generate Step Feature may contain errors, design flaws, vulnerabilities, performance issues, bugs or other problems.</>
      <br />
      <br />
      <>9. Voiceflow provides no assurance that any specific errors or discrepancies in the Generate Step Feature will be corrected.</>
      <br />
      <br />
      <>
        10. Any and all content provided by the Generate Step Feature is NOT intended to be relied on for any reason whatsoever (including, without
        limitation, for any reason regarding medical advice, financial advice, technical advice, training and educational purposes, or advice of any
        type). The Generate Step Feature is no substitute for the advice of a professional, who should be consulted in all cases, where a professional
        is required.
      </>
      <br />
      <br />
      <>11. You are responsible for the entirety of testing the Generate Step Feature.</>
      <br />
      <br />
      <b>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE GENERATE STEP FEATURE, YOU
        AND YOUR ORGANIZATION ACCEPT AND AGREE TO THE DISCLAIMER.
      </b>
    </>
  ),
};
