import React from 'react';

import { DisclaimerModalProps } from '@/ModalsV2/modals/Disclaimer';

export const GENERATE_NO_MATCH_DISCLAIMER: DisclaimerModalProps = {
  title: 'Freestyle Feature Disclaimer',
  body: (
    <>
      <strong>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE FREESTYLE FEATURE, YOU AND
        YOUR ORGANIZATION ACCEPT AND AGREE TO THE FOLLOWING DISCLAIMER.
      </strong>
      <br />
      <br />
      <strong>
        Voiceflow Freestyle Feature Disclaimer
        <br />
        (the “Disclaimer”)
      </strong>
      <br />
      <br />
      <>
        The Voiceflow Freestyle Feature, if enabled, automatically generates content (via OpenAI's GPT-3 language model) and communicates such content
        to your “<strong>end user(s)</strong>” (including, without limitation, your customers, employees, personnel, contractors, or other third
        parties) upon specific events and interactions with your end users (i) on Voiceflow's platform (without limitation, internal testing and
        prototyping) or (ii) in a production environment (without limitation, your organization's, product's, or website's chatbot or conversation
        channel with customers) (the “<strong>Freestyle Feature</strong>”).
        <br />
        <br />
        By enabling the Freestyle Feature, you and your organization (collectively, “<strong>you</strong>” and “<strong>your</strong>”) acknowledge
        and agree to the following principles:
      </>
      <br />
      <br />
      <>
        1. Use of the Freestyle Feature and any reliance on the content generated by Freestyle Feature is SOLELY AT YOUR OWN RISK AND YOU ASSUME ALL
        RISKS AND COSTS WITH THE USE OF THE FREESTYLE FEATURE.
      </>
      <br />
      <br />
      <>
        2.{' '}
        <strong>
          The content provided by the Freestyle Feature is provided directly and automatically by OpenAI's GPT-3 language model and Voiceflow does not
          control how such content is generated or communicated. You acknowledge that the Freestyle Feature could generate content that could be
          offensive to you or your end-users.
        </strong>
      </>
      <br />
      <br />
      <>
        3. NOTWITHSTANDING ANYTHING TO THE CONTRARY, VOICEFLOW SHALL BEAR NO LIABILITY WHATSOEVER FOR (i) USE OF THE FREESTYLE FEATURE; (ii) ITS
        CONTENT; AND (iii) ANY AND ALL INACCURACIES, ERRORS, OMISSIONS AND PROBLEMS OF THE CONTENT GENERATED BY THE FREESTYLE FEATURE.
      </>
      <br />
      <br />
      <>
        4. The Freestyle Feature is an experimental technology; THE FREESTYLE FEATURE AND ALL CONTENT PROVIDED BY IT ARE PROVIDED ON AN “AS-IS” AND
        “AS AVAILABLE” BASIS. VOICEFLOW DOES NOT GIVE ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED, AS TO (i) THE SUITABILITY OR USABILITY OF THE
        FREESTYLE FEATURE OR ANY OF ITS CONTENT; OR (ii) THE ACCURACY, ADEQUACY, VALIDITY, RELIABILITY, AVAILABILITY OR COMPLETENESS OF ANY CONTENT
        GENERATED BY THE FREESTYLE FEATURE.
      </>
      <br />
      <br />
      <>
        5. YOU SHALL BE RESPONSIBLE FOR THE COMMUNICATION OF ANY DISCLAIMERS TO YOUR END USERS REGARDING THE NATURE, RELIANCE ON, AND RISKS ASSOCIATED
        WITH THE USE OF THE FREESTYLE FEATURE AND THE CONTENT GENERATED BY THE FREESTYLE FEATURE, INCLUDING ANY DISCLAIMER RELATING TO THE DISCLOSURE
        OF ANY PERSONAL INFORMATION.
      </>
      <br />
      <br />
      <>
        6. The use of the Freestyle Feature may require the disclosure of your end-user data (which may include personal information) to OpenAI's
        GPT-3 language model (the “<strong>End-User Data</strong>”).
        <strong>
          You understand that you shall be responsible for the use of the Freestyle Feature, including any End-User Data that you or your end-users
          may disclose to the Freestyle Feature. To the extent permitted by applicable law, Voiceflow shall have no liability whatsoever for End-User
          Data (including personal information) that you choose to submit, integrate with, access, or otherwise process through the Freestyle Feature.
        </strong>
      </>
      <br />
      <br />
      <>
        7. You represent and warrant to, and covenant with Voiceflow that in the event that your end-users provide any End-User Data, such End-User
        Data will only contain Personal Information in respect of which you have provided all notices and disclosures, obtained all applicable third
        party consents and permissions and otherwise has all authority, in each case as required by applicable laws, to enable the use of the
        Freestyle Feature, including with respect to the collection, storage, access, use, disclosure, processing and transmission of personal
        information, including by or to Voiceflow and to or from all applicable third parties.
      </>
      <br />
      <br />
      <>8. The Freestyle Feature may contain errors, design flaws, vulnerabilities, performance issues, bugs or other problems.</>
      <br />
      <br />
      <>9. Voiceflow provides no assurance that any specific errors or discrepancies in the Freestyle Feature will be corrected.</>
      <br />
      <br />
      <>
        10 . Any and all content provided by the Freestyle Feature is NOT intended to be relied on for any reason whatsoever (including, without
        limitation, for any reason regarding medical advice, financial advice, technical advice, training and educational purposes, or advice of any
        type). The Freestyle Feature is no substitute for the advice of a professional, who should be consulted in all cases, where a professional is
        required.
      </>
      <br />
      <br />
      <>11 .You are responsible for the entirety of testing the Freestyle Feature.</>
      <br />
      <br />
      <strong>
        BY CLICKING “ACCEPT” BELOW ON THIS DISCLAIMER, WHICH MUST BE AGREED TO FOR THE ACTIVATION AND CONTINUED USE OF THE FREESTYLE FEATURE, YOU AND
        YOUR ORGANIZATION ACCEPT AND AGREE TO THE FOLLOWING DISCLAIMER.
      </strong>
    </>
  ),
};

export const GENERATE_STEP_DISCLAIMER: DisclaimerModalProps = {
  title: 'Generate Step Feature Disclaimer',
  body: GENERATE_NO_MATCH_DISCLAIMER.body,
};
