import { VoiceflowConstants } from '@voiceflow/voiceflow-types';

const BUILT_IN_NO_MATCHES_BY_LANGUAGE = {
  [VoiceflowConstants.Language.EN]: [
    "I'm sorry, I didn't quite understand what you meant. Could you please rephrase your question or request?",
    'Could you please provide more context or clarify your question?',
    "I'm having trouble understanding your message. Could you try rephrasing it in a different way?",
    "I'm sorry, but I'm not sure what you're asking. Could you please elaborate or give more details?",
    "Could you please provide more information or clarify your question? I'm not sure I understand what you're asking.",
    "I'm sorry, I didn't understand your message. Could you try explaining it in a different way?",
    "I'm having trouble following your question. Could you please give more details or rephrase it?",
    "I'm sorry, but I'm not sure what you mean. Could you try explaining it in a different way?",
    "Could you please clarify your question or provide more information? I'm having trouble understanding what you're asking.",
    "I'm sorry, I didn't understand your message. Could you please rephrase it or provide more context?",
  ],

  [VoiceflowConstants.Language.AR]: [
    'عذراً، لم أفهم ما قلت. هل يمكنك إعادة الكلام؟',
    'عذراً، لا أفهم ما تقول. هل يمكنك توضيح الموضوع؟',
    'لم أقم بالاستماع الى ما قلت. هل يمكنك إعادة طلبك؟',
    'عذراً، لم أفهم ما قلت. هل يمكنك إعطائني مزيد من التفاصيل؟',
    'عذراً، لا أفهم ما تطلب. هل يمكنك إعطائني مزيد من السياق؟',
    'عذراً، لم أفهم ما قلت. هل يمكنك إعادة المحاولة؟',
    'عذراً، لا أفهم ما تطلب. هل يمكنك إعطائني مزيد من المعلومات؟',
    'عذراً، لم أفهم ما قلت. هل يمكنك إعادة الكلام وإعطائني مزيد من السياق؟',
    'عذراً، لا أدري ما تطلب. هل يمكنك توضيح الموضوع وإعطائني مزيد من التفاصيل؟',
    'عذراً، لم أدرك ما قلت. هل يمكنك إعادة الكلام وإعطائني مزيد من التفاصيل؟',
  ],

  [VoiceflowConstants.Language.BG]: [
    'Съжалявам, не разбрах напълно какво има предвид. Можете ли да преформулирате въпроса или заявката си, моля?',
    'Можете ли да предоставите повече контекст или да уточните въпроса си, моля?',
    'Имам трудности да разбера вашето съобщение. Можете ли да го преформулирате по различен начин?',
    'Съжалявам, но не съм сигурен/а какво питате. Можете ли да обясните или да дадете повече подробности, моля?',
    'Можете ли да предоставите повече информация или да уточните въпроса си? Не съм сигурен/а, че разбирам какво питате.',
    'Съжалявам, не разбрах съобщението ви. Можете ли да опитате да го обясните по различен начин?',
    'Имам трудности да последвам вашия въпрос. Можете ли да предоставите повече подробности или да го преформулирате?',
    'Съжалявам, но не съм сигурен/а какво имате предвид. Можете ли да опитате да го обясните по различен начин?',
    'Можете ли да уточните въпроса си или да предоставите повече информация? Имам затруднения да разбера какво питате.',
    'Съжалявам, не разбрах съобщението ви. Можете ли да го преформулирате или да предоставите повече контекст, моля?',
  ],

  [VoiceflowConstants.Language.CA]: [
    'Lamento, no he entès del tot què volies dir. Podries reformular la teva pregunta o sol·licitud, si et plau?',
    'Podries proporcionar més context o aclarir la teva pregunta, si et plau?',
    "Em costa entendre el teu missatge. Podries provar de reformular-lo d'una manera diferent?",
    'Lamento, però no entenc què estàs preguntant. Podries detallar o donar més informació, si et plau?',
    "Podries proporcionar més informació o aclarir la teva pregunta? No estic segur/a d'entendre el que preguntes.",
    'Lamento, no he entès el teu missatge. Podries intentar explicar-ho de manera diferent?',
    'Em costa seguir la teva pregunta. Podries donar més detalls o reformular-la, si et plau?',
    "Lamento, però no entenc què vols dir. Podries provar d'explicar-ho de manera diferent?",
    'Podries aclarir la teva pregunta o proporcionar més informació? Em costa entendre què preguntes.',
    'Lamento, no he entès el teu missatge. Podries reformular-lo o proporcionar més context, si et plau?',
  ],

  [VoiceflowConstants.Language.HE]: [
    'מצטער, לא הבנתי מה שרצית לומר. האם תוכל לבקש מחדש את השאלה או הבקשה?',
    'האם תוכל לספק עוד הקשר או להבהיר את השאלה שלך?',
    'יש לי בעיה להבין את ההודעה שלך. האם תוכל לנסות להציג אותה בדרך אחרת?',
    'מצטער, אך לא בטוח מה אתה שואל. האם תוכל לפרט יותר או לספק פרטים נוספים?',
    'האם תוכל לספק עוד מידע או להבהיר את השאלה שלך? אני לא בטוח שהבנתי מה אתה שואל.',
    'מצטער, לא הבנתי את ההודעה שלך. האם תוכל לנסות להסביר אותה בדרך אחרת?',
    'יש לי קשיים לעקוב אחרי השאלה שלך. האם תוכל לספק פרטים נוספים או לפרט את השאלה?',
    'מצטער, אך אני לא בטוח מה המשמעות. האם תוכל לנסות להסביר את זה בדרך אחרת?',
    'האם תוכל להבהיר את השאלה שלך או לספק עוד מידע? יש לי קשיים להבין את מה שאתה שואל.',
    'מצטער, לא הבנתי את ההודעה שלך. האם תוכל לנסות להציג אותה בצורה אחרת או לספק יותר הקשר?',
  ],
  [VoiceflowConstants.Language.HU]: [
    'Sajnálom, nem értettem teljesen, hogy mire gondolsz. Meg tudnád újra fogalmazni a kérdésed vagy kérést?',
    'Kérlek, adj több kontextust vagy világosítsd fel a kérdésedet?',
    'Nehézséget okoz a üzeneted megértése. Megpróbálnád más szavakkal újra megfogalmazni?',
    'Sajnálom, de nem vagyok biztos abban, hogy mit kérdezel. Tudnál részletezni vagy több információt megadni?',
    'Kérlek, adj több információt vagy világosítsd fel a kérdésedet. Nem vagyok biztos benne, hogy értem, amit kérdezel.',
    'Sajnálom, nem értettem meg az üzenetedet. Megpróbálnád más módon elmagyarázni?',
    'Problémát okoz a kérdésed követése. Kérnél több részletet vagy újrafogalmazást?',
    'Sajnálom, de nem vagyok biztos abban, hogy mit értesz. Megpróbálnád más módon elmagyarázni?',
    'Kérlek, tisztázd a kérdésedet vagy adj meg több információt? Nehézséget okoz megérteni, hogy mit kérdezel.',
    'Sajnálom, nem értettem meg az üzenetedet. Megpróbálnád újra megfogalmazni vagy több kontextust adni?',
  ],
  [VoiceflowConstants.Language.PL]: [
    'Przepraszam, nie do końca zrozumiałem, o co ci chodziło. Czy mógłbyś/abyś przeformułować swoje pytanie lub prośbę?',
    'Proszę, czy mógłbyś/abyś dostarczyć więcej kontekstu lub wyjaśnić swoje pytanie?',
    'Mam trudności z zrozumieniem twojej wiadomości. Czy mógłbyś/abyś spróbować ją inaczej ująć?',
    'Przepraszam, ale nie jestem pewien/pewna, o co pytasz. Czy mógłbyś/abyś wyjaśnić lub podać więcej szczegółów?',
    'Czy mógłbyś/abyś dostarczyć więcej informacji lub wyjaśnić swoje pytanie? Nie jestem pewien/pewna, czy rozumiem, o co pytasz.',
    'Przepraszam, nie zrozumiałem twojej wiadomości. Czy mógłbyś/abyś spróbować ją inaczej wyjaśnić?',
    'Mam trudności z zrozumieniem twojego pytania. Czy mógłbyś/abyś podać więcej szczegółów lub je inaczej sformułować?',
    'Przepraszam, ale nie jestem pewien/pewna, co masz na myśli. Czy mógłbyś/abyś spróbować to inaczej wyjaśnić?',
    'Czy mógłbyś/abyś wyjaśnić swoje pytanie lub dostarczyć więcej informacji? Mam problem z zrozumieniem, o co pytasz.',
    'Przepraszam, nie zrozumiałem twojej wiadomości. Czy mógłbyś/abyś ją inaczej ująć lub dostarczyć więcej kontekstu?',
  ],
  [VoiceflowConstants.Language.RO]: [
    'Îmi pare rău, nu am înțeles foarte bine ce ai vrut să spui. Ai putea te rog să reformulezi întrebarea sau solicitarea ta?',
    'Poți oferi mai mult context sau să clarifici întrebarea ta, te rog?',
    'Am dificultăți în a înțelege mesajul tău. Ai putea să îl reformulezi în alt mod?',
    'Îmi pare rău, dar nu sunt sigur/ă ce întrebi. Ai putea să explici mai în detaliu sau să dai mai multe informații?',
    'Poți să furnizezi mai multe informații sau să clarifici întrebarea ta? Nu sunt sigur/ă că înțeleg ce întrebi.',
    'Îmi pare rău, nu am înțeles mesajul tău. Ai putea să îl explici în alt mod?',
    'Am dificultăți în a urmări întrebarea ta. Ai putea te rog să oferi mai multe detalii sau să o reformulezi?',
    'Îmi pare rău, dar nu sunt sigur/ă ce vrei să spui. Ai putea să încerci să explici în alt mod?',
    'Poți te rog să clarifici întrebarea sau să oferi mai multe informații? Am dificultăți în a înțelege ce întrebi.',
    'Îmi pare rău, nu am înțeles mesajul tău. Ai putea să îl reformulezi sau să oferi mai mult context?',
  ],
  [VoiceflowConstants.Language.RU]: [
    'Извините, я не совсем понял, что вы имели в виду. Можете ли вы переформулировать свой вопрос или запрос?',
    'Можете ли вы, пожалуйста, предоставить больше контекста или уточнить свой вопрос?',
    'У меня возникли проблемы с пониманием вашего сообщения. Не могли бы вы попробовать переформулировать его по-другому?',
    'Извините, но я не уверен, в чем ваш вопрос. Можете ли вы уточнить или предоставить больше деталей?',
    'Можете ли вы, пожалуйста, предоставить больше информации или уточнить свой вопрос? Я не уверен, что понимаю, о чем вы спрашиваете.',
    'Извините, я не понял вашего сообщения. Можете ли вы попробовать объяснить это другим способом?',
    'Мне трудно следовать за вашим вопросом. Не могли бы вы уточнить детали или переформулировать его?',
    'Извините, но я не уверен, что вы имеете в виду. Можете ли вы попробовать объяснить это по-другому?',
    'Можете ли вы, пожалуйста, уточнить свой вопрос или предоставить больше информации? Мне трудно понять, о чем вы спрашиваете.',
    'Извините, я не понял вашего сообщения. Можете ли вы переформулировать его или предоставить больше контекста?',
  ],
  [VoiceflowConstants.Language.UK]: [
    'Вибачте, я не зрозумів, що ви маєте на увазі. Можливо, ви могли б переформулювати своє питання чи запит?',
    'Можливо, ви могли б надати більше контексту або уточнити ваше питання?',
    'Я маю труднощі з розумінням вашого повідомлення. Можливо, спробуйте перефразувати його інакше?',
    'Вибачте, але я не впевнений, в чому ви запитуєте. Можливо, ви могли б уточнити або надати більше деталей?',
    'Можливо, ви могли б надати більше інформації або уточнити ваше питання? Я не впевнений, що розумію, що ви запитуєте.',
    'Вибачте, я не зрозумів вашого повідомлення. Можливо, спробуйте пояснити це інакше?',
    'Мені важко зрозуміти ваше питання. Можливо, ви могли б надати більше деталей або переформулювати його?',
    'Вибачте, але я не впевнений, що ви маєте на увазі. Можливо, ви могли б пояснити це інакше?',
    'Можливо, ви могли б уточнити ваше питання або надати більше інформації? Мені важко зрозуміти, що ви запитуєте.',
    'Вибачте, я не зрозумів вашого повідомлення. Можливо, ви могли б переформулювати його або надати більше контексту?',
  ],
  [VoiceflowConstants.Language.VI]: [
    'Tôi xin lỗi, tôi không hiểu rõ ý bạn đang nói gì. Bạn có thể diễn đạt lại câu hỏi hoặc yêu cầu của mình không?',
    'Liệu bạn có thể cung cấp thêm ngữ cảnh hoặc làm rõ câu hỏi của bạn không?',
    'Tôi gặp khó khăn trong việc hiểu tin nhắn của bạn. Bạn có thể thử diễn đạt lại bằng cách khác được không?',
    'Tôi xin lỗi, nhưng tôi không chắc bạn đang hỏi gì. Bạn có thể giải thích hoặc cung cấp thêm chi tiết được không?',
    'Liệu bạn có thể cung cấp thêm thông tin hoặc làm rõ câu hỏi của bạn không? Tôi không chắc tôi hiểu bạn đang hỏi gì.',
    'Tôi xin lỗi, tôi không hiểu tin nhắn của bạn. Bạn có thể thử giải thích bằng cách khác được không?',
    'Tôi gặp khó khăn trong việc theo sau câu hỏi của bạn. Bạn có thể cung cấp thêm chi tiết hoặc diễn đạt lại không?',
    'Tôi xin lỗi, nhưng tôi không chắc bạn đang nói gì. Bạn có thể thử giải thích bằng cách khác được không?',
    'Liệu bạn có thể làm rõ câu hỏi hoặc cung cấp thêm thông tin không? Tôi gặp khó khăn trong việc hiểu bạn đang hỏi gì.',
    'Tôi xin lỗi, tôi không hiểu tin nhắn của bạn. Bạn có thể diễn đạt lại hoặc cung cấp thêm ngữ cảnh không?',
  ],

  [VoiceflowConstants.Language.ZH]: [
    '对不起，我不太理解你的意思。你能再重新表述一下你的问题或请求吗？',
    '你能否提供更多的背景或澄清你的问题？',
    '我无法理解你的信息。你能否尝试用不同的方式重新表达一下？',
    '对不起，但我不确定你在询问什么。你能否详细阐述一下或提供更多的细节？',
    '你能否提供更多的信息或澄清你的问题？我不确定我理解了你的问题。',
    '对不起，我没有理解你的信息。你能否尝试用另一种方式解释一下？',
    '我无法理解你的问题。你能否提供更多的细节或重新表达一下？',
    '对不起，但我不确定你的意思。你能否尝试用另一种方式解释一下？',
    '你能否澄清你的问题或提供更多的信息？我无法理解你在询问什么。',
    '对不起，我没有理解你的信息。你能否重新表达一下或提供更多的背景？',
  ],

  [VoiceflowConstants.Language.CS]: [
    'Omlouvám se, nerozuměl jsem úplně tomu, co myslíte. Mohl(a) byste prosím přeformulovat svou otázku nebo žádost?',
    'Prosím, mohl(a) byste poskytnout více kontextu nebo objasnit svou otázku?',
    'Mám problém porozumět vaší zprávě. Mohl(a) byste ji zkusit vyjádřit jiným způsobem?',
    'Omlouvám se, ale nejsem si jistý(á), co se ptáte. Mohl(a) byste prosím upřesnit nebo uvést více detailů?',
    'Prosím, mohl(a) byste poskytnout více informací nebo objasnit svou otázku? Nejsem si jistý(á), že rozumím tomu, co se ptáte.',
    'Omlouvám se, nerozuměl(a) jsem vaší zprávě. Mohl(a) byste ji zkusit vysvětlit jiným způsobem?',
    'Mám potíže s následováním vaší otázky. Mohl(a) byste poskytnout více detailů nebo ji přeformulovat?',
    'Omlouvám se, ale nejsem si jistý(á), co máte na mysli. Mohl(a) byste to zkusit vysvětlit jiným způsobem?',
    'Prosím, mohl(a) byste objasnit svou otázku nebo poskytnout více informací? Mám problém porozumět tomu, co se ptáte.',
    'Omlouvám se, nerozuměl(a) jsem vaší zprávě. Mohl(a) byste ji prosím přeformulovat nebo poskytnout více kontextu?',
  ],

  [VoiceflowConstants.Language.DA]: [
    'Jeg beklager, jeg forstod ikke helt, hvad du mente. Kunne du venligst omformulere dit spørgsmål eller din anmodning?',
    'Kunne du venligst give mere kontekst eller præcisere dit spørgsmål?',
    'Jeg har svært ved at forstå din besked. Kunne du prøve at omformulere den på en anden måde?',
    'Jeg beklager, men jeg er ikke sikker på, hvad du spørger om. Kunne du venligst uddybe eller give flere detaljer?',
    'Kunne du venligst give mere information eller præcisere dit spørgsmål? Jeg er ikke sikker på, at jeg forstår, hvad du spørger om.',
    'Jeg beklager, jeg forstod ikke din besked. Kunne du prøve at forklare det på en anden måde?',
    'Jeg har svært ved at følge dit spørgsmål. Kunne du venligst give flere detaljer eller omformulere det?',
    'Jeg beklager, men jeg er ikke sikker på, hvad du mener. Kunne du prøve at forklare det på en anden måde?',
    'Kunne du venligst præcisere dit spørgsmål eller give mere information? Jeg har svært ved at forstå, hvad du spørger om.',
    'Jeg beklager, jeg forstod ikke din besked. Kunne du venligst omformulere det eller give mere kontekst?',
  ],
  [VoiceflowConstants.Language.NL]: [
    'Sorry, ik begrijp niet helemaal wat je bedoelt. Kun je je vraag of verzoek alsjeblieft op een andere manier formuleren?',
    'Kun je alsjeblieft meer context geven of je vraag verduidelijken?',
    'Ik heb moeite met het begrijpen van je bericht. Kun je het op een andere manier herformuleren?',
    'Sorry, maar ik ben niet zeker wat je vraagt. Kun je alsjeblieft uitweiden of meer details geven?',
    'Kun je alsjeblieft meer informatie geven of je vraag verduidelijken? Ik begrijp niet helemaal wat je vraagt.',
    'Sorry, ik heb je bericht niet begrepen. Kun je het op een andere manier uitleggen?',
    'Ik heb moeite met het volgen van je vraag. Kun je alsjeblieft meer details geven of het op een andere manier herformuleren?',
    'Sorry, maar ik ben niet zeker wat je bedoelt. Kun je het op een andere manier uitleggen?',
    'Kun je alsjeblieft je vraag verduidelijken of meer informatie geven? Ik begrijp niet helemaal wat je vraagt.',
    'Sorry, ik heb je bericht niet begrepen. Kun je het alsjeblieft op een andere manier formuleren of meer context geven?',
  ],

  [VoiceflowConstants.Language.ET]: [
    'Vabandust, ma ei saanud päris aru, mida te silmas peate. Kas saaksite palun oma küsimust või taotlust ümber sõnastada?',
    'Kas saaksite palun pakkuda rohkem konteksti või selgitada oma küsimust?',
    'Mul on raskusi teie sõnumi mõistmisega. Kas võiksite proovida seda erinevalt ümber sõnastada?',
    'Vabandust, aga ma pole kindel, millest te küsite. Kas saaksite palun täpsustada või anda rohkem üksikasju?',
    'Kas saaksite palun pakkuda rohkem infot või selgitada oma küsimust? Ma ei ole kindel, et mõistan, mida te küsite.',
    'Vabandust, ma ei saanud teie sõnumist aru. Kas saaksite proovida seda teistmoodi selgitada?',
    'Mul on raske jälgida teie küsimust. Kas saaksite palun anda rohkem üksikasju või sõnastada selle ümber?',
    'Vabandust, aga ma ei saa aru, mida te mõtlete. Kas saaksite proovida seda teistmoodi selgitada?',
    'Kas saaksite palun selgitada oma küsimust või pakkuda rohkem infot? Mul on raske aru saada, mida te küsite.',
    'Vabandust, ma ei saanud teie sõnumist aru. Kas saaksite seda ümber sõnastada või pakkuda rohkem konteksti?',
  ],
  [VoiceflowConstants.Language.FR]: [
    "Désolé, je n'ai pas tout à fait compris ce que vous vouliez dire. Pourriez-vous reformuler votre question ou votre demande, s'il vous plaît ?",
    "Pourriez-vous fournir plus de contexte ou préciser votre question, s'il vous plaît ?",
    "J'ai du mal à comprendre votre message. Pourriez-vous le reformuler de manière différente, s'il vous plaît ?",
    "Désolé, mais je ne suis pas sûr de ce que vous me demandez. Pourriez-vous développer ou donner plus de détails, s'il vous plaît ?",
    "Pourriez-vous fournir plus d'informations ou préciser votre question, s'il vous plaît ? Je ne suis pas sûr de comprendre ce que vous me demandez.",
    "Désolé, je n'ai pas compris votre message. Pourriez-vous l'expliquer de manière différente, s'il vous plaît ?",
    "J'ai du mal à suivre votre question. Pourriez-vous donner plus de détails ou la reformuler, s'il vous plaît ?",
    "Désolé, mais je ne suis pas sûr de ce que vous voulez dire. Pourriez-vous l'expliquer de manière différente, s'il vous plaît ?",
    "Pourriez-vous préciser votre question ou fournir plus d'informations, s'il vous plaît ? Je n'arrive pas à comprendre ce que vous me demandez.",
    "Désolé, je n'ai pas compris votre message. Pourriez-vous le reformuler ou fournir plus de contexte, s'il vous plaît ?",
  ],

  [VoiceflowConstants.Language.DE]: [
    'Entschuldigung, ich habe nicht ganz verstanden, was Sie meinen. Könnten Sie Ihre Frage oder Ihre Anfrage bitte anders formulieren?',
    'Könnten Sie bitte mehr Kontext liefern oder Ihre Frage klären?',
    'Ich habe Schwierigkeiten, Ihre Nachricht zu verstehen. Könnten Sie es bitte anders formulieren?',
    'Entschuldigung, aber ich bin mir nicht sicher, was Sie mich fragen. Könnten Sie bitte ausführen oder mehr Details geben?',
    'Könnten Sie bitte mehr Informationen liefern oder Ihre Frage klären? Ich bin mir nicht sicher, ob ich verstehe, was Sie mich fragen.',
    'Entschuldigung, ich habe Ihre Nachricht nicht verstanden. Könnten Sie es bitte anders erklären?',
    'Ich habe Schwierigkeiten, Ihre Frage zu verfolgen. Könnten Sie bitte mehr Details geben oder es anders formulieren?',
    'Entschuldigung, aber ich bin mir nicht sicher, was Sie meinen. Könnten Sie es bitte anders erklären?',
    'Könnten Sie bitte Ihre Frage klären oder mehr Informationen liefern? Ich habe Schwierigkeiten, zu verstehen, was Sie mich fragen.',
    'Entschuldigung, ich habe Ihre Nachricht nicht verstanden. Könnten Sie bitte anders formulieren oder mehr Kontext liefern?',
  ],

  [VoiceflowConstants.Language.HI]: [
    'माफ़ कीजिये, मैंने आपका मतलब ठीक से समझा नहीं है। क्या आप अपना सवाल या अनुरोध फिर से बनाने में मदद कर सकते हैं?',
    'क्या आप अधिक संदर्भ या अपना सवाल स्पष्ट कर सकते हैं?',
    'मैंने अपनी संदेश को समझने में तकलीफ है। क्या आप उसे अलग तरह से फिर से व्यक्त करने में मदद कर सकते हैं?',
    'माफ़ कीजिये, लेकिन मैं नहीं सुनता हूँ कि आप मुझसे क्या पूछ रहे हैं। क्या आप बढ़ावा दे सकते हैं या अधिक विवरण दे सकते हैं?',
    'माफ़ कीजिये, मैंने आपकी संदेश नहीं समझी है। क्या आप उसे अलग तरह से स्पष्ट कर सकते हैं?',
    'मैंने अपने सवाल को पढ़ने में तकलीफ है। क्या आप अधिक विवरण दे सकते हैं या उसे अलग तरह से फिर से बना सकते हैं?',
    'क्या आप अपना सवाल स्पष्ट कर सकते हैं या अधिक जानकारी दे सकते हैं? मैं नहीं सुनता हूँ कि आप मुझसे क्या पूछ रहे हैं।',
    'माफ़ कीजिये, मैंने आपकी संदेश नहीं समझी है। क्या आप उसे अलग तरह से फिर से बना सकते हैं या अधिक संदर्भ दे सकते हैं?',
  ],

  [VoiceflowConstants.Language.IT]: [
    'Mi dispiace, non ho capito del tutto cosa volevi dire. Potresti riformulare la tua domanda o richiesta, per favore?',
    'Potresti fornire più contesto o chiarire la tua domanda, per favore?',
    'Sto avendo difficoltà a capire il tuo messaggio. Potresti riformularlo in modo diverso, per favore?',
    'Mi dispiace, ma non sono sicuro di cosa mi stai chiedendo. Potresti esporre o fornire maggiori dettagli, per favore?',
    'Potresti fornire più informazioni o chiarire la tua domanda, per favore? Non sono sicuro di aver capito cosa mi stai chiedendo.',
    'Mi dispiace, non ho capito il tuo messaggio. Potresti spiegare in modo diverso, per favore?',
    'Sto avendo difficoltà a seguire la tua domanda. Potresti fornire maggiori dettagli o riformularla, per favore?',
    'Mi dispiace, ma non sono sicuro di cosa vuoi dire. Potresti spiegare in modo diverso, per favore?',
    'Potresti chiarire la tua domanda o fornire più informazioni, per favore? Non riesco a capire cosa mi stai chiedendo.',
    'Mi dispiace, non ho capito il tuo messaggio. Potresti riformularlo o fornire più contesto, per favore?',
  ],

  [VoiceflowConstants.Language.JA]: [
    'すみません、あなたが何を言いたいのかわかりませんでした。 質問やリクエストを別のやり方で再フォーマットすることはできますか？',
    'もっと文脈を提供するか、質問を明確にすることはできますか？',
    'あなたのメッセージを理解するのが難しいです。 別のやり方で再度言い表すことはできますか？',
    'すみませんが、あなたが何を聞いているのかわかりません。 もっと詳細を述べるか、より多くの詳細を提供することはできますか？',
    'もっと情報を提供するか、質問を明確にすることはできますか？ あなたが何を聞いているのかわかりません。',
    'すみません、あなたのメッセージを理解できませんでした。 別のやり方で説明することはできますか？',
    '私はあなたの質問を追跡するのが難しいです。 もっと詳細を提供するか、別のやり方で再フォーマットすることはできますか？',
    'すみませんが、あなたが何を言いたいのかわかりません。 別のやり方で説明することはできますか？',
    '質問を明確にするか、もっと情報を提供することはできますか？ あなたが何を聞いているのかわかりません。',
    'すみません、あなたのメッセージを理解できませんでした。 別のやり方で再フォーマットするか、もっと文脈を提供することはできますか？',
  ],

  [VoiceflowConstants.Language.KO]: [
    '죄송합니다. 제가 제가 이해할 수 없는 질문이나 요청을 하고 있습니다. 질문 또는 요청을 다른 방식으로 재형성할 수 있을까요?',
    '제가 이해할 수 있도록 자세히 설명하거나 질문을 정확하게 전달할 수 있을까요?',
    '제가 메시지를 이해하기 어려운 상황입니다. 다른 방식으로 재형성할 수 있을까요?',
    '죄송합니다만, 제가 어떤 질문을 하고 있는지 잘 모르겠습니다. 자세히 설명하거나 자세한 정보를 제공할 수 있을까요?',
    '자세한 정보를 제공하거나 질문을 정확하게 전달할 수 있을까요? 제가 어떤 질문을 하고 있는지 잘 모르겠습니다.',
    '죄송합니다만, 제가 메시지를 이해하지 못했습니다. 다른 방식으로 설명할 수 있을까요?',
    '질문을 추적하기 어려운 상황입니다. 자세한 정보를 제공하거나 다른 방식으로 재형성할 수 있을까요?',
    '죄송합니다만, 제가 어떤 의도로 질문을 하고 있는지 잘 모르겠습니다. 다른 방식으로 설명할 수 있을까요?',
    '질문을 정확하게 전달하거나 자세한 정보를 제공할 수 있을까요? 제가 어떤 질문을 하고 있는지 잘 모르겠습니다.',
    '죄송합니다만, 제가 메시지를 이해하지 못했습니다. 다른 방식으로 재형성할 수 있거나 자세한 정보를 제공할 수 있을까요?',
  ],

  [VoiceflowConstants.Language.MR]: [
    'माफ करा, मी तुमची संदेश समजत नाही. क्या तुम्ही तो विविध माहितीने पुनर्स्थापित करू शकता?',
    'माफ करा, मी तुमचे प्रश्न समजत नाही. तुम्ही तो अधिक विवरण देऊ शकता अथवा तो विविध माहितीने पुनर्स्थापित करू शकता?',
    'माफ करा, मी तुमचे संदेश समजत नाही. तुम्ही तो अधिक विवरण देऊ शकता अथवा तो विविध माहितीने पुनर्स्थापित करू शकता?',
    'माफ करा, मी तुमचा प्रश्न समजत नाही. तुम्ही तो अधिक विवरण देऊ शकता अथवा तो विविध माहितीने प',
    'माफ करा, मी तुमचा प्रश्न समजत नाही. तुम्ही तो अधिक विवरण देऊ शकता अथवा तो विविध माहितीने पुनर्स्थापित करू शकता?',
    'माफ करा, मी तुमचे संदेश समजत नाही. तुम्ही तो विविध माहितीने पुनर्स्थापित करू शकता अथवा तो अधिक विवरण देऊ शकता?',
    'माफ करा, मी तुमचे संदेश समजले नाही. क्या तुम्ही तो विविध माहिती देऊ शकता अथवा तो ही आवश्यकताने नंतर पुनर्स्थापित करू शकता?',
    'माफ करा, मी तुमचा प्रश्न पुनरावलोकन करण्यासाठी असमर्थ आहे. तुम्ही तो अधिक विवरण देऊ शकता अथवा तो विविध माहितीने पुनर्स्थापित करू शकता?',
  ],

  [VoiceflowConstants.Language.PT]: [
    'Desculpe, não entendi sua mensagem. Poderia reformular ou fornecer mais informações para que eu possa compreender?',
    'Desculpe, não consegui entender sua mensagem. Poderia reformular de outra maneira ou fornecer mais contexto?',
    'Desculpe, mas não estou entendendo o que você está perguntando. Poderia fornecer mais detalhes ou reformular a pergunta de outra maneira?',
    'Desculpe, não consegui acompanhar sua pergunta. Poderia fornecer mais informações ou reformular de outra maneira?',
    'Desculpe, não estou conseguindo acompanhar sua pergunta. Poderia fornecer mais detalhes ou reformular de outra maneira?',
    'Desculpe, mas não estou entendendo o que você está perguntando. Poderia fornecer mais informações ou reformular a pergunta de outra maneira?',
    'Desculpe, não consegui acompanhar sua pergunta. Poderia fornecer mais detalhes ou reformular de outra maneira?',
    'Desculpe, não entendi sua mensagem. Poderia reformular de outra maneira ou fornecer mais contexto?',
  ],

  [VoiceflowConstants.Language.ES]: [
    'Lo siento, no entendí tu mensaje. ¿Podrías reformularlo o proporcionar más información para que pueda entenderlo mejor?',
    'Lo siento, no estoy entendiendo tu pregunta. ¿Podrías proporcionar más detalles o reformularla de otra manera?',
    'Lo siento, no logré entender tu mensaje. ¿Podrías reformularlo de otra manera o proporcionar más contexto?',
    'Lo siento, pero no estoy entendiendo lo que estás preguntando. ¿Podrías proporcionar más información o reformular la pregunta de otra manera?',
    'Lo siento, pero no estoy entendiendo lo que estás preguntando. ¿Podrías proporcionar más detalles o reformular la pregunta de otra manera?',
    'Lo siento, no estoy entendiendo tu pregunta. ¿Podrías proporcionar más información o reformularla de otra manera?',
  ],

  [VoiceflowConstants.Language.TA]: ['மன்னிக்கவும் எனக்கு புரியவில்லை. அதை மீண்டும் வேறு விதமாக சொல்ல முடியுமா?'],

  [VoiceflowConstants.Language.TE]: ['క్షమించండి నాకు అర్ధం కాలేదు. మళ్లీ వేరే విధంగా చెప్పగలరా?'],

  [VoiceflowConstants.Language.TR]: [
    'Özür dilerim, mesajınızı anlayamadım. Lütfen daha ayrıntılı bilgi verin veya mesajınızı farklı bir şekilde yeniden yazın.',
  ],
} as const;

export const DEFAULT_BUILT_IN_NO_MATCHES = BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.EN];

export const BUILT_IN_NO_MATCHES_BY_LOCALE: Partial<Record<VoiceflowConstants.Locale, readonly string[]>> = {
  [VoiceflowConstants.Locale.EN_US]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.EN],
  [VoiceflowConstants.Locale.AR_AR]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.AR],
  [VoiceflowConstants.Locale.BG_BG]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.BG],
  [VoiceflowConstants.Locale.CA_ES]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.CA],
  [VoiceflowConstants.Locale.CS_CZ]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.CS],
  [VoiceflowConstants.Locale.ZH_TW]: [
    '抱歉，我不太了解您的意思。您可以重新詞述您的問題或請求嗎？',
    '請您提供更多的背景資訊或釐清您的問題嗎？',
    '我有點難以理解您的訊息。您能試著用不同的方式表達一下嗎？',
    '抱歉，我不確定您在詢問什麼。您可以詳細說明或提供更多細節嗎？',
    '您能提供更多資訊或釐清您的問題嗎？我不太確定我理解您的意思。',
    '抱歉，我沒有理解您的訊息。您能試著用另一種方式解釋嗎？',
    '我有點難以理解您的問題。您能提供更多細節或重新詞述嗎？',
    '抱歉，我不確定您的意思。您能試著用不同的方式解釋嗎？',
    '您可以釐清您的問題或提供更多資訊嗎？我有點難以理解您的詢問。',
    '抱歉，我沒有理解您的訊息。您可以重新表達或提供更多背景嗎？',
  ],
  [VoiceflowConstants.Locale.ZH_CN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.ZH],
  [VoiceflowConstants.Locale.DA_DK]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.DA],
  [VoiceflowConstants.Locale.NL_NL]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.NL],
  [VoiceflowConstants.Locale.NL_BE]: [
    'Zou je meer context kunnen geven of je vraag kunnen verduidelijken, alsjeblieft?',
    'Ik heb moeite om je bericht te begrijpen. Zou je het op een andere manier kunnen verwoorden?',
    'Het spijt me, maar ik weet niet zeker wat je vraagt. Zou je kunnen uitweiden of meer details kunnen geven?',
    'Zou je meer informatie kunnen geven of je vraag kunnen verduidelijken? Ik ben niet zeker of ik begrijp wat je bedoelt.',
    'Het spijt me, ik begreep je bericht niet helemaal. Zou je het op een andere manier kunnen uitleggen?',
    'Ik heb moeite om je vraag te volgen. Zou je meer details kunnen geven of het anders kunnen verwoorden?',
    'Het spijt me, maar ik begrijp niet goed wat je bedoelt. Zou je het op een andere manier kunnen uitleggen?',
    'Zou je je vraag kunnen verduidelijken of meer informatie kunnen geven? Ik begrijp niet goed wat je bedoelt.',
    'Het spijt me, ik begreep je bericht niet. Zou je het anders kunnen verwoorden of meer context kunnen geven?',
  ],
  [VoiceflowConstants.Locale.ET_EE]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.ET],
  [VoiceflowConstants.Locale.FR_FR]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.FR],
  [VoiceflowConstants.Locale.DE_DE]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.DE],
  [VoiceflowConstants.Locale.HE_IL]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.HE],
  [VoiceflowConstants.Locale.HI_IN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.HI],
  [VoiceflowConstants.Locale.HU_HU]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.HU],
  [VoiceflowConstants.Locale.IT_IT]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.IT],
  [VoiceflowConstants.Locale.JA_JP]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.JA],
  [VoiceflowConstants.Locale.KO_KR]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.KO],
  [VoiceflowConstants.Locale.MR_IN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.MR],
  [VoiceflowConstants.Locale.PT_BR]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.PT],
  [VoiceflowConstants.Locale.PT_PT]: [
    'Lamento, não compreendi bem o que quis dizer. Poderia reformular a sua pergunta ou pedido, por favor?',
    'Poderia fornecer mais contexto ou esclarecer a sua pergunta, por favor?',
    'Estou com dificuldades em compreender a sua mensagem. Poderia tentar reformulá-la de maneira diferente?',
    'Lamento, mas não tenho a certeza do que está a perguntar. Poderia elaborar ou dar mais detalhes, por favor?',
    'Poderia fornecer mais informações ou esclarecer a sua pergunta? Não tenho a certeza se entendi o que está a perguntar.',
    'Lamento, não compreendi a sua mensagem. Poderia tentar explicar de forma diferente?',
    'Estou com dificuldades em entender a sua pergunta. Poderia fornecer mais detalhes ou reformulá-la, por favor?',
    'Lamento, mas não percebo o que quer dizer. Poderia tentar explicar de forma diferente?',
    'Poderia esclarecer a sua pergunta ou fornecer mais informações? Estou com dificuldades em entender o que está a perguntar.',
    'Lamento, não compreendi a sua mensagem. Poderia reformulá-la ou fornecer mais contexto, por favor?',
  ],
  [VoiceflowConstants.Locale.PL_PL]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.PL],
  [VoiceflowConstants.Locale.RO_RO]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.RO],
  [VoiceflowConstants.Locale.RU_RU]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.RU],
  [VoiceflowConstants.Locale.ES_ES]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.ES],
  [VoiceflowConstants.Locale.ES_MX]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.ES],
  [VoiceflowConstants.Locale.TA_IN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.TA],
  [VoiceflowConstants.Locale.TE_IN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.TE],
  [VoiceflowConstants.Locale.TR_TR]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.TR],
  [VoiceflowConstants.Locale.UK_UA]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.UK],
  [VoiceflowConstants.Locale.VI_VN]: BUILT_IN_NO_MATCHES_BY_LANGUAGE[VoiceflowConstants.Language.VI],

  [VoiceflowConstants.Locale.FR_CA]: [
    "Désolé, j'ai pas tout compris ce que tu voulais dire. Pourrais-tu reformuler ta question ou ta demande, s'il te plaît ?",
    "Pourrais-tu fournir plus de contexte ou préciser ta question, s'il te plaît ?",
    "J'ai de la misère à comprendre ton message. Pourrais-tu le reformuler de manière différente, s'il te plaît ?",
    "Désolé, mais je suis pas sûr de ce que tu me demandes. Pourrais-tu développer ou donner plus de détails, s'il te plaît ?",
    "Pourrais-tu fournir plus d'informations ou préciser ta question, s'il te plaît ? Je suis pas sûr de comprendre ce que tu me demandes.",
    "Désolé, j'ai pas compris ton message. Pourrais-tu l'expliquer de manière différente, s'il te plaît ?",
    "J'ai de la misère à suivre ta question. Pourrais-tu donner plus de détails ou la reformuler, s'il te plaît ?",
    "Désolé, mais je suis pas sûr de ce que tu veux dire. Pourrais-tu l'expliquer de manière différente, s'il te plaît ?",
    "Pourrais-tu préciser ta question ou fournir plus d'informations, s'il te plaît ? J'arrive pas à comprendre ce que tu me demandes.",
    "Désolé, j'ai pas compris ton message. Pourrais-tu le reformuler ou fournir plus de contexte, s'il te plaît ?",
  ],
};
