import { AlexaProject } from '@voiceflow/alexa-types';

export const MARKET_PLACE_AVAILABILITY = [
  {
    marketPlace: AlexaProject.MarketPlace.COM,
    currency: 'USD',
    icon: '$',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: ['US'],
  },
  {
    marketPlace: AlexaProject.MarketPlace.CO_UK,
    currency: 'GBP',
    icon: '£',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: [
      'IE',
      'BE',
      'BG',
      'CY',
      'CZ',
      'DK',
      'EE',
      'FI',
      'GB',
      'GG',
      'GI',
      'GR',
      'HR',
      'HU',
      'LT',
      'LV',
      'MT',
      'NL',
      'NO',
      'PL',
      'PT',
      'RO',
      'SE',
      'SI',
      'SK',
      'UA',
    ],
  },
  {
    marketPlace: AlexaProject.MarketPlace.DE,
    currency: 'EUR',
    icon: '€',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: ['AT', 'DE', 'LI', 'LU'],
  },
  {
    marketPlace: 'amazon.es',
    currency: 'EUR',
    icon: '€',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: ['ES'],
  },
  {
    marketPlace: AlexaProject.MarketPlace.FR,
    currency: 'EUR',
    icon: '€',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: ['FR'],
  },
  {
    marketPlace: 'amazon.it',
    currency: 'EUR',
    icon: '€',
    min: 0.99,
    max: {
      ENTITLEMENT: 99.99,
      SUBSCRIPTION: 99.99,
      CONSUMABLE: 9.99,
    },
    countries: ['IT'],
  },
  {
    marketPlace: AlexaProject.MarketPlace.CO_JP,
    currency: 'JPY',
    icon: '¥',
    min: 99,
    max: {
      ENTITLEMENT: 9999,
      SUBSCRIPTION: 9999,
      CONSUMABLE: 999,
    },
    countries: ['JP'],
  },
];
