import { Utils } from '@voiceflow/common';
import * as Realtime from '@voiceflow/realtime-sdk';

import { AbstractProjectChannelControl } from '@/actions/project/utils';

interface Payload extends Realtime.BaseVersionPayload, Realtime.actionUtils.CRUDValuePayload<Realtime.CustomBlock> {}

/**
 * NOTE: This no-op service is needed because of some quirks of the existing frontend state framework.
 *
 * The `createCRUDReducer` reducer helps you bootstrap a normalized store for your state slice, which simplifies
 * your work.
 *
 * Howeover, the `createCRUDReducer` forces you specify an action payload which contains an `id` field. This is
 * impossible to know before the action dispatch, because the `id` is supposed to be generated by MongoDB as an
 * ObjectID. However, the Redux-Logux framework forces us to send an action dispatch, then do the MongoDB
 * insert which causes ordering issues.
 *
 * Therefore, we need a separate "create" service that doesn't need you to provide an `id` in its action payload.
 *
 * However, we still need to update the normalized store, so we send a CRUD action from `createCRUDAction`
 *
 * However, naively doing this causes you to be hit with the "Useless action" error, because Logux has an internal
 * registry for what actions it expects. We need to create a service here so that we can dispatch the ADD action
 * from `createCRUDAction` from the custom ADD action we defined.
 *
 */
class AddCustomBlock extends AbstractProjectChannelControl<Payload> {
  protected actionCreator = Realtime.customBlock.crud.add;

  protected process = Utils.functional.noop;
}

export default AddCustomBlock;
