import reportTagsAdapter from '@/client/adapters/reportTags';
import { toast } from '@/components/Toast';
import { addReportTag, removeReportTag, replaceReportTags } from '@/ducks/reportTag/actions';
import { activeProjectIDSelector } from '@/ducks/session';
import { Sentiment, SystemTag } from '@/models';
import { Thunk } from '@/store/types';
import { cuid } from '@/utils/string';

export const DUMMY_DATA = [
  {
    id: '1',
    projectID: '1',
    label: 'happy path',
  },
  {
    id: '2',
    projectID: '1',
    label: 'sad path',
  },
  {
    id: '3',
    projectID: '1',
    label: 'user error',
  },
  {
    id: '4',
    projectID: '1',
    label: 'perfect interaction',
  },
  {
    id: SystemTag.REVIEWED,
    projectID: '1',
    label: '',
  },
  {
    id: SystemTag.SAVED,
    projectID: '1',
    label: '',
  },
  {
    id: Sentiment.EMOTION_POSITIVE,
    projectID: '1',
    label: '',
  },
];

export const fetchReportTags = (): Thunk => async (dispatch, _getState) => {
  try {
    // TODO fetch report tags from pg
    const reportTags = DUMMY_DATA.map((data) => reportTagsAdapter.fromDB(data));
    dispatch(replaceReportTags(reportTags));
  } catch (e) {
    toast.error('Error fetching report tags');
  }
};

export const createTag =
  // For undoing a delete, we want to preserve the id, so anything that was referencing it in transcripts, will still have the correct reference ID


    (tagLabel: string, id?: string): Thunk =>
    async (dispatch, getState) => {
      const state = getState();
      const activeProjectID = activeProjectIDSelector(state);

      // TODO client call to save to db
      const newTagID = id || cuid(); // TO BE GENERATED BY THE Back End

      dispatch(
        addReportTag(newTagID, {
          id: newTagID,
          projectID: activeProjectID!,
          label: tagLabel,
        })
      );
    };

export const deleteTag =
  (tagID: string): Thunk =>
  async (dispatch, _getState) => {
    // const state = getState();
    // const activeProjectID = activeProjectIDSelector(state);

    // TODO client call to save to db

    dispatch(removeReportTag(tagID));
  };
