/* eslint-disable no-process-env */

import { FeatureFlag } from '@voiceflow/realtime-sdk';

import { INTERCOM_ENABLED } from '.';

export { FeatureFlag };

const GADGETS_ENABLED = process.env.FF_GADGETS === 'true';
const NATO_APCO_ENABLED = process.env.FF_NATO_ACPO === 'true';
const OWNER_ROLE_ENABLED = process.env.FF_OWNER_ROLE === 'true';
const ASR_BYPASS_ENABLED = process.env.FF_ASR_BYPASS === 'true';
const MOTOROLA_SSO_ENABLED = process.env.FF_MOTOROLA_SSO === 'true';
const WAVENET_VOICES_ENABLED = process.env.FF_WAVENET_VOICES === 'true';
const ENTERPRISE_TRIAL_ENABLED = process.env.FF_ENTERPRISE_TRIAL_ENABLED === 'true';
const TOPICS_AND_COMPONENTS_ENABLED = process.env.FF_TOPICS_AND_COMPONENTS === 'true';
const ATOMIC_ACTIONS_PHASE_2_ENABLED = process.env.FF_ATOMIC_ACTIONS_PHASE_2 === 'true';
const ATOMIC_ACTIONS_AWARENESS_ENABLED = process.env.FF_ATOMIC_ACTIONS_AWARENESS === 'true';
const VARIABLE_STATES_STARTING_BLOCKS_ENABLED = process.env.VARIABLE_STATES_STARTING_BLOCKS === 'true';
const IMM_MODALS_V2 = process.env.FF_IMM_MODALS_V2 === 'true';
const NLU_MANAGER_ENABLED = process.env.FF_NLU_MANAGER === 'true';
const PROJECT_CREATE_ENABLED = process.env.FF_PROJECT_CREATE === 'true';
const EXPERIMENTAL_SYNC_LINKS_ENABLED = process.env.FF_EXPERIMENTAL_SYNC_LINKS === 'true';
const CHAT_CARDS_CAROUSEL_ENABLED = process.env.FF_CHAT_CARDS_CAROUSEL === 'true';
const REVISED_CREATOR_ENTITLEMENTS_ENABLED = process.env.FF_REVISED_CREATOR_ENTITLEMENTS === 'true';
const MIGRATION_SYSTEM_ENABLED = process.env.FF_MIGRATION_SYSTEM === 'true';

export const LOCAL_FEATURE_OVERRIDES: Partial<Record<FeatureFlag, boolean>> = {
  [FeatureFlag.GADGETS]: GADGETS_ENABLED,
  [FeatureFlag.NATO_APCO]: NATO_APCO_ENABLED,
  [FeatureFlag.OWNER_ROLE]: OWNER_ROLE_ENABLED,
  [FeatureFlag.ASR_BYPASS]: ASR_BYPASS_ENABLED,
  [FeatureFlag.MOTOROLA_SSO]: MOTOROLA_SSO_ENABLED,
  [FeatureFlag.WAVENET_VOICES]: WAVENET_VOICES_ENABLED,
  [FeatureFlag.ENTERPRISE_TRIAL]: ENTERPRISE_TRIAL_ENABLED,
  [FeatureFlag.INTERCOM_INTEGRATION]: INTERCOM_ENABLED,
  [FeatureFlag.TOPICS_AND_COMPONENTS]: TOPICS_AND_COMPONENTS_ENABLED,
  [FeatureFlag.IMM_MODALS_V2]: IMM_MODALS_V2,
  [FeatureFlag.NLU_MANAGER]: NLU_MANAGER_ENABLED,
  [FeatureFlag.PROJECT_CREATE]: PROJECT_CREATE_ENABLED,
  [FeatureFlag.VARIABLE_STATES_STARTING_BLOCKS]: VARIABLE_STATES_STARTING_BLOCKS_ENABLED,
  [FeatureFlag.MIGRATION_SYSTEM]: MIGRATION_SYSTEM_ENABLED,
  [FeatureFlag.ATOMIC_ACTIONS_PHASE_2]: ATOMIC_ACTIONS_PHASE_2_ENABLED,
  [FeatureFlag.ATOMIC_ACTIONS_AWARENESS]: ATOMIC_ACTIONS_AWARENESS_ENABLED,
  [FeatureFlag.CHAT_CARDS_CAROUSEL]: CHAT_CARDS_CAROUSEL_ENABLED,
  [FeatureFlag.EXPERIMENTAL_SYNC_LINKS]: EXPERIMENTAL_SYNC_LINKS_ENABLED,
  [FeatureFlag.REVISED_CREATOR_ENTITLEMENTS]: REVISED_CREATOR_ENTITLEMENTS_ENABLED,
};
