export enum Hotkey {
  COPY = 'COPY',
  UNDO = 'UNDO',
  REDO = 'REDO',
  DELETE = 'DELETE',
  ZOOM_IN = 'ZOOM_IN',
  ZOOM_OUT = 'ZOOM_OUT',
  SPOTLIGHT = 'SPOTLIGHT',
  ROOT_NODE = 'ROOT_NODE',
  LAUNCH_PAGE = 'LAUNCH_PAGE',
  DESIGN_PAGE = 'DESIGN_PAGE',
  USER_SPEECH = 'USER_SPEECH',
  OPEN_CMS_MODAL = 'OPEN_CMS_MODAL',
  OPEN_FLOW_MENU = 'OPEN_FLOW_MENU',
  OPEN_BLOCK_MENU = 'OPEN_BLOCK_MENU',
  OPEN_VARIABLE_MENU = 'OPEN_VARIABLE_MENU',
  OPEN_RESOURCES_DROPDOWN = 'OPEN_RESOURCES_DROPDOWN',
  TOGGLE_LEFT_SIDEBAR_LOCK = 'TOGGLE_LEFT_SIDEBAR_LOCK',
  OPEN_LEFT_SIDEBAR_STEPS_TAB = 'OPEN_LEFT_SIDEBAR_STEPS_TAB',
  OPEN_LEFT_SIDEBAR_FLOWS_TAB = 'OPEN_LEFT_SIDEBAR_FLOWS_TAB',
  OPEN_MARKUP = 'OPEN_MARKUP',
  OPEN_COMMENTING = 'OPEN_COMMENTING',
  CLOSE_CANVAS_MODE = 'CLOSE_CANVAS_MODE',
  SELECT_IMAGE_MARKUP = 'SELECT_IMAGE_MARKUP',
  SELECT_TEXT_MARKUP = 'SELECT_TEXT_MARKUP',
  DUPLICATE = 'DUPLICATE',
  SHOW_HIDE_UI = 'SHOW_HIDE_UI',
  MOVE_FORWARD = 'MOVE_FORWARD',
  MOVE_BACKWARD = 'MOVE_BACKWARD',
  TEST_MODE = 'TEST_MODE',
}

/**
 * syntax for keys can be found here:
 * https://craig.is/killing/mice
 */
const HOTKEY_MAPPING = {
  [Hotkey.COPY]: ['ctrl+c', 'meta+c'],
  [Hotkey.UNDO]: ['ctrl+z', 'meta+z'],
  [Hotkey.REDO]: ['ctrl+shift+z', 'meta+shift+z'],
  [Hotkey.DELETE]: ['del', 'backspace'],
  [Hotkey.ZOOM_IN]: ['=', 'shift+='],
  [Hotkey.ZOOM_OUT]: ['-', 'shift+-'],
  [Hotkey.ROOT_NODE]: 's',
  [Hotkey.SPOTLIGHT]: 'shift+space',
  [Hotkey.USER_SPEECH]: 'space',
  [Hotkey.OPEN_CMS_MODAL]: 'm',
  [Hotkey.OPEN_FLOW_MENU]: 'shift+2',
  [Hotkey.OPEN_BLOCK_MENU]: 'shift+1',
  [Hotkey.OPEN_VARIABLE_MENU]: 'shift+3',
  [Hotkey.OPEN_RESOURCES_DROPDOWN]: 'i',
  [Hotkey.DESIGN_PAGE]: '1',
  [Hotkey.LAUNCH_PAGE]: '2',
  [Hotkey.TOGGLE_LEFT_SIDEBAR_LOCK]: ['/', '?'],
  [Hotkey.OPEN_LEFT_SIDEBAR_STEPS_TAB]: ['shift+,', ','],
  [Hotkey.OPEN_LEFT_SIDEBAR_FLOWS_TAB]: ['shift+.', '.'],
  [Hotkey.OPEN_MARKUP]: ['a'],
  [Hotkey.OPEN_COMMENTING]: ['c'],
  [Hotkey.CLOSE_CANVAS_MODE]: ['esc'],
  [Hotkey.SELECT_IMAGE_MARKUP]: ['i'],
  [Hotkey.SELECT_TEXT_MARKUP]: ['t'],
  [Hotkey.DUPLICATE]: ['ctrl+d', 'meta+d'],
  [Hotkey.SHOW_HIDE_UI]: ['ctrl+\\', 'meta+\\'],
  [Hotkey.MOVE_FORWARD]: ['right'],
  [Hotkey.MOVE_BACKWARD]: ['left'],
  [Hotkey.TEST_MODE]: 't',
};

export default HOTKEY_MAPPING;
