export enum AlexaStageType {
  IDLE = 'IDLE',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  PROGRESS = 'PROGRESS',
  WAIT_ACCOUNT = 'WAIT_ACCOUNT',
  WAIT_VENDORS = 'WAIT_VENDORS',
  WAIT_INVOCATION_NAME = 'WAIT_INVOCATION_NAME',
}

export enum AlexaJobErrorType {
  RENDERING = 'RENDERING',
  ENABLING_SKILL = 'ENABLING_SKILL',
  SUBMITTING_PROJECT = 'SUBMITTING_PROJECT',
  SUBMITTING_FOR_REVIEW = 'SUBMITTING_FOR_REVIEW',
  CHECKING_INTERACTION_MODEL_STATUS = 'CHECKING_INTERACTION_MODEL_STATUS',
}

export enum AlexaJobSuccessType {
  UPLOAD = 'UPLOAD',
  SUBMIT = 'SUBMIT',
}
