version: '3.9' # optional since v1.27.0
services:
  proxy:
    image: nginx:stable
    volumes:
      - ./config/nginx.proxy.template:/etc/nginx/conf.d/proxy.template
      - ./config/proxy.conf:/etc/nginx/includes/proxy.conf
      - ./certs:/certs
    ports:
      - '3002:80'
    environment:
      - TARGET=host.docker.internal:3000
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  # # DO NOT USE: FOR DEBUGGING ONLY!
  # e2e:
  #   image: nginx:stable
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #   - ./build/.:/var/www
  #   - ./certs/.:/etc/nginx/ssl
  #   - ./config/nginx.e2e.conf:/etc/nginx/conf.d/default.conf
  #   command: nginx -g 'daemon off;'
